### PR TITLE
Fix automatically loading research variants when loading a case

### LINKED ISSUE #4661: "scout setup demo" is loading also research variants, but they are not shown as a category of available vars on case page
**To Reproduce**
run `scout setup demo`
- Load the case clone of 643594 -> `scout --demo load case scout/demo/643595.config.yaml`
- Go on case 643595 and mark the usual POT1 variant as causative
- Go on case 643594 and see that when matching causatives contains 2 variants instead of one:

image

One is a clinical variant and one is a research variant. 
BUT!
Case 643594 doesn't have research variants links:

image

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug.
- Fix loading also research variants when loading a case (fix #4661 )

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. Locally, remove all cases from the demo instance 
2. Using main branch install demo case -> `scout --demo load case scout/demo/643594.config.yaml`
3. Note the number and type of variants loaded (clinical and research)
4. Remove case -> `scout --demo delete case -i cust000 -c internal_id`
5. Repeat step 2 & 3 using the branch

**Expected outcome**:
- This branch will load only clinical variants

**Review:**
- [x] code approved by DN
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Loading variants using main branch:

image

Remove case:

image

Loading using this branch:

image

**Review by dnil — APPROVED** [review]
💯

**Comment by dnil** [comment]
Maybe you could fix the changelog here as well to reflect the MT vars not being in 4.82..

**Comment by northwestwitch** [comment]
> Maybe you could fix the changelog here as well to reflect the MT VCFs not being in 4.82..

Yes, I will!

**Pull request merged**
