### PR TITLE
return always prio cases

### LINKED ISSUE #1494: Prioritized cases again
Sorry @sofievonlanthen - we have managed to botch the prioritised cases first rule, presumably when re-enabling the case count again. Prioritised cases are currently only shown first, if shown at all.

https://scout-stage.scilifelab.se/cust002?query=&limit=100
Screenshot 2019-11-12 at 20 22 01

https://scout-stage.scilifelab.se/cust002?query=&limit=200
Screenshot 2019-11-12 at 20 22 22

### PR DESCRIPTION
**Pull request by northwestwitch**
This is an alternative way to fix #1494. 
I didn't like much the idea of adding an extra query to the whole process so I wrote this attempt to do the same without this step. I don't know if it works, should be tested on stage!

**How to test**:
1. Go on scout stage and make sure that 1 old case is prioritized for cust000 : 15026-miptest
1. From master branch. If you limit the case query to 1 case: (https://scout-stage.scilifelab.se/cust000?query=&limit=1) then the case returned is the latest edited case (15078-mip7), not the prio one.
1. Install this branch and run the same query. The prio sample should be returned.
1. Bonus test. Run this query: https://scout-stage.scilifelab.se/cust000?query=&limit=2 and 2 samples will be returned: both the prio and the latest edited (15078-mip7)

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
@dnil I wrote this alternative to #1520. It's not that I didn't like yours, but I wanted to avoid an extra query!

**Comment by northwestwitch** [comment]
Woops, this needs to be fixed:
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 21, in decorated_function
    context = f(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/views.py", line 67, in cases
    data = controllers.cases(store, cases_by_status, limit, sort_by, sort_order)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/controllers.py", line 77, in cases
    case_groups[status] = sorted(case_groups[status], key = lambda k: k[sort_by], reverse=reverse)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/controllers.py", line 77, in <lambda>
    case_groups[status] = sorted(case_groups[status], key = lambda k: k[sort_by], reverse=reverse)
KeyError: 'track'

**Comment by dnil** [comment]
This has the advantage and disadvantage that control of the data is moved to python. I would very much have preferred the >3.4 solution. Cases is not a huge collection, so I guess it is doable though using the db should be faster and save some temp RAM. But, once we have decided to duplicate all cases to memory, there is a lot of good stuff to be done. For one we could rewrite the case query functions to something a lot simpler. 

The current implementation again does not always show the prioritised cases, only puts them at the top if they are shown. But that can be fixed (and may not be desired for *all* case queries).

**Comment by northwestwitch** [comment]
FIxed. I'd like to update mongo as well, both our solutions are sad attempts at workarounds because we can't use the right methods :(

**Comment by northwestwitch** [comment]
Bye, it was good while it lasted. #1520 wins! :(

**Comment by dnil** [comment]
:wave: ⚰️ 🥀

**Pull request closed without merging**
