### PR TITLE
Patch release 4.17.1

### PR DESCRIPTION
**Pull request by northwestwitch**
This is a patch release because it's fixing the lack of data in the cytoband by chromosome objects populating the variants filter form.

The bug was observed on stage environment in a number of cases with case["genome_build"] either None or non standard ("37" or "38). It failed for instance on a case with build="grch37". 

We should be more strict in general when it comes to parsing the genome build value provided by the load config file.

**How to test**:
1. Install on stage and try to use the filter by cytobands form (SNVs, SVs variants page)

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by MM
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Tested on stage and it works:

image

**Comment by northwestwitch** [comment]
Ready for review!

**Comment by northwestwitch** [comment]
> I have not followed the cytobandhandlerthing but I trust you!!

Thanks!!

**Comment by dnil** [comment]
Well done! It’s in a way more about the handling of build version. I suspect we have a few more places where a defined but unexpected build value could cause a hiccup.

**Comment by northwestwitch** [comment]
> Well done! It’s in a way more about the handling of build version. I suspect we have a few more places where a defined but unexpected build value could cause a hiccup.

Oh yes, I am certain we have plenty of those, unfortunately!

**Pull request merged**
