### PR TITLE
Allow multiple COSMIC links for a cancer variant

### PR DESCRIPTION
**Pull request by northwestwitch**
Partial fix for #2826, issue n.3. COSMIC IDs are correctly saved to database for cancer variants but just one ID is used to create links to cosmic

**How to test**:
1. Locally on master branch go to the first variant of demo cancer case, TP53 (you should load demo cancer case first)
2. Make sure that it contains only one link to COSMIC
3. Switch to this branch and you should be able to see 4 COSMIC links for 4 different cosmic IDs (hover on the buttons to see the actual id). These links should work.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by mikaell

### CODE REVIEW

**Comment by mikaell** [comment]
Works as expected. 

But the Cosmic links look a bit cramped and are hard to distinguish from each other. Suggestions:
* Add a small amount of space
* Give the buttons different names e.g. Cosmic-1, Cosmic-2 or reflecting the id e.g. Cosmic-0886, Cosmic-2386.

image

**Review by mikaell — APPROVED** [review]
Looks good!

**Comment by northwestwitch** [comment]
Fixed it, it looks like this now: 
image

Thanks for the review and the nice suggestions!

**Comment by hassanfa** [comment]
@northwestwitch you're fast! 😄

**Pull request merged**
