### PR TITLE
Fix broken load case when case has no custom images

### LINKED ISSUE #2967: Broken load case cli command for cases with no custom images
Master (command line):
image

Master (docker image):
image

To reproduce, load demo case with command: `scout --demo load case scout/demo/cancer.load_config.yaml`

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #2967 

**How to test**:
1. Locally from master branch, run `scout --demo load case scout/demo/cancer.load_config.yaml`
2. Switch to this branch and run the same command

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by ML
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Master:
image


This branch: 🆗 
image

**Comment by northwestwitch** [comment]
This is ready for review!

**Comment by mikaell** [comment]
I'll have a look.

**Review by mikaell — APPROVED** [review]
Nice bug fix.

**Pull request merged**
