### PR TITLE
Start preparing v4.50

### PR DESCRIPTION
**Pull request by dnil**
This PR marks a new Scout release. We apply semantic versioning. This is a minor release since it both adds new features and fixes issues with old ones.

### Added
- [x] Individual-specific OMIM terms
- [x] OMIM disease descriptions in ClinVar submission form
~~Add a toggle for melter rerun monitoring of cases~~
- [x] Add a config option to show the rerun monitoring toggle
- [x] Add a cli option to export cases with rerun monitoring enabled
- [x] Add a link to STRipy for STR variants
- [x] OMIM terms in general case report
- [x] Individual-level info on OMIM and HPO terms in general case report
- [x] PanelApp gene link among the external links on variant page
### Fixed
- [x] A malformed panel id request would crash with exception: now gives user warning flash with redirect
- [x] Link to HPO resource file hosted on `http://purl.obolibrary.org`
- [x] Gene search form when gene exists only in build 38
- [x] Fixed odd redirect error and poor error message on missing column for gene panel csv upload
- [x] Typo in parse variant transcripts function
- [x] Modified keys name used to parse local observations (archived) frequencies to reflect change in MIP keys naming
- [x] Better error handling for partly broken/timed out chanjo reports
- [x] Broken javascript code when case Chromograph data is malformed
- [x] Broader space for case synopsis in general report
- [x] Show partial causatives on causatives and matching causatives panels
### Changed
- [x] Slightly smaller and improved layout of content in case PDF report
- [x] Relabel more cancer variant pages somatic for navigation
- [x] Removed unused `add_compounds` param from variant controllers function
- [x] Changed default hg19 genome for IGV.js to legacy hg19_1kg_decoy to fix a few problematic loci
- [x] Reduce code complexity (parse/ensembl.py)
- [x] Silence certain fields in ClinVar export if prioritised ones exist (chrom-start-end if hgvs exist)
- [x] Made phenotype non-mandatory when marking a variant as partial causative
- [x] Only one phenotype condition type (OMIM or HPO) per variant is used in ClinVar submissions
- [x] ClinVar submission variant condition prefers OMIM over HPO if available
- [x] Use lighter version of gene objects in Omim MongoDB adapter, panels controllers, panels views and institute controllers
- [x] Gene-variants table size is now adaptive
- [x] Remove unused file upload on gene-variants page

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by DN, CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is deployed on cv-vm1 now, so we can start testing!

**Comment by dnil** [comment]
Sorry, just merged the filter-unaffected! I can redeploy once it finishes!

**Comment by northwestwitch** [comment]
I've installed this branch also on Hasta stage and tried to reupload [this](https://scout-stage.scilifelab.se/cust000/ACC7948A21_ds) cancer case: all good!

**Review by northwestwitch — APPROVED** [review]
👍🏻

**Comment by northwestwitch** [comment]
Deployed on Hasta stage:

image

And Hasta prod:

image

**Pull request merged**
