### PR TITLE
Fix #2160 - BP2 IGV chrom for variant view

### LINKED ISSUE #2160: SV chrom for IGV & UCSC have mutated..
Spot the difference:
Screenshot 2020-10-14 at 11 31 02

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

**How to test**:
1. look at a BND on the variant view and note if the BP2 button shows and opens IGV on the correct chromosome. Broken on master, works in branch.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by DN, CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
When did this happen, must have been quite some time ago, but we haven't noticed

**Comment by dnil** [comment]
I'm guessing 8 months, when Måns and I rearranged the cards? But dunno really.. I suppose BNDs have become more popular now with better frequency filters.

**Comment by northwestwitch** [comment]
Test example: https://scout-stage.scilifelab.se/cust000/643594-300M/sv/variants/1b212ea0cea32c6b62c7a3798025783b

**Comment by dnil** [comment]
Thanks - I was just looking, only got this far:
Screenshot 2020-10-14 at 14 59 50

**Comment by dnil** [comment]
@northwestwitch test variant works:
Screenshot 2020-10-14 at 15 01 26
Screenshot 2020-10-14 at 15 01 31

**Review by northwestwitch — APPROVED** [review]
Looking good, but I was wondering, does it really make sense to display that huge lenght?

image

**Comment by dnil** [comment]
Looks like its working. Merging!

**Pull request merged**
