### PR TITLE
Scout release 4.6.0

### PR DESCRIPTION
**Pull request by northwestwitch**
Scout version 4.6.0

### Added
- Description of Scout branching model in CONTRIBUTING doc
- Causatives in alphabetical order, display ACMG classification and filter by gene.
- Added 'external' to the list of analysis type options
- Adds functionality to display "Tissue type". Passed via load config.
- Update to IGV 2.

### Fixed
- Fixed alignment visualization and vcf2cytosure availability for demo case samples
- Fixed 3 bugs affecting SV pages visualization
- Reintroduced the --version cli option
- Fixed variants query by panel (hpo panel + gene panel).
- Downloaded MT report contains excel files with individuals' display name
- Refactored code in parsing of config files.

All changes have been verified before merging to master. All changes together (this branch) has been verified both on clinical-db stage and hasta-stage.

This is a minor version change because it contains bugfixes and new features but does not alter the API / methods used by other apps, that are left unchanged from the previous major version.

- [x] code reviewed by dNil
- [x] verification by @northwestwitch 
- [x] approved for deployment by @ingkebil

### CODE REVIEW

**Comment by northwestwitch** [comment]
Could someone approve? @mikaell?

**Comment by northwestwitch** [comment]
@ingkebil @patrikgrenfeldt could you approve the deployment? Thanks!

**Comment by northwestwitch** [comment]
> Did you motivate the level of version change somewhere? It’s clearly about right: certainly no major.

I will do it. And I need to check something before merging and deploying. I need to test if it is possible to run some basic commands that connect to the database on hasta stage. It's not sufficient that it installs. We might deploy a bit later today after all!

**Comment by northwestwitch** [comment]
> Looks good!

Thanks!

**Comment by northwestwitch** [comment]
Just tested the connection to the database on hasta stage cli .. All good! 👍

**Comment by northwestwitch** [comment]
> > Did you motivate the level of version change somewhere? It’s clearly about right: certainly no major.

Done!

**Comment by ingkebil** [comment]
Approved! Go ahead! :shipit:

**Comment by ingkebil** [comment]
@northwestwitch : can you next time take screenshots or c/p what you did for your test? thanks :)

**Comment by northwestwitch** [comment]
> ou next time take screenshots or c/p what you did for your test? thanks :)

Sure! Thanks!

**Pull request merged**
