### PR TITLE
Chanjo2 MANE coverage overview

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug.
- Adds a link to the new MANE overview on the case side panel
- Adds a link also on the gene panel page

image

image

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. Deploy this branch of scout and [this branch](https://github.com/Clinical-Genomics/chanjo2/pull/365) of chanjo2
2. From the page of a case run with build 38, click on the MANE coverage overview and make sure the data returned is correct

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by 
- [x] tests executed by CR, Jakob37

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is not easily testable on our stage server since we have only one case with d4 files and unfortunately has build 37, but perhaps you can give it a try with one of your build 38 cases @Jakob37 ?

**Comment by Jakob37** [comment]
> This is not easily testable on our stage server since we have only one case with d4 files and unfortunately has build 37, but perhaps you can give it a try with one of your build 38 cases @Jakob37 ?

I'll test!

**Comment by Jakob37** [comment]
Links show up and I get a report. Results looks sane. Nice 👌 

mane_report
mane_overview
mane_coverage_report

Super tiny feedback is that the mouse pointer icon does not switch to a hand (👆) when hovering over the Chanjo2 chain link icons, but does so over the other icons. Same on both the case and the panel pages.

But anyways. It looks great, and seems to be doing what it should!

**Comment by Jakob37** [comment]
A few genes have no MANE assigned. 

no_mane

Looking at the gene page of one, it has both "MANE Select" and "MANE Plus Clinical" (the gene is HRAS).

no_mane_gene_page

Not sure what I am looking at here. Maybe you are more familiar with this?

I'll test a bit more after lunch 🥗

**Comment by northwestwitch** [comment]
> Looking at the gene page of one, it has both "MANE Select" and "MANE Plus Clinical" (the gene is HRAS).
> Not sure what I am looking at here. Maybe you are more familiar with this?
> 

Ah yes, I can reproduce it locally. It's a bug. I'll fix it!

**Comment by Jakob37** [comment]
A small feedback might be that the mean values probably could be rounded to two digits or something, i.e. 25.05, 67.17 ...

**Comment by northwestwitch** [comment]
> A small feedback might be that the mean values probably could be rounded to two digits or something, i.e. 25.05, 67.17 ...

I pushed some fixes for the missing badges and for the number rounding. Give it another go when you have time @Jakob37

**Comment by Jakob37** [comment]
Looks good now!

working_mane

**Comment by Jakob37** [comment]
> Super tiny feedback is that the mouse pointer icon does not switch to a hand (👆) when hovering over the Chanjo2 chain link icons, but does so over the other icons. Same for URLs in the list on the panel page.

Would it be possible to fix this as well? To make it clear for the user that the icon is clickable.

**Comment by Jakob37** [comment]
I'll check the code as well and wrap the review later today or first thing tomorrow!

**Comment by northwestwitch** [comment]
> Would it be possible to fix this as well? To make it clear for the user that the icon is clickable.

Ah yes,I'll check it out

**Comment by northwestwitch** [comment]
> Super tiny feedback is that the mouse pointer icon does not switch to a hand (👆) when hovering over the Chanjo2 chain link icons, but does so over the other icons. Same for URLs in the list on the panel page.
> 
> Would it be possible to fix this as well? To make it clear for the user that the icon is clickable.

This should also be fixed now, both on case sidebar and panel page

**Comment by Jakob37** [comment]
> > Super tiny feedback is that the mouse pointer icon does not switch to a hand (👆) when hovering over the Chanjo2 chain link icons, but does so over the other icons. Same for URLs in the list on the panel page.
> > Would it be possible to fix this as well? To make it clear for the user that the icon is clickable.
> 
> This should also be fixed now, both on case sidebar and panel page

Nice, it works! This has been itching me for long time, but haven't felt big enough to bring up. Thanks for fixing 😅

**Review by Jakob37 — APPROVED** [review]
Worked nicely in testing for me. Nothing to comment on in the code.

**Comment by northwestwitch** [comment]
> Worked nicely in testing for me. Nothing to comment on in the code.

Nice! Thanks for testing and the review! 🙏🏻

**Comment by northwestwitch** [comment]
> This has been itching me for long time, but haven't felt big enough to bring up. Thanks for fixing 😅

Don't be shy, they pay me also for fixing these things! 😆

**Pull request merged**
