### PR TITLE
Export validated variants

### PR DESCRIPTION
**Pull request by northwestwitch**
- Created a cli to export validated variants for a single institute. One excel file is created.

- Created a button to export validated variants for all institutes of a user. One excel file per institute is created and download returns a zip file with these excel files. This button is in the dashboard, under the variant stats:
image

- Test for checking that variant query and document line creation works fine

### CODE REVIEW

**Comment by northwestwitch** [comment]
fix #1139

**Comment by northwestwitch** [comment]
No, is stage available? It would be nice to test if from there you can produce on excel sheet per institute

**Comment by moonso** [comment]
Should be fine to test on stage as long as you talk to @dnil first

**Comment by northwestwitch** [comment]
> Should be fine to test on stage as long as you talk to @dnil first

Yes I asked him first. Thanks for the review :)

**Comment by northwestwitch** [comment]
Testing on stage and doesn't work. I guess the query takes too much time to run. I'll investigate

**Comment by moonso** [comment]
Didn't you get the mail from scout-browser? I think there was a bug in the code with institutes on case_obj. Guess it should be collaborators instead?

**Comment by northwestwitch** [comment]
I didn't get it, could you post the content here? Thanks

**Comment by northwestwitch** [comment]
Thanks @moonso for your suggestion to use the variant events, it's super fast now!!

I've updated scout-stage with this PR and it works. In the beginning I was a bit surprised that when I tried to download the validated variants and I just got those from one institute, but it's the intended behavior I guess, so keep in mind that if you are an admin you don't get to download everything but just stuff from your institute.

If we don't like this we could change at a later stage.

**Pull request merged**
