### PR TITLE
Add lanscape orientation style to demo cancer coverage and QC report HTML file

### LINKED ISSUE #2442: PDF Delivery report is truncated
All the coverage qc reports that are delivered to Scout through deliver_report functionality are truncated and data from last column is unreadable. HTML is readable: https://scout.scilifelab.se/cust107/2017-00600-reprep

Reproduce:
1. Select a cancer case with a coverage qc report:
image

2. Select PDF report:
image

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #2442, it wasn't that complicated! Tested on Chome and Safari

**How to test**:
1. Load a demo cancer case via config file into a local scout instance:
```
scout --demo load case scout/demo/cancer.load_config.yaml
```
1. Check how the PDF version of the coverage_qc_report looks on master and this branch

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
On master:

image



This branch:

image

**Comment by northwestwitch** [comment]
Doesn't affect the layout of the HTML version of the report, checked just in case:

image

**Comment by dnil** [comment]
Nice!

**Comment by northwestwitch** [comment]
> Did you also PR Balsamic with the same?

Yes, already merged!

**Pull request merged**
