### PR TITLE
New minor release 4.32

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- Load and show MITOMAP associated diseases from VCF (INFO field: MitomapAssociatedDiseases, via HmtNote)
- Show variant allele frequencies for mitochondrial variants (GRCh38 cases)
- Extend "public" json API with diseases (OMIM) and phenotypes (HPO)
- HPO gene list download now has option for clinical and non-clinical genes
- Display gene splice junctions data in sashimi plots
- Update case individuals with splice junctions tracks
- Simple Docker compose for development with local build
- Make Phenomodels subpanels collapsible
- User side documentation of cytogenomics features (Gens, Chromograph, vcf2cytosure, rhocall)
- iSort GitHub Action
### Fixed
- Show other causative once, even if several events point to it
- Filtering variants by mitochondrial chromosome for cases with genome build=38
- HPO gene search button triggers any warnings for clinical / non-existing genes also on first search
- Fixed a bug in variants pages caused by MT variants without alt_frequency
- Tests for CADD score parsing function
- Fixed the look of IGV settings on SNV variant page
- Cases analyzed once shown as `rerun`
- Missing case track on case re-upload
- Fixed severity rank for SO term "regulatory region ablation"
### Changed
- Refactor according to CodeFactor - mostly reuse of duplicated code
- Phenomodels language adjustment
- Open variants in a new window (from variants page)
- Open overlapping and compound variants in a new window (from variant page)
- gnomAD link points to gnomAD v.3 (build GRCh38) for mitochondrial variants.
- Display only number of affected genes for dismissed SVs in general report
- Chromosome build check when populating the variants filter chromosome selection
- Display mitochondrial and rare diseases coverage report in cases with missing 'rare' track

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
Waiting to merge a couple of bugfixes before merging, but we can start testing what we already have:

## [4.32]
### Added
- [ ] Load and show MITOMAP associated diseases from VCF (INFO field: MitomapAssociatedDiseases, via HmtNote)
- [ ] Show variant allele frequencies for mitochondrial variants
- [ ] Extend "public" json API with diseases (OMIM) and phenotypes (HPO)
- [ ] HPO gene list download now has option for clinical and non-clinical genes
- [ ] Display gene splice junctions data in sashimi plots
- [ ] Update case individuals with splice junctions tracks
- [ ] Simple Docker compose for development with local build
- [ ] Make Phenomodels subpanels collapsible
### Fixed
- [ ] Show other causative once, even if several events point to it
- [ ] Filtering variants by mitochondrial chromosome for cases with genome build=38
- [ ] HPO gene search button triggers any warnings for clinical / non-existing genes also on first search
- [ ] Fixed a bug in variants pages caused by MT variants without alt_frequency
- [ ] Tests for CADD score parsing function
### Changed
- [ ] Refactor according to CodeFactor - mostly reuse of duplicated code
- [ ] Phenomodels language adjustment
- [ ] Open variants in a new window (from variants page)
- [ ] Open overlapping and compound variants in a new window (from variant page)
- [ ] gnomAD link points to gnomAD v.3 (build GRCh38) for mitochondrial variants.
- [ ] Display only number of affected genes for dismissed SVs in general report

**Comment by northwestwitch** [comment]
I'm going to install it on clinical-db stage

**Comment by dnil** [comment]
I started writing a little on Chromograph for the user docs, and realise there are many new features we have not written much about. Something for a rainy day as well..

**Comment by northwestwitch** [comment]
This is on stage now. I'll start checking now!

**Comment by northwestwitch** [comment]
First problem: A test case in genome build 37 is showing "M" (not "MT") chromosome in variants filter, and when you select by this chromosome, no variant is returned. Will fix!

**Comment by northwestwitch** [comment]
We should probably upload a case on stage to make sure the new MT parsing features work fine on chr build 37. I'll reupload  vitalmouse (https://scout-stage.scilifelab.se/cust000/643594-300M) or some other recent test case

**Comment by northwestwitch** [comment]
I've re-uploaded [keenviper](https://scout-stage.scilifelab.se/cust002/F0013248-3) on stage using this branch! Case upload worked fine!

**Comment by dnil** [comment]
Good timing: https://github.com/obophenotype/human-phenotype-ontology/releases/tag/v2021-04-13

**Comment by northwestwitch** [comment]
Checking the "Show other causative once, even if several events point to it" on clinical-db stage.

For instance [this causative variant](https://scout-stage.scilifelab.se/cust000/643594/4c7d5c70d955875504db72ef8e1abe77) is the same as this: https://scout-stage.scilifelab.se/cust002/F0003953/18fa94f464ae970d736b010ff7460baa

How come that in the second case it doesn't show as other causative? 🤔

**Comment by dnil** [comment]
> How come that in the second case it doesn't show as other causative? 🤔

From chat, for reference: different institutes w/o collaborator status on the case.

**Comment by northwestwitch** [comment]
Deployed on 

- hasta stage: 🆗 
image

- hasta prod: 🆗 
image

- clinical-db stage: 🆗 
image

- clinical-db prod: 🆗 
image

**Pull request merged**
