### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by moonso**
This PR adds updates some of the deprecated functions.

**How to test**:
1. Install this branch
1. Run the tests and see that most deprecation warnings are gone

**Expected outcome**:
Deprecation warnings from pymongo, interval tree and logging should be gone

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "merge and deploy" approved by

### CODE REVIEW

**Comment by moonso** [comment]
If you know how to fix deprecation warnings for `defusedxml` and wtfforms please go ahead and fix those here @dnil and @northwestwitch

**Comment by northwestwitch** [comment]
Could you describe a case scenario where you'll get warnings? I didn't see any so far

**Comment by moonso** [comment]
I get hundreds of warnings when I write `pytest -v tests/` before this PR

**Comment by moonso** [comment]
Skärmavbild 2019-08-28 kl  11 07 20
The ones that are left looks like this

**Comment by northwestwitch** [comment]
> Skärmavbild 2019-08-28 kl 11 07 20
> The ones that are left looks like this

Weird, I don't get any warnings? Am I in an archaic environment or something?

**Comment by dnil** [comment]
:smile: I usually still test locally on 3.6, though most things are ok for 3.7. Perhaps not all?

**Comment by northwestwitch** [comment]
> I usually still test locally on 3.6, though most things are ok for 3.7. Perhaps not all?

**Comment by moonso** [comment]
The warnings are correct and they are on dependency level. For example insert is deprecated in pymongo and search is deprecated in intervaltree.

**Comment by northwestwitch** [comment]
I'm giving it a try installing scout on an environment with python=3.7. I'm not getting any warnings .

@moonso do you get warnings if you use python 3.6?

**Comment by moonso** [comment]
I'm using python 3.7. It should not depend on the python version though. This is pytest who show all the warnings and the warnings are raised by the other packages. I think it has to do with what version of pytest you are using, I have 
```
(scout3) MansMacAirDisplay:scout mansmagnusson$ pytest --version
This is pytest version 3.8.0, imported from /Users/mansmagnusson/miniconda3/envs/scout3/lib/python3.7/site-packages/pytest.py
```

could you check that instead?

**Comment by northwestwitch** [comment]
> I'm using python 3.7.

I'm using python 3.6 for developing and have installed pytest 3.6.
Do you remember that we have a lot of dependency problems on the server environments because the other software use python 3.6? I wonder if we should stick to python 3.6 for the time being, and move to the 3.7 when scout will be installed on its own environment.

I'm afraid that if you make the changes in this PR you would not have background compatibility with the prod environment where scout is running, that has python 3.6

**Comment by moonso** [comment]
```
(scout36) MansMacAirDisplay:scout mansmagnusson$ pytest --version
This is pytest version 3.8.0, imported from /Users/mansmagnusson/miniconda3/envs/scout36/lib/python3.6/site-packages/pytest.py
setuptools registered plugins:
  pytest-flask-0.12.0 at /Users/mansmagnusson/miniconda3/envs/scout36/lib/python3.6/site-packages/pytest_flask/plugin.py
  pytest-cov-2.6.0 at /Users/mansmagnusson/miniconda3/envs/scout36/lib/python3.6/site-packages/pytest_cov/plugin.py
(scout36) MansMacAirDisplay:scout mansmagnusson$ python --version
Python 3.6.6 :: Anaconda, Inc.
(scout36) MansMacAirDisplay:scout mansmagnusson$ pytsen -v tests/
.
.
.
================================================================================= warnings summary ==================================================================================
/Users/mansmagnusson/miniconda3/envs/scout36/lib/python3.6/site-packages/wtforms/fields/core.py:353: DeprecationWarning: The TextField alias for StringField has been deprecated and will be removed in WTForms 3.0
  return self.field_class(*self.args, **kw)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================================================================== 490 passed, 1 warnings in 302.43 seconds ======================================================================
```

**Comment by moonso** [comment]
It does not have to do with the python version as you can see above. Please run the exact commands in you environment, you should be given the same result.

**Comment by northwestwitch** [comment]
> It does not have to do with the python version as you can see above. Please run the exact commands in you environment, you should be given the same result.

What's that pytsen thing, I don't have it. Anyway I've tested the installation and test running and it works, so OK!

**Comment by moonso** [comment]
Haha it should be pytest! not pytsen

**Pull request merged**
