### PR TITLE
Attempt to fix #4852 by explicitly loading variants

### LINKED ISSUE #4852: Omics variants view test coverage unexpectedly low?
The tests appear to run, but probably there is something off with case provisioning so the omics_variants never make it in there?
Screenshot 2024-09-13 at 11 41 43

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by pytest. Actually this time.

### CODE REVIEW

**Comment by dnil** [comment]
I have change my mind: BASIC and assembler were a lot cleaner.
Screenshot 2024-09-13 at 14 07 48

**Comment by dnil** [comment]
You would think that the test discovery would work the same way if you run it on a parent directory or grandparent directory as well... 🫠 

You would also think that tests, with functions named test, in a super-folder named tests, given explicitly to pytest when starting the test (and that run if you give the subfolder name) would run by default. No. You have to name every file in the whole directory tree something that begins or ends with "test". Was this developed by Microsoft?

**Comment by dnil** [comment]
Anyway.
Screenshot 2024-09-13 at 14 18 34

**Comment by northwestwitch** [comment]
> No. You have to name every file in the whole directory tree something that begins or ends with "test".

I knew actually. That's why in general when I'm developing I call the single test specifically introducing an error so I know if it runs or not. It fooled me already 😆

**Comment by dnil** [comment]
Hehe, I see. Calling the single test or subdirectories works even - I do already locally just to save time. You mean you actually run the whole test barrage with an error once for every new test?

One might also take into consideration the oaf-ness of the guy who sees a huuuuge tree with files named "test_*.py" and decides it would be a good idea to introduce the first one that doesn't. 😆

**Comment by northwestwitch** [comment]
> Hehe, I see. Calling the single test or subdirectories works even if running on the top level dir doesn't. I do already locally just to save time. You mean you actually run the whole test barrage with an error once for every new test?

No like, I create the test and inside I write something like: asset "BLABLA" == "BLEBLE" and see if I get the error. Just once

**Comment by dnil** [comment]
> > Hehe, I see. Calling the single test or subdirectories works even if running on the top level dir doesn't. I do already locally just to save time. You mean you actually run the whole test barrage with an error once for every new test?
> 
> No like, I create the test and inside I write something like: asset "BLABLA" == "BLEBLE" and see if I get the error. Just once

Ah on GitHub actions? Gotcha, good practice.

**Comment by northwestwitch** [comment]
> Ah on GitHub actions? Gotcha, good practice.

no, locally

**Comment by dnil** [comment]
> > Ah on GitHub actions? Gotcha, good practice.
> 
> no, locally

But that takes like 40 mins?!

**Comment by northwestwitch** [comment]
> But that takes like 40 mins?!

Nope, just my test

**Comment by dnil** [comment]
> > But that takes like 40 mins?!
> 
> Nope, just my test

Both 
```
pytest tests/server/blueprints/omics_variants/omics_variants.py::test_filter_export_omics_variants
```
and 
```
pytest tests/server/blueprints/omics_variants
```
work just fine... 🫠 
Just not only 
```
pytest
```

**Comment by dnil** [comment]
> > > But that takes like 40 mins?!
> > 
> > 
> > Nope, just my test
> 
> But I think I also run all tests once per PR. Same time as I develop somewhere else. Locally I mean. Or if I'm on servers I run tests on all the servers dir

Sure, same, but I would not notice the omission of one new test there without like as you suggested an expected assert error in there! Anyway, not the nicest mechanism, though one could kind of infer the idea from looking at a hundred examples. >XD

**Review by northwestwitch — APPROVED** [review]
Looks good! 👍🏻

**Pull request merged**
