### PR TITLE
test unfreeze package

### PR DESCRIPTION
**Pull request by northwestwitch**
unfreeze mkdocs-material. Don't know why we froze in the first place

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by
- [x] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Nope! I don't get it, in which other package is virtualenv?

**Comment by dnil** [comment]
No!? Black I guess, but who else?

**Comment by dnil** [comment]
pre-commit!
>Requirement already satisfied: virtualenv>=20.0.8 in /usr/local/miniconda3/envs/scout38/lib/python3.8/site-packages (from pre-commit->-r requirements-dev.txt (line 13)) (20.0.31)

**Comment by dnil** [comment]
So, precommit wants virtualenv>=20.0.8, virtualenv of the version we get has importlib-metadata frozen to <2, but we have a 2.0 from somewhere else..

**Comment by dnil** [comment]
To complicate things, that import of importlib-metadata is different for different python versions in pre-commit.

**Comment by dnil** [comment]
Testing! 😊

**Comment by northwestwitch** [comment]
We could always remove pre-commit. @elevu is not using it anyway, see the commit history if her PR (half hers, half blacks) 😆

**Comment by dnil** [comment]
Or we can just install it ourselves rather have the tests croak on it..

**Comment by dnil** [comment]
But lets see - fingers crossed!

**Comment by dnil** [comment]
> We could always remove pre-commit. @elevu is not using it anyway, see the commit history if her PRs (half hers, half blacks) 😆

I've grown to like it - or at least liking not having that situation. I had a day or so with an outdated black-package. Painful! 😄

**Comment by dnil** [comment]
This passes dev checks. What do you say, should we spend more time on it or just disable pre-commit in the dev-req for now?

**Comment by northwestwitch** [comment]
> This passes dev checks. What do you say, should we spend more time on it or just disable pre-commit in the dev-req for now?

Let's remove it!

**Review by dnil — APPROVED** [review]

**Pull request merged**
