### PR TITLE
moving buttons

### PR DESCRIPTION
**Pull request by mayabrandi**
This PR swhitces place on the buttns "Next page" and "First page" as described in this [issue](https://github.com/Clinical-Genomics/scout/issues/1367) Although the cancer views had no buttons @northwestwitch. Did you want me to add that? Also I couldnt find any link to the cancer variant page from the case view. Do you want that? Or is it there, but I just didnt find it? 

(I did run "Format Document" on the htmls. Thats why the pr looks bigger than it is. Is it okey? Or you want me to redo that?)

**How to test**:
1. Thats a loooong and complicated story
1. If you manage to install, look at the different variant views. The Next page button should be last.

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "merge and deploy" approved by

### CODE REVIEW

**Comment by moonso** [comment]
Hi @mayabrandi , nice that you contribute! Could you point to the lines that you have actually changed(if not to many)?
There should be links to cancer variants from case page but they will only be visible if there are cancer variants added. You can try in a local instance, there is a cancer case in `scout/demo/` that you can use.

**Comment by northwestwitch** [comment]
@moonso are you reviewing this PR or should I do it?

**Comment by moonso** [comment]
Please go ahead @dnil

**Comment by northwestwitch** [comment]
I agree with @dnil, it's really hard to understand which code actually changed from master, because after re-formatting everything in these pages looks different. @mayabrandi  could you please create a PR containing only the changed code (buttons switch) and another (of you want) with the code re-formatting?

**Pull request closed without merging**
