### PR TITLE
Prepare version 4.35

### PR DESCRIPTION
**Pull request by northwestwitch**
New minor version 4.35

Features:

### Added
- [x] A new index for hgnc_symbol in the hgnc_gene collection
- [x] A Pedigree panel in STR page
- [x] Display Tier I and II variants in case view causatives card for cancer cases
### Fixed
- [x] Send partial file data to igv.js when visualizing sashimi plots with splice junction tracks
- [x] Research variants filtering by gene
### Changed
- [x] Switch off non-clinical gene warnings when filtering research variants
- [x] Don't display OMIM disease card in case view for cancer cases
- [x] Refactored Individuals and Causative card in case view for cancer cases
- [x] Add max-height to all dropdowns in Filters
- [x] Update and style STR case report

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by dnil** [comment]
What do you think @moedarrah and @northwestwitch: couldn't we get #2651 in there as well? 😊

**Comment by northwestwitch** [comment]
> hat do you think @moedarrah and @northwestwitch: couldn't we get #2651 in there as well?

I was thinking the same, let's include it!

**Comment by moedarrah** [comment]
I added it 👍

**Comment by northwestwitch** [comment]
It's installed on clinical-db stage now!

**Comment by northwestwitch** [comment]
Testing the new release. Shouldn't [this case](https://scout-stage.scilifelab.se/cust000/643594-300M) show a pedigree panel in the STR variantS page?

**Comment by dnil** [comment]
> Testing the new release. Shouldn't [this case](https://scout-stage.scilifelab.se/cust000/643594-300M) show a pedigree panel in the STR variantS page?

Notice that it also shows none on the case page..

**Comment by dnil** [comment]
> > Testing the new release. Shouldn't [this case](https://scout-stage.scilifelab.se/cust000/643594-300M) show a pedigree panel in the STR variantS page?
> 
> Notice that it also shows none on the case page..

Compare instead https://scout-stage.scilifelab.se/cust000/SWEDAC-2019-HG-05-Trio-NovaSeq/str/variants?variant_type=clinical

**Comment by northwestwitch** [comment]
> Compare instead https://scout-stage.scilifelab.se/cust000/SWEDAC-2019-HG-05-Trio-NovaSeq/str/variants?variant_type=clinical

Ah yes! I see now that my example is missing the pedigree on the case page

**Comment by northwestwitch** [comment]
The latest is on stage now, it contains also the dropdown height fix

**Comment by northwestwitch** [comment]
I think we are good with this one!

**Review by dnil — APPROVED** [review]
Yay!

**Comment by northwestwitch** [comment]
Deployed on prod now:

image

**Pull request merged**
