### PR TITLE
New minor release 4.23

### PR DESCRIPTION
**Pull request by northwestwitch**
Minor release 4.23, containing new features and bugfixes:

### Added
- Save custom IGV track settings
- Show a flash message with clear info about non-valid genes when gene panel creation fails
- CNV report link in cancer case side navigation
- Return to comment section after editing, deleting or submitting a comment
- Managed variants
- MT vs 14 chromosome mean coverage stats if Scout is connected to Chanjo
### Fixed
- missing `vcf_cancer_sv` and `vcf_cancer_sv_research` to manual.
- Split ClinVar multiple clnsig values (slash-separated) and strip them of underscore for annotations without accession number
- Timeout of `All SNVs and INDELs` page when no valid gene is provided in the search
- Round CADD (MIPv9)
- Missing default panel value
- Invisible other causatives lines when other causatives lack gene symbols
### Changed
- Do not freeze mkdocs-material to version 4.6.1
- Remove pre-commit dependency

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
I've installed it on stage, so we can test it!

**Comment by elevu** [comment]
awesome! Testing it now

**Review by elevu — APPROVED** [review]

**Comment by northwestwitch** [comment]
Tested here and there as well and looks fine. Shall we merge and deploy?

**Comment by dnil** [comment]
Right before the course? You really like living on the edge.. 😸

**Comment by northwestwitch** [comment]
> Right before the course? You really like living on the edge.

I think it's fine, and if it isn't we can always revert. What do you say?

**Comment by dnil** [comment]
We can revert most of the time. If you enjoy it, I'm in. The plan was early this week anyway, so why not. I'll drop a PR for a couple more workers on servers as well.

**Comment by northwestwitch** [comment]
And I am actually very calm , it's the others who are on edge for my decisions in general.. 😆

**Comment by dnil** [comment]
Yes, yes, naturally. 😉

**Comment by northwestwitch** [comment]
Someone has to be responsible in the group I guess..

**Pull request merged**
