### PR TITLE
Load STRs regardless of rank score threshold

### PR DESCRIPTION
**Pull request by dnil**
This PR marks a new Scout release. We apply semantic versioning. This is a major/minor/patch release for reasons.

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is the one based on 4.29 right? let's not update the branch with current master!

**Comment by dnil** [comment]
Actually, Im not so sure we should merge it at all? The branch does exist, so perhaps we should rather create a release from it? Sorry for being slow..

**Review by northwestwitch — CHANGES_REQUESTED** [review]
No we shouldn't merge, you are right, but we need to fix the scout version as well before creating the release from this

No worries I'm slower! :)

**Comment by dnil** [comment]
Tested on stage:
Screenshot 2021-02-19 at 08 32 07

**Comment by dnil** [comment]
The speed part is very context sensitive I'd say - typically we tend to end up with the same solution around the same second?

**Review by northwestwitch — APPROVED** [review]
Why not version 4.29.1?

**Comment by dnil** [comment]
Because you are on vacation next week!

**Comment by dnil** [comment]
(But the hotfix could theoretically be renamed 4.29.1 and we bump this to 4.29.2 when it's time..)

**Comment by dnil** [comment]
Why not actually - it is just a name anyway and not really a merge graph representation. It is better in line with semantic versioning which would otherwise rather ask for calling this 4.30-rc or something. I like. I’ll update it.

**Comment by northwestwitch** [comment]
The can be either closed or merged. Perhaps close it since it's based on an old master, but doesn't make much difference I guess. You choose @dnil

**Pull request closed without merging**
