### PR TITLE
Use woke to check for non-inclusive language in repo

### PR DESCRIPTION
**Pull request by northwestwitch**
Partial fix for #2598

### This PR adds a github action that is using  [woke](https://github.com/get-woke/woke) for checking for non-sensitive language:
- Action that checks the whole repo (action doesn't fail with errors but generates warnings)

**How to prepare for test**:
- Tests are executed via the github actions

### Expected outcome:
- [x] Get warnings if non-sensitive expressions are found in this repo

**Review:**
- [ ] code approved by
- [x] tests executed by github

### CODE REVIEW

**Comment by dnil** [comment]
👀 I expected it would find something at least? Aside from the horror of "Merge branch 'master' into woke_action".. 😸

**Comment by dnil** [comment]
Hm, it still missed mongo..

**Comment by northwestwitch** [comment]
> Hm, it still missed mongo..

Perhaps it's not a universally-blamed word. In Italy for instance it is slightly different 🤔

**Comment by northwestwitch** [comment]
Aha! Found the one that blocks everything!

**Comment by northwestwitch** [comment]
Better now:

image

**Comment by northwestwitch** [comment]
I think I'm satisfied enough with this for now. It checks but doesn't fail if it finds expressions it doesn't like.

**Review by dnil — APPROVED** [review]
The report on the action flagged green is not very easy to find, but if the "check annotations" comments on the code stays it should be very obvious anyway. Let's go with that!

**Comment by northwestwitch** [comment]
> The report on the action flagged green is not very easy to find, but if the "check annotations" comments on the code stays it should be very obvious anyway. Let's go with that!

I know, but the option was to fail (which we don't want). I've just merged the same action in the MatchMaker repo, but I've set that one to fail instead (now it doesn't find anything). We could do the same in Scout after fixing all the the issues and adding the words we would like to skip in a ahem "allowlist" in the scout settings.

**Pull request merged**
