### PR TITLE
Patch release 4.32.1

### PR DESCRIPTION
**Pull request by northwestwitch**
### Fixed
- iSort lint check only
- Institute cases page crashing when a case has track:Null
### Changed

**Review:**
- [x] code approved by DN
- [x] tests executed by DN. CR

### CODE REVIEW

**Review by dnil — APPROVED** [review]
Changelog looks a little off though; the hotfix track should be in the latest as well?

**Comment by dnil** [comment]
Like it is now! 😄

**Comment by northwestwitch** [comment]
Clinical-db before (cust000 cases page)

image


- [ ] Deployed on clinical-db stage: 🆗 

image


- [ ] Deployed on clinical-db prod:

image

**Comment by northwestwitch** [comment]
I've also pushed the new docs, in case nobody did it yesterday

image

**Comment by dnil** [comment]
Oh, I kind of thought they were autodeploy through GitHub Actions now! Lets check!

**Comment by dnil** [comment]
No, it seems that is not enabled.. Hm, it is very tempting..

**Pull request merged**
