### PR TITLE
Minor release 4.74

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] SNVs and Indels, MEI and str variants genes have links to Decipher
- [x] An `owner + case display name` index for cases database collection
- [x] Test and fixtures for RNA fusion case page
- [x] Load and display fusion variants from VCF files as the other variant types
- [x] Option to update case document with path to mei variants (clinical and research)
### Changed
- [x] Details on variant type and category for audit filters on case general report
- [x] Enable Gens CN profile button also in somatic case view
- [x]  Fix case of analysis type check for Gens analysis button - only show for WGS
### Fixed
- [x] loqusdb table no longer has empty row below each loqusid
- [x] MatchMaker submission details page crashing because of change in date format returned by PatientMatcher
- [x] Variant external links buttons style does not change color when visited
- [x] Hide compounds with compounds follow filter for region or function would fail for variants in multiple genes
- [x] Updated FontAwesome version due to fix missing icons

**Review:**
- [x] code approved by DN
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by northwestwitch** [comment]
This branch is deployed on stage now (cg-vm1)

**Comment by northwestwitch** [comment]
Update case with path to mei tested on hasta stage: 🆗 

image

**Review by dnil — APPROVED** [review]

**Comment by dnil** [comment]
Deployed to `cg-prod-services`:
```
[hiseq.clinical@cg-prod-services ~]$ systemctl --user stop scout@v4.73; systemctl --user start scout@v4.74
[hiseq.clinical@cg-prod-services ~]$ podman ps |grep scout
87d4e5f283bc  docker.io/clinicalgenomics/scout-reviewer-service:latest                        5 weeks ago     Up 5 weeks ago     0.0.0.0:7103->5050/tcp  scout_reviewer_service-latest
54d0f87ab9c5  docker.io/clinicalgenomics/scout-server:v4.74             /bin/sh -c gunico...  12 minutes ago  Up 12 minutes ago  0.0.0.0:7073->8000/tcp  scout-v4.74
```

**Comment by dnil** [comment]
Deployed to `hasta` prod:
```
1d [daniel.nilsson@hasta:~] [P_base] 3s $ bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.^C -e S_scout -t scout -b owner_display_name_index
(reverse-i-search)`update-too': bash /home/proj/production/servers/resources/hasta.scilifelab.se/^Cdate-tool-stage.sh -e S_scout -t scout -b owner_display_name_index
1d [daniel.nilsson@hasta:~] [P_base] 3s $ bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-prod.sh -e P_scout -t scout -b version_4.74
Collecting git+https://github.com/Clinical-Genomics/scout@version_4.74
  Running command git clone --quiet https://github.com/Clinical-Genomics/scout /home/daniel.nilsson/tmp/pip-req-build-nnjs3ymm
  Cloning https://github.com/Clinical-Genomics/scout (to revision version_4.74) to ./tmp/pip-req-build-nnjs3ymm
  Running command git checkout -b version_4.74 --track origin/version_4.74
  Resolved https://github.com/Clinical-Genomics/scout to commit 56865a972efbf62ed446481c8f5ff7092c0b0c33
  Switched to a new branch 'version_4.74'
  Preparing metadata (setup.py): started
  Branch version_4.74 set up to track remote branch version_4.74 from origin.
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: scout-browser
  Building wheel for scout-browser (setup.py): started
  Building wheel for scout-browser (setup.py): finished with status 'done'
  Created wheel for scout-browser: filename=scout_browser-4.74-py3-none-any.whl size=14527321 sha256=870e21d4268f450ec6af0722f281d69182b16fea8dc23d05b79f8df06ab5e36a
  Stored in directory: /home/daniel.nilsson/tmp/pip-ephem-wheel-cache-ht_rox8a/wheels/4f/57/e2/97683fae57049b4b90e6d8a38746a6f3d48b4dfaef88548b61
Successfully built scout-browser
Installing collected packages: scout-browser
  Attempting uninstall: scout-browser
    Found existing installation: scout-browser 4.73
    Uninstalling scout-browser-4.73:
      Successfully uninstalled scout-browser-4.73
Successfully installed scout-browser-4.74
Collecting git+https://github.com/Clinical-Genomics/scout@version_4.74
  Running command git clone --quiet https://github.com/Clinical-Genomics/scout /home/daniel.nilsson/tmp/pip-req-build-pc9sg7vu
  Cloning https://github.com/Clinical-Genomics/scout (to revision version_4.74) to ./tmp/pip-req-build-pc9sg7vu
  Running command git checkout -b version_4.74 --track origin/version_4.74
  Resolved https://github.com/Clinical-Genomics/scout to commit 56865a972efbf62ed446481c8f5ff7092c0b0c33
  Switched to a new branch 'version_4.74'
  Preparing metadata (setup.py): started
  Branch version_4.74 set up to track remote branch version_4.74 from origin.
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: werkzeug<2.3 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (2.2.2)
Requirement already satisfied: Flask>=2.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (2.2.2)
Requirement already satisfied: Flask-Bootstrap in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (3.3.7.1)
Requirement already satisfied: Flask-CORS in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (3.0.10)
Requirement already satisfied: path.py in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (12.5.0)
Requirement already satisfied: Flask-Markdown in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (0.3)
Requirement already satisfied: WTForms<3 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (2.3.3)
Requirement already satisfied: Flask-WTF in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (1.0.1)
Requirement already satisfied: Flask-Mail in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (0.9.1)
Requirement already satisfied: coloredlogs<=14.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (14.0)
Requirement already satisfied: query_phenomizer in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (1.2)
Requirement already satisfied: Flask-Babel>=3 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (3.0.1)
Requirement already satisfied: livereload in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (2.6.3)
Requirement already satisfied: tornado<6.3 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (6.2)
Requirement already satisfied: python-dateutil in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (2.8.2)
Requirement already satisfied: pymongo in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (3.12.3)
Requirement already satisfied: pathlib in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (1.0.1)
Requirement already satisfied: pdfkit in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (1.0.0)
Requirement already satisfied: phenopackets in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (2.0.2)
Requirement already satisfied: xlsxwriter in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (3.0.3)
Requirement already satisfied: click in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (8.1.3)
Requirement already satisfied: cryptography<3.4 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (3.3.2)
Requirement already satisfied: defusedxml in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (0.7.1)
Requirement already satisfied: svglib in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (1.4.1)
Requirement already satisfied: cairosvg in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (2.5.2)
Requirement already satisfied: importlib_resources in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (5.12.0)
Requirement already satisfied: authlib in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (1.1.0)
Requirement already satisfied: flask_login in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (0.6.2)
Requirement already satisfied: flask-ldapconn in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (0.10.1)
Requirement already satisfied: cyvcf2 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (0.30.18)
Requirement already satisfied: configobj in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (5.0.6)
Requirement already satisfied: ped_parser in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (1.6.6)
Requirement already satisfied: pydantic>=2 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (2.4.2)
Requirement already satisfied: PyYaml>=5.1 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (6.0)
Requirement already satisfied: intervaltree==3.0.2 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (3.0.2)
Requirement already satisfied: anytree in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (2.8.0)
Requirement already satisfied: tabulate in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from scout-browser==4.74) (0.9.0)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from intervaltree==3.0.2->scout-browser==4.74) (2.4.0)
Requirement already satisfied: humanfriendly>=7.1 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from coloredlogs<=14.0->scout-browser==4.74) (10.0)
Requirement already satisfied: six>=1.4.1 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from cryptography<3.4->scout-browser==4.74) (1.16.0)
Requirement already satisfied: cffi>=1.12 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from cryptography<3.4->scout-browser==4.74) (1.15.1)
Requirement already satisfied: Jinja2>=3.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from Flask>=2.0->scout-browser==4.74) (3.1.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from Flask>=2.0->scout-browser==4.74) (5.0.0)
Requirement already satisfied: itsdangerous>=2.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from Flask>=2.0->scout-browser==4.74) (2.1.2)
Requirement already satisfied: Babel<3.0.0,>=2.11.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from Flask-Babel>=3->scout-browser==4.74) (2.11.0)
Requirement already satisfied: pytz<2023.0,>=2022.7 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from Flask-Babel>=3->scout-browser==4.74) (2022.7.1)
Requirement already satisfied: annotated-types>=0.4.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from pydantic>=2->scout-browser==4.74) (0.5.0)
Requirement already satisfied: pydantic-core==2.10.1 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from pydantic>=2->scout-browser==4.74) (2.10.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from pydantic>=2->scout-browser==4.74) (4.7.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from werkzeug<2.3->scout-browser==4.74) (2.1.1)
Requirement already satisfied: tinycss2 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from cairosvg->scout-browser==4.74) (1.2.1)
Requirement already satisfied: pillow in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from cairosvg->scout-browser==4.74) (9.2.0)
Requirement already satisfied: cssselect2 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from cairosvg->scout-browser==4.74) (0.7.0)
Requirement already satisfied: cairocffi in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from cairosvg->scout-browser==4.74) (1.4.0)
Requirement already satisfied: numpy in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from cyvcf2->scout-browser==4.74) (1.21.6)
Requirement already satisfied: visitor in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from Flask-Bootstrap->scout-browser==4.74) (0.1.3)
Requirement already satisfied: dominate in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from Flask-Bootstrap->scout-browser==4.74) (2.7.0)
Requirement already satisfied: ldap3>=2.3 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from flask-ldapconn->scout-browser==4.74) (2.9.1)
Requirement already satisfied: blinker in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from Flask-Mail->scout-browser==4.74) (1.5)
Requirement already satisfied: markdown in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from Flask-Markdown->scout-browser==4.74) (3.4.1)
Requirement already satisfied: zipp>=3.1.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from importlib_resources->scout-browser==4.74) (3.10.0)
Requirement already satisfied: path in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from path.py->scout-browser==4.74) (16.5.0)
Requirement already satisfied: pytest in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from ped_parser->scout-browser==4.74) (7.2.0)
Requirement already satisfied: protobuf==3.20.1 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from phenopackets->scout-browser==4.74) (3.20.1)
Requirement already satisfied: requests in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from query_phenomizer->scout-browser==4.74) (2.28.1)
Requirement already satisfied: lxml in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from svglib->scout-browser==4.74) (4.9.1)
Requirement already satisfied: reportlab in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from svglib->scout-browser==4.74) (3.6.12)
Requirement already satisfied: pycparser in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from cffi>=1.12->cryptography<3.4->scout-browser==4.74) (2.21)
Requirement already satisfied: webencodings in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from cssselect2->cairosvg->scout-browser==4.74) (0.5.1)
Requirement already satisfied: pyasn1>=0.4.6 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from ldap3>=2.3->flask-ldapconn->scout-browser==4.74) (0.4.8)
Requirement already satisfied: packaging in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from pytest->ped_parser->scout-browser==4.74) (21.3)
Requirement already satisfied: pluggy<2.0,>=0.12 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from pytest->ped_parser->scout-browser==4.74) (1.0.0)
Requirement already satisfied: iniconfig in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from pytest->ped_parser->scout-browser==4.74) (1.1.1)
Requirement already satisfied: tomli>=1.0.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from pytest->ped_parser->scout-browser==4.74) (2.0.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from pytest->ped_parser->scout-browser==4.74) (1.0.0)
Requirement already satisfied: attrs>=19.2.0 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from pytest->ped_parser->scout-browser==4.74) (22.1.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from requests->query_phenomizer->scout-browser==4.74) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from requests->query_phenomizer->scout-browser==4.74) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from requests->query_phenomizer->scout-browser==4.74) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from requests->query_phenomizer->scout-browser==4.74) (1.26.12)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/proj/production/bin/miniconda3/envs/P_scout/lib/python3.7/site-packages (from packaging->pytest->ped_parser->scout-browser==4.74) (3.0.9)
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/daniel.nilsson
done.
Log deploy... done.
scout, version 4.74
1d [daniel.nilsson@hasta:~] [P_base] 3s $ scout --version
scout, version 4.74
```

**Pull request merged**
