### PR TITLE
Verification mail comments

### PR DESCRIPTION
**Pull request by bjhall**
This PR adds a comment box to the verification modal form and adds the comment to the email. This allows the Scout user to include a message to the Sanger sequencing people.

### CODE REVIEW

**Comment by northwestwitch** [comment]
How nice that you are contributing to Scout! I'll try to review as much as possible on these days! :)

**Comment by northwestwitch** [comment]
This is a bit tricky because I see that the branch you are making the pull request from is not really updated with out master (like 87 commitments behind and 2 ahead). 
This shouldn't be a problem for this PR because it's simple stuff, but maybe for some other more advanced functionalities you might want to update your repo and working branch. Unless you branched out for your reasons, which I totally respect.
First thing I notice is that this PR doesn't pass the tests. It should be quite easy to fix (by adding the missing comment parameter into the right test). Could you do that?

**Comment by northwestwitch** [comment]
No wait, your master branch is actually like ours. So it's just this branch!

**Comment by bjhall** [comment]
I branched and did these changes a while ago, so your master has diverged quite a bit since then. Is it the recommended workflow that I do a rebase with your master before I submit pull requests? I'm not really used to working in a fork of such a fast-paced projects as Scout :)

Should I close this PR and make a new one with a rebased branch (and also include the fixed test)?

**Comment by northwestwitch** [comment]
I know! This repo keeps changing and drives us nuts at times. I think that yes, before pushing your branch and submitting the PR it's best to pull from an updated branch (our master, or your master if it's up to date)
You could do that now or you could push the above "Update branch" button, cross your fingers and hope for the best. That's what I do most of the time! :)

**Comment by northwestwitch** [comment]
If it works you could pull from the updated branch, fix the test, and push again in the PR

**Comment by bjhall** [comment]
I did as you suggested. Hopefully it worked as expected.

**Comment by northwestwitch** [comment]
Nice, feel free to merge! :)

**Comment by bjhall** [comment]
I don't think I have the permissions to merge?

**Comment by northwestwitch** [comment]
> I don't think I have the permissions to merge?

Ok! Probably just users from with our github group have the permissions. I'll do it! 
Thank you, and keep the good stuff coming!

**Pull request merged**
