### PR TITLE
Update hpo terms

### PR DESCRIPTION
**Pull request by moonso**

### CODE REVIEW

**Comment by northwestwitch** [comment]
Wow that was a big update, good job @moonso !

**Comment by northwestwitch** [comment]
So this solves the issue #702 (Adding HPO phenotypes not associated to any gene)?

**Comment by moonso** [comment]
Yes

**Comment by northwestwitch** [comment]
Nice, so we can close that issue e insert the add "HP:0012335" to the scout checklist.

**Comment by northwestwitch** [comment]
Ok, it's closed already, but I definitely add it to the checklist, right?

**Comment by moonso** [comment]
Yes sounds good. I've added `scout update hpo` to the checklist

**Comment by northwestwitch** [comment]
Hello again. I was doing some testing with the new master, that contains also this PR, and after the "scout update hpo" command it looks like it is still not possible to add HPO terms not associated to genes (like HPO:0012335). The difference from before is that now the program doesn't crash anymore, but the term is not added to the "Added phenotypes" panel. Am I missing something?

**Comment by moonso** [comment]
skarmavbild 2018-05-28 kl 18 39 29
skarmavbild 2018-05-28 kl 18 40 01
skarmavbild 2018-05-28 kl 18 40 16

**Comment by northwestwitch** [comment]
I believed you even without pics! :)

**Comment by moonso** [comment]
👍 if you want to keep use that you can run `scout --demo update hpo` and then `scout --demo serve`

**Pull request merged**
