### PR TITLE
display MME contact emails when available

### LINKED ISSUE #1517: Show contact emails in matchmaker matches
Some MME nodes provide email field in contact object. We are not currently displaying these emails in the match overview. Example:

image

They have asked us to show them to our users.
Email field is correctly saved in match objects (patientMatcher database) but it's not yet displayed by Scout. It's an easy fix, probably in the mme matches template, because the info should already be available in the match results dictionaries

### PR DESCRIPTION
**Pull request by northwestwitch**
fix #1517

**How to test**:
1. From master branch, check matchmaker external matches on stage for this case: https://scout-stage.scilifelab.se/cust101/A1383/mme_matches
1. Open one random external match and make sure that contact email is not displayed (contact looks like in fix #1375 
1. Install this branch on stage check the same external matches

**Expected outcome**:
1. Email fields email should be now present and MME pages in general are more clear

**Review:**
- [x] code approved by dNil
- [x] tests executed by dNil

### CODE REVIEW

**Comment by northwestwitch** [comment]
It's already on stage. It works but the table looks a bit busy. Can be improved!

**Comment by northwestwitch** [comment]
Ready for review, whoever has time!

**Comment by dnil** [comment]
Hm, CHANGELOG is not quite in shape after last release (and subsequent commits). Oh well, lets just be attentive of that. Release history is fine.

**Comment by dnil** [comment]
Nice! I can confirm email display is working, and generally looks are improved.
The only other thing I noticed at a glance is the commas on the empty fields here:
Screenshot 2019-11-18 at 17 49 45

I'll leave it to you if you want to fix that now - the issue at hand is closed as far as I can tell!

**Comment by northwestwitch** [comment]
> Nice! I can confirm email display is working, and generally looks are improved.
> The only other thing I noticed at a glance is the commas on the empty fields here:
> Screenshot 2019-11-18 at 17 49 45
> 
> I'll leave it to you if you want to fix that now - the issue at hand is closed as far as I can tell!

Yes, this happens when these fields are empty. I'll try to fix it in a better way in this PR. I'd like to show the options even when data is missing, because it's informative to know if the patient info was not provided, but we could display a '-' instead. Thanks for the review!

**Comment by northwestwitch** [comment]
Fixed by adding '-' for missing values. Looking this on stage:
image

**Comment by northwestwitch** [comment]
I'm satisfied with this PR now, merging!

**Pull request merged**
