### PR TITLE
fix #1116

### LINKED ISSUE #1116: Report - missing phenotype and sex
Phenotype and gender are missing on the generated general report. "Phenotype overview" window.

### PR DESCRIPTION
**Pull request by northwestwitch**
After the fix it should look like this:
image

With A and NA labels which stand for AFFECTED and NOT AFFECTED. Sex is also displayed now.

### CODE REVIEW

**Comment by northwestwitch** [comment]
I don't know if there was any specific reason why pytest was frozen to version 3.3, but it wasn't working any more. By updating it to 3.6 the tests pass!

**Comment by dnil** [comment]
Nice, thank you! NA somehow gives us doubts about if it was typed or is NotAvailable? Not sure how to best convey that it is "unaffected" - make it "NAD" ("NothingAbnormal Detected"), leave those blank, use "U" and explain somewhere?

**Comment by northwestwitch** [comment]
Oh yes, you're right! What about changing the header into 'affected' and on the individual level I write yes or no?

**Comment by dnil** [comment]
Sounds good!

**Comment by northwestwitch** [comment]
It looks like this now:
image

**Comment by dnil** [comment]
Code looks good to me, but I'm no expert on the ped-file data and what to expect in the db there.

**Comment by northwestwitch** [comment]
But your comment was really helpful, thanks! :)

**Pull request merged**
