### PR TITLE
Rank pie chart

### PR DESCRIPTION
**Pull request by mayabrandi**
This PR adds a rank score pie chart to the variant view

**How to test**:
1. install on stage and go to a variant. 

**Expected outcome**:
There should be a pie chart under the summary, showing some details about the rank score

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "merge and deploy" approved by

### CODE REVIEW

**Comment by mayabrandi** [comment]
I directly noticed that Clinical STRs are using the same html, resulting in an empty chart there. Ill look into how to handle that @moonso

**Comment by moonso** [comment]
Nice Maya! One thing that came to my mind: what will happen if there is no rankscore result on the variant?

**Comment by moonso** [comment]
Haha ok you are already on it.

**Comment by mayabrandi** [comment]
That is not taken care of. Ill add a exeption for that

Skickat från min iPhone

**Comment by mayabrandi** [comment]
Ready for review @moonso

**Comment by mayabrandi** [comment]
@northwestwitch See what you think now!

**Comment by northwestwitch** [comment]
Nice! I'll check as soon as I'm at the office!

**Comment by northwestwitch** [comment]
Testing the PR, unfortunately I don't see the chart under the variant summary. There are some javascript errors:
image

**Comment by mayabrandi** [comment]
Sry. I missed to push the views.py

**Comment by mayabrandi** [comment]
@dnil @moonso @northwestwitch I pushed a commit with both pie and bar plot. Can you look and select which you prefer. (Ignore the weird borders in the plots. They should not be there )

**Comment by moonso** [comment]
@mayabrandi Could you post screenshots as comments here? And maybe add a comment what you think

**Comment by dnil** [comment]
I'm guessing this is a prototype, but just to be clear we probably need a full OSS solution? This appears semi-commercial, and rather expensive at that?
Screenshot 2019-12-03 at 13 40 45

**Comment by mayabrandi** [comment]
I don’t really have an opinion.

**Comment by mayabrandi** [comment]
Valtteri already approved on using Highcharts in Vogue. I tried some different packages and talked to Phill about it and he agreed on that Highcharts is a good choice. He is also using it in multiQC and megaQC if I remember correctly. Should be okej.

**Comment by hassanfa** [comment]
Vega/vega-lit/Altair-viz offers a similar solution (and similar grammar), and it is free for commercial usage: https://github.com/vega/vega . It is not pretty to work with though.

**Comment by mayabrandi** [comment]
Skärmavbild 2019-12-03 kl  13 44 35

**Comment by dnil** [comment]
Neato! I much prefer the bar version. It is as good as a table. :wink: I'm also curious to see it with ranges as well - there it might be even better!

How does one go about getting a highcharts version that can be used locally, and not complicate things for other sites? I can't imagine multiQC etc shipping with a little ad from that company in it?

**Comment by vwirta** [comment]
When we progress in use of highcharts we can look into the licensing. Non-commercial license is ok for universities, but we can still look into if a commercial developer’s license gives added value.

**Comment by northwestwitch** [comment]
Vega is good. Otherwise I used Chart.js to create the charts present in the dashboard. @mayabrandi I don't think we should buy any library here. You are using a demo?

**Comment by dnil** [comment]
@vwirta From their ad, I don't quite see how we could avoid a license, but perhaps there is more to it behind the scenes? 
Our research is formally governmental, and the clinical side is commercial, arguably non-profit, but that is usually a complicated area.

**Comment by vwirta** [comment]
It is complicated… universities were explicitly mentioned as ok for non-commercial somewhere in the faq
But the clinic side is of course different…  let’s see where we land regarding choice of tools and then discuss strategy for licensing

**Comment by dnil** [comment]
Ok. This is so far the only place its used. It would seem easier just to use another library or draw ourselves?

**Comment by mayabrandi** [comment]
@dnil Absolutely. Not a problem. ill switch to something else

**Comment by dnil** [comment]
Interesting! You are absolutely right Phil is using this, but you have to drill down all the way to the actual js files to find the highcharts license in the MultiQC package. Upfront it sells with https://github.com/ewels/MultiQC/blob/master/LICENSE which to this lay person appears legally incompatible with https://github.com/highcharts/highcharts and its www.highcharts.com/license?

**Comment by dnil** [comment]
> @dnil Absolutely. Not a problem. ill switch to something else

Thanks @mayabrandi - sorry to be a bother.. :sweat:

**Comment by dnil** [comment]
For the record we had a chat with Phil, who recommended not using HighCharts for new projects, but who also was not in any immediate rush to remove it from MultiQC, and when in the distant future this happens plans to move to plotly (MIT license).

**Comment by mayabrandi** [comment]
Thanks for digging into this Daniel.

**Comment by northwestwitch** [comment]
Does anybody mind if I take over this one?

**Comment by dnil** [comment]
Check with @mayabrandi - but note that it is effectively blocked by #791, even if a different drawing package is used?

**Comment by northwestwitch** [comment]
> Check with @mayabrandi - but note that it is effectively blocked by #791, even if a different drawing package is used?

Ok, let's wait then!

**Comment by northwestwitch** [comment]
This PR is almost a year old and blocked by #791. I suggest we close and reopen when it can be addressed properly. Anyone disagrees?

**Comment by mayabrandi** [comment]
Sure!

**Pull request closed without merging**
