### PR TITLE
Fix #2069 - show VAF on pinned and causatives

### LINKED ISSUE #2069: Show VAF on pinned cancer variants
Users want to see VAF of pinned variants already on the case page. 

Connected to https://github.com/Clinical-Genomics/scout/issues/1245 
and #1682 - perhaps fix in one go?

### PR DESCRIPTION
**Pull request by dnil**
This PR extends a functionality: show VAF on pinned and causative cancer variants on the case page.

Fix #2069!

**How to test**:
1. pin / mark variants causative, ideally both tumor-only, tumor-normal and RD and make sure all looks ok and shows intended values

Screenshot 2020-09-07 at 17 51 46

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by CR

### CODE REVIEW

**Comment by dnil** [comment]
Ping @heronikdin: did you want normal alt AF as well if it is available, or is that either so often not determined, or so often negligibly larger than zero for a presumed causative that we should just leave it out on the case page and only show for the variants and variant page?

**Comment by northwestwitch** [comment]
And then this one, and we release a new version today, ok?

**Comment by heronikdin** [comment]
> And then this one, and we release a new version today, ok?

Fantastic! Thank you!

**Comment by dnil** [comment]
@northwestwitch Yeah, if you find nothing seriously wrong with this one in review it could be included, but we don't *have* to included in this release. Its a feature not a bug, although @heronikdin seemed happy. 😸

**Review by northwestwitch — APPROVED** [review]
Works perfectly! 👍 

image

**Comment by heronikdin** [comment]
> Ping @heronikdin: did you want normal alt AF as well if it is available, or is that either so often not determined, or so often negligibly larger than zero for a presumed causative that we should just leave it out on the case page and only show for the variants and variant page?

It doesnt hurt if the normal AF is show. Could we try it like this and then I can come back with an issue regarding this? :)

**Comment by northwestwitch** [comment]
Can we merge this one?

**Pull request merged**
