### PR TITLE
Update docs url

### PR DESCRIPTION
**Pull request by moonso**
This PR updates the docs URL in README

**Expected outcome**:
Link should work

### CODE REVIEW

**Review by northwestwitch — CHANGES_REQUESTED** [review]
Nice!

I'm seeing in the code that there are a few other places with the old link, it would be nice to fix those as well

```
(py38) chiararasi@n129-p71:~/Documents/work/GITs/scout$ grep -r clinicalgenomics.se/scout .
./scout_browser.egg-info/PKG-INFO:        This README only gives a brief overview of Scout, for a more complete reference, please check out our docs: [www.clinicalgenomics.se/scout](http://www.clinicalgenomics.se/scout/).
./mkdocs.yml:site_url: http://www.clinicalgenomics.se/scout/
./Dockerfile:LABEL about.documentation="http://www.clinicalgenomics.se/scout"
./scout/server/blueprints/panels/templates/panels/panel_pdf_simple.html:  <a href="http://www.clinicalgenomics.se/scout/" target="_blank">http://www.clinicalgenomics.se/scout/</a>
./scout/server/blueprints/panels/templates/panels/panels.html:            <p class="help-block">How do I format my <a href="https://www.clinicalgenomics.se/scout/user-guide/panels/#uploading-a-new-gene-panel-version">gene panel file</a>?</p>
./scout/server/blueprints/panels/templates/panels/panels.html:            <p class="help-block">How do I format my <a href="https://www.clinicalgenomics.se/scout/user-guide/panels/#uploading-a-new-gene-panel-version">gene panel file</a>?</p>
./scout/server/blueprints/cases/templates/cases/case_report.html:   <a href="http://www.clinicalgenomics.se/scout/" target="_blank">http://www.clinicalgenomics.se/scout/</a>
./scout/server/blueprints/managed_variants/templates/managed_variants/managed_variants.html:        <p class="help-block">How do I format my <a href="https://www.clinicalgenomics.se/scout/user-guide/panels/#uploading-a-new-gene-panel-version">managed variants file</a>?</p>
./scout/server/templates/layout_bs4.html:                <a class="dropdown-item" href="http://www.clinicalgenomics.se/scout/" target='_blank'>User guide</a>
./docs/README.md:	<a href="http://www.clinicalgenomics.se/scout">
./README.md:This README only gives a brief overview of Scout, for a more complete reference, please check out our docs: [www.clinicalgenomics.se/scout](http://www.clinicalgenomics.se/scout/).
```

and don't forget the changelog!

**Comment by moonso** [comment]
Fixed @northwestwitch !

**Review by northwestwitch — APPROVED** [review]
Perfect! 👍

**Comment by northwestwitch** [comment]
I've just pushed the new documentation so the links work now!

**Pull request merged**
