### PR TITLE
Swap ref/alt to alt/ref reads in cancer variants page

### PR DESCRIPTION
**Pull request by northwestwitch**
So it mirrors the actual alt allele frequency

**How to test**:
1. Install it and check that on variants page it is reported the right info

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by
- [x] tests executed by

### CODE REVIEW

**Comment by dnil** [comment]
Ok, thanks that's what I asked for. Seems @hassanfas and @mikaell  issue with refs is also in my demo case:
Screenshot 2020-02-20 at 11 10 01

I'm leaning towards this being ok as things seemed ok on stage? What do you think?

**Comment by northwestwitch** [comment]
> Ok, thanks that's what I asked for. Seems the issue of @hassanfa and @mikaell with refs is also in my demo case:
> Screenshot 2020-02-20 at 11 10 01
> 
> I'm leaning towards this being ok as things seemed ok on stage? What do you think?

It's OK! :)

**Comment by northwestwitch** [comment]
I don't know about this -1 in the demo case but It's looking good on stage:

image

**Comment by dnil** [comment]
Ok good. What about column width / nbsp for the cell? It looks a bit chaotic on that picture?

**Comment by northwestwitch** [comment]
> Ok good. What about column width / nbsp for the cell? It looks a bit chaotic on that picture?

It's a lot of info in all the other cols, so I'm not surprised. What about leaving it like this for now. We can fix it later, there's a number of other changes that is going to happen in that page anyway

**Comment by northwestwitch** [comment]
Shall I merge?

**Pull request merged**
