### PR TITLE
Remove overflow auto to avoid cut tables from several pages

### PR DESCRIPTION
**Pull request by elevu**
This PR changes the styling in some pages

**How to test**:
1. run this branch in staging (you will need a lot of data and long tables) and check out the users, causatives and institute tables

**Expected outcome**:
The tables should look fine

**Review:**
- [x] code approved by
- [x] tests executed by

### CODE REVIEW

**Comment by mikaell** [comment]
Code seems alright.

Playing around on stage the tables look alright. Next time you could add a screen shot that highlights the changes.

**Review by mikaell — APPROVED** [review]
OK!

**Comment by elevu** [comment]
> Next time you could add a screen shot showing before and after.

will do!

**Comment by mikaell** [comment]
CHANGELOG! You must edit CHANGELOG (I always forget it too).

**Comment by elevu** [comment]
> CHANGELOG! You must edit CHANGELOG (I always forget it too).

I edited it before merging
Screen Shot 2020-08-24 at 12 55 09

**Pull request merged**
