### PR TITLE
Prepare minor version 4.82

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Tooltip for combined score in tables for compounds and overlapping vars
- [x] Option to filter variants by excluding genes listed in selected gene panels, files or provided as list
- [x] STR variant information card with database links, replacing empty frequency panel
- [x] Display paging and number of HPO terms available in the database on Phenotypes page
- [x] On case page, typeahead hints when searching for a disease using substrings containing source ("OMIM:", "ORPHA:")
- [x] Button to monitor the status of submissions on ClinVar Submissions page
- [x] Option to filter cancer variants by number of observations in somatic and germline archived database
- [x] Documentation for integrating chanjo2
- [x] More up-to-date VEP CSQ dbNSFP frequency keys
- [x] Parse PacBio TRGT (Tandem repeat genotyping tool) Short Tandem Repeat VCFs
### Changed
- [x] In the case_report #panel-tables has a fixed width
- [x] Updated IGV.js to 2.15.11
- [x] Fusion variants in case report now contain same info as on fusion variantS page
- [x] Block submission of somatic variants to ClinVar, until we harmonise with their changed API
- [x] Additional control on the format of conditions provided in ClinVar form
- [x] Errors while loading managed variants from file are now displayed on the Managed Variants page
- [x] Chanjo2 coverage button visible only when query will contain a list of HGNC gene IDs
- [x] Prepare to unfreeze Werkzeug, but don't actually activate until chanjo can deal with the change
### Fixed
- [x] Submit requests to Chanjo2 using HTML forms instead of JSON data
- [x] Research somatic variants` link name on caseS page
- [x] Broken `Install the HTML 2 PDF renderer` step in a GitHub action
- [x] Fix ClinVar form parsing to not include ":" in conditionType.id when condition conditionType.db is Orphanet
- [x] Fix condition dropdown and pre-selection on ClinVar form for cases with associated ORPHA diagnoses
- [x] Improved visibility of ClinVar form in dark mode
- [x] End coordinates for indels in ClinVar form
- [x] Diagnoses API search crashing with empty search string
- [x] Variant's overlapping panels should show overlapping of variant genes against the latest version of the panel
- [x] Installation of git in second build stage of Dockerfile, allowing correct installation of libraries

**Review:**
- [ ] code approved by
- [x] tests executed by DN. CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
I've deployed this branch on stage now, for testing!

**Comment by northwestwitch** [comment]
@dnil did you test the "Button to monitor the status of submissions on ClinVar Submissions page" with a real submission?

**Comment by dnil** [comment]
Updated `winningchicken` again with this branch:
Screenshot 2024-05-07 at 13 16 37

**Comment by northwestwitch** [comment]
Mmm I've tried to install the latest version of this branch on hasta and got this error:

ERROR: Ignored the following versions that require a different python version: 2.3.0 Requires-Python >=3.8; 2.3.1 Requires-Python >=3.8; 2.3.2 Requires-Python >=3.8; 2.3.3 Requires-Python >=3.8; 2.3.4 Requires-Python >=3.8; 2.3.5 Requires-Python >=3.8; 2.3.6 Requires-Python >=3.8; 2.3.7 Requires-Python >=3.8; 2.3.8 Requires-Python >=3.8; 3.0.0 Requires-Python >=3.8; 3.0.1 Requires-Python >=3.8; 3.0.2 Requires-Python >=3.8; 3.0.3 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement werkzeug>=3.0.3 (from scout-browser) (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.4.1, 0.5, 0.5.1, 0.6, 0.6.1, 0.6.2, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.10, 0.10.1, 0.10.2, 0.10.4, 0.11, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.11.7, 0.11.8, 0.11.9, 0.11.10, 0.11.11, 0.11.12, 0.11.13, 0.11.14, 0.11.15, 0.12, 0.12.1, 0.12.2, 0.13, 0.14, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.15.5, 0.15.6, 0.16.0, 0.16.1, 1.0.0rc1, 1.0.0, 1.0.1, 2.0.0rc1, 2.0.0rc2, 2.0.0rc3, 2.0.0rc4, 2.0.0rc5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.2.0a1, 2.2.0, 2.2.1, 2.2.2, 2.2.3)
ERROR: No matching distribution found for werkzeug>=3.0.3
ERROR conda.cli.main_run:execute(49): `conda run pip install -U git+https://github.com/Clinical-Genomics/scout@version_4.82` failed. (See above for error)

**Comment by northwestwitch** [comment]
> Mmm I've tried to install the latest version of this branch on hasta and got this error:
> 
> ERROR: Ignored the following versions that require a different python version: 2.3.0 Requires-Python >=3.8; 2.3.1 Requires-Python >=3.8; 2.3.2 Requires-Python >=3.8; 2.3.3 Requires-Python >=3.8; 2.3.4 Requires-Python >=3.8; 2.3.5 Requires-Python >=3.8; 2.3.6 Requires-Python >=3.8; 2.3.7 Requires-Python >=3.8; 2.3.8 Requires-Python >=3.8; 3.0.0 Requires-Python >=3.8; 3.0.1 Requires-Python >=3.8; 3.0.2 Requires-Python >=3.8; 3.0.3 Requires-Python >=3.8 ERROR: Could not find a version that satisfies the requirement werkzeug>=3.0.3 (from scout-browser) (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.4.1, 0.5, 0.5.1, 0.6, 0.6.1, 0.6.2, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.10, 0.10.1, 0.10.2, 0.10.4, 0.11, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.11.7, 0.11.8, 0.11.9, 0.11.10, 0.11.11, 0.11.12, 0.11.13, 0.11.14, 0.11.15, 0.12, 0.12.1, 0.12.2, 0.13, 0.14, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.15.5, 0.15.6, 0.16.0, 0.16.1, 1.0.0rc1, 1.0.0, 1.0.1, 2.0.0rc1, 2.0.0rc2, 2.0.0rc3, 2.0.0rc4, 2.0.0rc5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.2.0a1, 2.2.0, 2.2.1, 2.2.2, 2.2.3) ERROR: No matching distribution found for werkzeug>=3.0.3 ERROR conda.cli.main_run:execute(49): `conda run pip install -U git+https://github.com/Clinical-Genomics/scout@version_4.82` failed. (See above for error)

Whoops

image

**Comment by dnil** [comment]
I thought we ditched 3.7 a while ago? 😅

**Comment by northwestwitch** [comment]
Ok, Hasta stage fixed like this:

## Updated the python on S_scout:

```
[chiara.rasi@hasta:~] [base] $ us
[chiara.rasi@hasta:~] [S_base] $ conda activate S_scout
[chiara.rasi@hasta:~] [S_scout] $ conda install python=3.11
```

## Installed scout again 🆗 
```
[chiara.rasi@hasta:~] [S_scout] $ down
[chiara.rasi@hasta:~] [base] $ us
[chiara.rasi@hasta:~] [S_base] $ bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b version_4.82
```

```
[chiara.rasi@hasta:~] [S_base] $ scout --version
scout, version 4.82
[chiara.rasi@hasta:~] [S_base] $
```

**Comment by dnil** [comment]
> We need to fix it before deploying this release

Yes, right, chanjo and that SQL library wasn't it.

**Comment by northwestwitch** [comment]
> > We need to fix it before deploying this release
> 
> Yes, right, chanjo and that SQL library wasn't it.

Yes, so we can't update scout web to 3.11, but the update worked fine on hasta

**Comment by dnil** [comment]
Tested loading TRGT STRanger VCFs with `winning chicken`. 
Screenshot 2024-05-14 at 11 12 14

**Comment by northwestwitch** [comment]
> Tested loading TRGT STRanger VCFs with `winningchicken`.

Nice!

**Pull request merged**
