### PR TITLE
Prepare version 4.49

### PR DESCRIPTION
**Pull request by northwestwitch**
### Fixed
- [x] Pydantic model types for genome_build, madeline_info, peddy_ped_check and peddy_sex_check, rank_model_version and sv_rank_model_version
- [x] Replace `MatchMaker` with `Matchmaker` in all places visible by a user
- [x] Save diagnosis labels along with OMIM terms in Matchmaker Exchange submission objects
- [x] `libegl-mesa0_21.0.3-0ubuntu0.3~20.04.5_amd64.deb` lib not found by GitHub actions Docker build
- [x] Remove unused `chromograph_image_files` and `chromograph_prefixes` keys saved when creating or updating an RD case
- [x] Search managed variants by description and with ignore case
### Changed
- [x] Introduced page margins on exported PDF reports
- [x] Smaller gene fonts in downloaded HPO genes PDF reports
- [x] Reintroduced gene coverage data in the PDF-exported general report of rare-disease cases
- [x] Check for existence of case report files before creating sidebar links
- [x] Better description of HPO and OMIM terms for patients submitted to Matchmaker Exchange
- [x] Remove null non-mandatory key/values when updating a case
- [x] Freeze WTForms<3 due to several form input rendering changes

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
</details>

**Review:**
- [x] code approved by DN
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by northwestwitch** [comment]
Let's wait and fix #3162 before releasing, right? What else?

**Comment by northwestwitch** [comment]
Tested `Pydantic model types for genome_build, madeline_info, peddy_ped_check and peddy_sex_check, rank_model_version and sv_rank_model_version` by removing a demo case `acewombat` (cust002) and loading it as a new case: 🆗 

image

**Comment by northwestwitch** [comment]
Tested `Remove null non-mandatory key/values when updating a case` by re-uploading [safeguinea](https://scout-stage.scilifelab.se/cust000/F0006358-mip7): 🆗 

image

**Comment by dnil** [comment]
Chromograph images also look ok for `acewombat` and `safeguinea`. Also a non-reuploaded case `inferret`.

**Review by dnil — APPROVED** [review]

**Pull request merged**
