### PR TITLE
Add link to genes coverage overview on case page, HPO panel

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug.
- Refactor chanjo2 endpoint to accept the type of report to be created (report/overview)
- Partial fix for #4000 --> Add a link to the genes overview report on the case HPO panel

image

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. Deploy on a test server and test with a case with associated .d4 files (on our server, testable with [this case](https://scout-stage.scilifelab.se/cust000/F0006358-mip7))

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Hi @Jakob37, I have this PR with another piece of chanjo2 integration. You might test it if you want. In the meanwhile I've fixed (I think) the problem of the intermittent SQL connection [on the other repo](https://github.com/Clinical-Genomics/chanjo2/pull/257). 
If you are testing this PR with a scout case that has WGS data you might miss data when you try to open the links created in the overview report. I'm also fixing this in chanjo2!

**Comment by Jakob37** [comment]
> Hi @Jakob37, I have this PR with another piece of chanjo2 integration. You might test it if you want. In the meanwhile I've fixed (I think) the problem of the intermittent SQL connection [on the other repo](https://github.com/Clinical-Genomics/chanjo2/pull/257). If you are testing this PR with a scout case that has WGS data you might miss data when you try to open the links created in the overview report. I'm also fixing this in chanjo2!

Great! I'll give it a test run today

**Comment by northwestwitch** [comment]
> Great! I'll give it a test run today

Nice! In the meanwhile I've published a Chanjo2 release with some fixes: https://github.com/Clinical-Genomics/chanjo2/releases/tag/v1.5.1

**Comment by Jakob37** [comment]
Yes, I got the same error on a second attempt

**Comment by northwestwitch** [comment]
> New error during loading of my wgs test case:

I'll move the error above to a new issue, since it's not related with this pull request!

**Comment by Jakob37** [comment]
Testing on my smaller onco-sample, I am getting some results:

3_brca

This looks good to my untrained eyes!

**Comment by Jakob37** [comment]
Clicking on the other links (15x and so on) does not seem to give a response though (same in the demo case)

**Comment by northwestwitch** [comment]
> Clicking on the other links (15x and so on) does not seem to give a response though (same in the demo case)
> 
> (But guessing that is on the Chanjo2 side)
> 
> Here are the web console errors:
> 
> 4_chanjo2_issue

Mmm weird, I suspect it might be some settings on your server. Check how the demo coverage overview looks on our stage server: https://chanjo2-stage.scilifelab.se/overview/demo

**Comment by Jakob37** [comment]
> > Clicking on the other links (15x and so on) does not seem to give a response though (same in the demo case)
> > (But guessing that is on the Chanjo2 side)
> 
> Mmm weird, I suspect it might be some settings on your server. Check how the demo coverage overview looks on our stage server: https://chanjo2-stage.scilifelab.se/overview/demo

OK I see! I'll investigate then. But that is different from this PR. Looks good here!

**Review by Jakob37 — APPROVED** [review]
Seems to work fine in my testing!

**Comment by Jakob37** [comment]
> > OK I see! I'll investigate then. But that is different from this PR. Looks good here!
> 
> Might even be settings in the browser, what are you using, chrome? You need to allow CORS

I was also suspecting something with CORS. I am using Firefox primarily. Chrome does not work for me either. Getting "Failed to load fetch" errors 🤔 

Didn't know you needed to enable it browser wise, seems to generally work fine on other sites. I'll test and see if it helps.

**Comment by northwestwitch** [comment]
> I was also suspecting something with CORS. I am using Firefox primarily. Chrome does not work for me either. Getting "Failed to load fetch" errors 🤔
> 
> Didn't know you needed to enable it browser wise, seems to generally work fine on other sites. I'll test and see if it helps.

I didn't have to do anything on safari. Perhaps I did something on chrome, related to an issue in another repo, I think.

**Comment by northwestwitch** [comment]
Might also be NGINX settings: https://enable-cors.org/server_nginx.html

**Comment by northwestwitch** [comment]
Here's my NGINX config file:

```
# generated 2024-02-16, Mozilla Guideline v5.7, nginx 1.25, OpenSSL 3.2.1, modern configuration
# https://ssl-config.mozilla.org/#server=nginx&version=1.25&config=modern&openssl=3.2.1&guideline=5.7
server {
    listen 80;
    listen [::]:80;
    server_name chanjo2-stage.scilifelab.se;

    location / {
        return 301 https://chanjo2-stage.scilifelab.se$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name chanjo2-stage.scilifelab.se;

    ssl_certificate /etc/pki/tls/private/server.crt;
    ssl_certificate_key /etc/pki/tls/private/myserver.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;


    # modern configuration
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # verify chain of trust of OCSP response using Root CA and Intermediate certs
    # ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;

    # Resolver defined in /etc/resolv.conf

    location / {
        proxy_connect_timeout 5m;
        proxy_read_timeout 5m;
        proxy_send_timeout 5m;
        proxy_buffer_size   128k;
        proxy_buffers   4 256k;
        proxy_busy_buffers_size   256k;
        proxy_set_header X-Forwarded-Host chanjo2-stage.scilifelab.se;
        proxy_set_header X-Forwarded-Server chanjo2-stage.scilifelab.se;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host chanjo2-stage.scilifelab.se;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:7071;
	}
}
```

**Comment by Jakob37** [comment]
Thank you! That will be useful. We are running NGINX in production, but in the testing environment I have been using I have not set it up. Maybe that is something I have to look into then.

I also get SSL errors in Chrome for Chanjo2 (for instance it seems to fail accessing a CSS file which I can obtain if changing the URL to `http` instead of `https`), so started wondering whether we have SSL-certificates set up on our dev server and whether this plays a role, and/or whether that is unrelated.

I'll ask @mhkc more when he is back from vacation next week about more context on how he has set things up here.

I smell some more learning coming up ahead. Looking forward 😅

**Pull request merged**
