### PR TITLE
Update hpo

### PR DESCRIPTION
**Pull request by moonso**
Adds functionality to reload HPO

### CODE REVIEW

**Comment by moonso** [comment]
This is ready for merge, please have a look @robinandeer

**Comment by robinandeer** [comment]
Looks good as far as I can tell!

What's the plan here? Do we just need to reload the terms or do we need to do any further migration and updating of the interface?

**Comment by moonso** [comment]
I don't think it will affect the interface, reloading should be fine

**Comment by moonso** [comment]
Ok @robinandeer I merged this, please try to rerun `scout load hpo`and check that it works

**Pull request merged**
