### PR TITLE
Custom annotation

### PR DESCRIPTION
**Pull request by bjhall**
This PR adds support for custom annotations from VCF, that do not need to be defined in Scout. Solves: https://github.com/Clinical-Genomics/scout/issues/1578

The data needs to be defined in the VCF in an INFO field called SCOUT_CUSTOM. It takes key-value pairs (both are always treated as strings). Pairs are separated with commas and the key and values are separated by pipes. Example:

```SCOUT_CUSTOM=Some key|Some value,Another key|Another value```

**How to test**:
1. Create a VCF which has the SCOUT_CUSTOM field above in at least one variant
1. Load the case 

**Expected outcome**:
The custom annotations should be shown in the variant overview.

Both for SNVs:
image

And SVs:
image

The table is only displayed if there are custom annotations available, so it doesn't change anything if the feature is not used. If you are at all interesting in merging this I can add tests as well. I'd also be happy to change anything regarding the implementation. If you do not want to merge it I'll just keep it in our fork, and I won't be offended :)

### CODE REVIEW

**Comment by dnil** [comment]
I don't see why we couldn't keep this in here! I would prefer PRs on specific items, but why not! Anyone against - @moonso @northwestwitch?

Tests and a CHANGELOG update would be lovely. 😸

**Comment by bjhall** [comment]
The reason I don't always want to make PRs for specific items is that we are getting fairly obscure requests from our users, such as: "Show if an SV is overlapping anything from this collections of variants that I've been manually curating in an excel file for the past 10 years". Since I don't see this ever being of interest to anyone else I don't want to litter the parsing code of Scout with such things.

I will still make specific PRs for things that are of potential interest to anyone else!

I'll update the PR with tests and CHANGELOG as soon as I find the time!

**Comment by northwestwitch** [comment]
> The reason I don't always want to make PRs for specific items is that we are getting fairly obscure requests from our users, such as: "Show if an SV is overlapping anything from this collections of variants that I've been manually curating in an excel file for the past 10 years". Since I don't see this ever being of interest to anyone else I don't want to litter the parsing code of Scout with such things.
> 
> I will still make specific PRs for things that are of potential interest to anyone else!
> 
> I'll update the PR with tests and CHANGELOG as soon as I find the time!

It's OK, we get also a lot of custom request so we do understand! :)
I'm not against this PR, but I agree with Daniel: it would be nice to have tests and a changelog update.

**Comment by moonso** [comment]
Sounds like a nice feature

**Comment by bjhall** [comment]
@northwestwitch Tests and CHANGELOG entry added! Hope it's fine :)

**Comment by northwestwitch** [comment]
@moonso you approved, it this ready to merge?

**Comment by cogrho** [comment]
Hello,

Are custom annotations also available for cancer variants? Thanks!

**Comment by northwestwitch** [comment]
> Hello,
> 
> Are custom annotations also available for cancer variants? Thanks!

Hello! I'm quite positive that they are parsed, but I'm not 100% certain that they are shown on cancer variants pages. Are you asking before you don't see your custom annotations?

**Comment by cogrho** [comment]
Hi, @northwestwitch! 
Thank you for the quick response! I attempted to add the SCOUT_CUSTOM INFO tag to some somatic variants and then loaded the VCF file into Scout. However, it seems like the custom annotations are not being displayed on the cancer variants page.

**Comment by northwestwitch** [comment]
> Hi, @northwestwitch!
> Thank you for the quick response! I attempted to add the SCOUT_CUSTOM INFO tag to some somatic variants and then loaded the VCF file into Scout. However, it seems like the custom annotations are not being displayed on the cancer variants page.

I see, what probably happened is that when we separated the template page for cancer variants from the general variant template we didn't include the code for displaying the custom annotations. We'll fix it, thanks for reporting the issue!

**Pull request merged**
