### PR TITLE
Display SV Variants AFs in Cancer SVs page

### LINKED ISSUE #3595: Customer wants to be able to filter CANCER SVs by tumor or normal alt freq
But tumor or normal alt freq looks like this:

image

Example: https://scout.scilifelab.se/cust109/F0041632-1/cancer/sv-variants?variant_type=clinical

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #3595 

Before:

image

After:

image

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the paxa software installed on `hasta`:
 - Log in into hasta: `ssh <USER.NAME>@hasta.scilifelab.se`
 - Activate the staging environment with the command `us` (Use Stage)
 - Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the server cg-vm1 as server.
1. Log out from the hasta server.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**How to test**:
1. Locally, delete the demo cancer case: `scout --demo delete case -i cust000 -c cancer_test`
2. Reupload it from this branch : `scout --demo load case scout/demo/cancer.load_config.yaml`

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by dnil** [comment]
Again, a bit same thing as with the other issue. I would be rather hesitant to make that calculation, or at least differentiate it heavily on caller and variant type. For pure del dup and read depth calling, it is very doable. For split reads, it is sometimes possible to calculate. For discordant pairs, complicated to say the least. And for combination callers, a djungle!

**Comment by northwestwitch** [comment]
> Again, a bit same thing as with the other issue. I would be rather hesitant to make that calculation, or at least differentiate it heavily on caller and variant type. For pure del dup and read depth calling, it is very doable. For split reads, it is sometimes possible to calculate. For discordant pairs, complicated to say the least. And for combination callers, a djungle!

I see your point. So there are these 2 solutions, perhaps

- Calculate only for DELs and DUPs
- Remove entirely option to filter by AF

Starting to make complicate calculations according to variant type looks messy and dangerous..

**Comment by northwestwitch** [comment]
Closing this PR, as it's not really fixing the issue. Let's keep the original issue open and see if we can find a way to fix it

**Comment by dnil** [comment]
> > Again, a bit same thing as with the other issue. I would be rather hesitant to make that calculation, or at least differentiate it heavily on caller and variant type. For pure del dup and read depth calling, it is very doable. For split reads, it is sometimes possible to calculate. For discordant pairs, complicated to say the least. And for combination callers, a djungle!
> 
> I see your point. So there are these 2 solutions, perhaps:
> 
> * Calculate only for DELs and DUPs
> * Remove entirely the option to filter by AF
> 
> Starting to make complicate calculations according to variant type looks messy and dangerous..

Yes, better left with the callers / pipeline if at all possible! I might lean towards just add a tooltip warning, but it is likely much more a trap than useful as is.

**Comment by dnil** [comment]
Sorry! 😊

**Pull request closed without merging**
