### PR TITLE
Partial causatives

### LINKED ISSUE #291: Partial causative feature and associated HPO-terms
Sometimes a variant only explains part of the phenotype. 
A feature that marks variant(s) as partial causative and the option to attach HPO-terms that explain which symptoms that the partial causative variants contribute to would be a great addition. Especially when sharing data.

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality (fix #291)

**How to test**:
1. Install the branch on stage
1. Mark one or more (SNV) variants as causative or partial causative (SV variants fix ongoing)
1. Make sure that you have to associate a phenotype (HPO terms or OMIM diagnosis) to each partial causative.
1. Make sure case is not marked as solved when a partial causative variant is assigned.
1. Make sure that specific links to phenotypes on case page work.
1. Make sure events are correctly recorded.
1. Make sure you can remove causative and partial causative variants.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by dNil
- [x] tests executed by CR

In the end I didn’t add the requirement of having a phenotype before marking a variant as causative, it’s already quite complicated as it is. We can take it on another PR

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is ready for review. @dnil I've found a nice way to test macros. Look at how I test the new macro in this PR!

**Comment by dnil** [comment]
I confirm local test working as well. 

After adding a partial, I miss a way to assign (remaining?) HPO terms/OMIM disorders to the next causative. And a way to optionally mark the case as solved after adding (typically more than one) partial.

**Comment by northwestwitch** [comment]
> I confirm local test working as well.
> 
> After adding a partial, I miss a way to assign (remaining?) HPO terms/OMIM disorders to the next causative. And a way to optionally mark the case as solved after adding (typically more than one) partial. But I digress. That all belongs to the philosophical realm of what is actually causative. Practically the user can leave primary realevant HPO / OMIM terms on the case, and pick the other variant as causative. 🤷‍♂
> 
> Really nice with the macro sub-page test! Well done - that will be very useful! 🚀

Should I add something or this is fine for now?

**Comment by dnil** [comment]
I think it works like this. How about you? Those and a bunch of possible follow ups, like showing partial_causatives on the causatives view, can be addressed in separate PRs if requested?

**Comment by northwestwitch** [comment]
> I think it works like this. How about you? Those and a bunch of possible follow ups, like showing partial_causatives on the causatives view, can be addressed in separate PRs if requested?

I agree, otherwise it becomes huge!

**Pull request merged**
