### PR TITLE
Version 4.87 - configure RNA build, add igv.js genome aliases

### PR DESCRIPTION
**Pull request by dnil**
This PR marks a new Scout release. We apply semantic versioning. This is a minor release for reasons.

### Added
- [x] Option to configure RNA build on case load (default '38')
### Changed
- [x] Tooltip on RNA alignments now shows RNA genome build version
- [x] Updated igv.js to v3.0.4
### Fixed
- [x] Style of "SNVs" and "SVs" buttons on WTS Outliers page
- [x] Chromosome alias files for igv.js
- [x] Genes track displayed also when RNA alignments are present without splice junctions track on igv browser
- [x] Genes track displayed again when splice junction tracks are present

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by DN, CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Ok. I've deployed the latest on stage now

**Comment by northwestwitch** [comment]
Alignment of buttons in the omics variants can be tested here --> https://scout-stage.scilifelab.se/cust002/F0044127/omics_variants/outliers

**Comment by northwestwitch** [comment]
Do we have an example of a case with TOMTE analysis in build hg19 to load to stage @dnil ?

**Comment by dnil** [comment]
Lets see, I did manually load one such case - I can dig it up!

**Comment by northwestwitch** [comment]
> Lets see, I did manually load one such case (`onekoala + dashingdinosaur`) - I can dig it up !

Ok, so it's tested then?

**Comment by dnil** [comment]
In a way, but let's do it with the release candidate as well. I've set it to test on hasta stage now:
Screenshot 2024-08-27 at 14 05 53
Screenshot 2024-08-27 at 14 14 04

**Comment by dnil** [comment]
Screenshot 2024-08-27 at 14 23 12
✅

**Review by northwestwitch — APPROVED** [review]
Looks great! 👍🏻

**Comment by dnil** [comment]
✅ Deployed to prod: 
Screenshot 2024-08-27 at 15 12 34

**Comment by northwestwitch** [comment]
Deployed on Hasta prod ✅

image

**Pull request merged**
