### PR TITLE
Fix parsing of variant.FORMAT DR key in parse variant file

### LINKED ISSUE #3490: Local variable 'alt_value' referenced before assignment when parsing tiddit lement
```
UnboundLocalError: local variable 'alt_value' referenced before assignment
2022-07-01 21:27:33 hasta.scilifelab.se scout.adapter.mongo.variant_loader[194066] WARNING Deleting inserted variants
2022-07-01 21:27:33 hasta.scilifelab.se scout.adapter.mongo.variant[194066] INFO Deleting old clinical  variants for case fleetjay
2022-07-01 21:27:43 hasta.scilifelab.se scout.adapter.mongo.variant[194066] INFO 7347 variants deleted
2022-07-01 21:27:43 hasta.scilifelab.se scout.commands.load.case[194066] ERROR Unhandled Exception: Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/S_scout/lib/python3.7/site-packages/scout/commands/load/case.py", line 123, in case
    adapter.load_case(config_data, update, keep_actions)
  File "/home/proj/bin/conda/envs/S_scout/lib/python3.7/site-packages/scout/adapter/mongo/case.py", line 741, in load_case
    custom_images=custom_images,
  File "/home/proj/bin/conda/envs/S_scout/lib/python3.7/site-packages/scout/adapter/mongo/variant_loader.py", line 720, in load_variants
    raise error
  File "/home/proj/bin/conda/envs/S_scout/lib/python3.7/site-packages/scout/adapter/mongo/variant_loader.py", line 714, in load_variants
    local_archive_info=local_archive_info,
  File "/home/proj/bin/conda/envs/S_scout/lib/python3.7/site-packages/scout/adapter/mongo/variant_loader.py", line 440, in _load_variants
    local_archive_info=local_archive_info,
  File "/home/proj/bin/conda/envs/S_scout/lib/python3.7/site-packages/scout/parse/variant/variant.py", line 148, in parse_variant
    variant, case["individuals"], individual_positions
  File "/home/proj/bin/conda/envs/S_scout/lib/python3.7/site-packages/scout/parse/variant/genotype.py", line 37, in parse_genotypes
    genotypes.append(parse_genotype(variant, ind, pos))
  File "/home/proj/bin/conda/envs/S_scout/lib/python3.7/site-packages/scout/parse/variant/genotype.py", line 95, in parse_genotype
    (paired_end_ref, paired_end_alt) = get_paired_ends(variant, pos)
  File "/home/proj/bin/conda/envs/S_scout/lib/python3.7/site-packages/scout/parse/variant/genotype.py", line 155, in get_paired_ends
    if alt_value >= 0:
UnboundLocalError: local variable 'alt_value' referenced before assignment
```

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #3490 

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the paxa software installed on `hasta`:
 - Log in into hasta: `ssh <USER.NAME>@hasta.scilifelab.se`
 - Activate the staging environment with the command `us` (Use Stage)
 - Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the server cg-vm1 as server.
1. Log out from the hasta server.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**How to test**:
1. Install on hasta stage and try loading one MIP case and one Balsamic case (latest Balsamic) using the code from this branch. 
2. Follow the deployment/testing docs present [here](https://github.com/Clinical-Genomics/deployment/blob/master/Scout.md): 

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
@ashwini06 @khurrammaqbool @ivadym @vwirta. This branch is now installed in hasta stage. Which case was failing the upload, so we can test loading it with it?

**Comment by ashwini06** [comment]
> @ashwini06 @khurrammaqbool @ivadym @vwirta this branch is now installed in hasta stage. Which case was failing the upload, so we can test loading it with it?

Thanks @northwestwitch for the fast fix! You can use one of WGS cases (civilsole: Tumor-only) 

scout config is here:  `/home/proj/stage/cancer/cases/civilsole/scout_load.yaml`

**Comment by northwestwitch** [comment]
Case existed:

image

SO after removing it (`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml delete case -i cust059 -c civilsole`):

Case was loaded in Scout 🆗 

image


But I got quite a number of these messages during the process: 🤔 

image

**Comment by northwestwitch** [comment]
Test re-uploading an old RD-case to make sure this fix doesn't disrupt anything:

image

Works just fine.

**Comment by northwestwitch** [comment]
I think the fix works fine in patching the code. It is still to be understood why Scout complains of finding duplicated variants during the insertion.

**Comment by northwestwitch** [comment]
I think this is fine to merge. The problem with variants as seen as duplicates vars in scout is still to be understood, but this PR is fixing the parsing bug

**Review by khurrammaqbool — APPROVED** [review]
💯

**Review by ashwini06 — APPROVED** [review]
👍🏼

**Comment by northwestwitch** [comment]
Thanks guys, merging!

**Pull request merged**
