### PR TITLE
Assign phenotype less cramped on Case page

### LINKED ISSUE #3529: Assign phenotype button cramped
A small oopsie on the phenotype card layout when shrinking the window size a little:

Screenshot 2022-08-17 at 09 43 15

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #3529 

From this:

image

To this:

image

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the paxa software installed on `hasta`:
 - Log in into hasta: `ssh <USER.NAME>@hasta.scilifelab.se`
 - Activate the staging environment with the command `us` (Use Stage)
 - Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the server cg-vm1 as server.
1. Log out from the hasta server.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by CR

### CODE REVIEW

**Review by dnil — APPROVED** [review]
💯

**Comment by northwestwitch** [comment]
> 💯

I think @mikaell assigned himself to this PR, but I don't know who started reviewing first. Thanks both anyway!

**Comment by dnil** [comment]
> > 💯
> 
> I think @mikaell assigned himself to this PR, but I don't know who started reviewing first. Thanks both anyway!

Oh, sorry @mikaell! I might not have reloaded the page before starting; probably had it open from yesterday. It would be good with a GitHub app, where stuff is up to date.

**Review by mikaell — COMMENTED** [review]
I opened this issue in a new tab this morning, so it would have been fresh out of the box. 

Anyways, I wondered off and fixed some other aesthetics. Soon done.

**Pull request merged**
