### PR TITLE
Sort select default

### LINKED ISSUE #4695: Removed panels are displayed on case page
On the panel page, we can see that the v1.0 "albinism" has been removed:

scout_removed_panel

But it is still displayed among the panels on the case page:

scout_removed_panel_shown

This is true generally for removed panels.

I suspect that this is a bug - that the removed panels shouldn't be displayed.

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.
- Fix #4695 
- Fix sorting of the select default panels dropdown - as discussed in #4695 

Marking this as a bug fix as the display of the "removed" badge was there once upon a time, but now only for the default panels. Refactored a little to do the panel hiding check separate from the default panel check and latest panel genes update.

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. remove a panel present on a case
2. look at the case page and its dropdown
✅ Screenshot 2024-07-03 at 11 45 52
✅ Screenshot 2024-07-03 at 11 47 08

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by Jakob37** [comment]
Nice, I'll give it a go!

**Comment by Jakob37** [comment]
OK, testing it out ..

I can confirm that the badges appear on the case page:

badge_apperas

I can also confirm that the sorting now works for the drop-down on the case page:

sorted_panels

Nice!

**Review by Jakob37 — APPROVED** [review]
Looks good! Eyed through the code as well, more for my learning. No comments there.

**Comment by dnil** [comment]
> We still would like some way to optionally hide panels from the "Change default gene panels" dropdown, but I guess that was probably not indended to be a part of this PR anyway. Work for the future.

No, exactly. We can certainly add more switches, but as you see every extra condition and use case for the same component is somewhat error prone. I would also suggest a bit of work on the integration side so that perhaps a slightly more reasonable number of panels could be added to each case. Or maybe we take a discussion with some relevant persons at your end and ours to see what could be generalized to help. Would it eg help if we worked in a more fine grained panel app panel handling than the current single “PanelApp Green” directly in scout?

**Comment by Jakob37** [comment]
> No, exactly. We can certainly add more switches, but as you see every extra condition and use case for the same component is somewhat error prone. 

Yes, I agree that more switches will increase complexity both of logic and UI, and that this needs to be weighed against the use benefit.

> I would also suggest a bit of work on the integration side so that perhaps a slightly more reasonable number of panels could be added to each case.

It seems to me our geneticists like to work this way - to load variants broadly, to have the opportunity to expand their search to other panels if needed, without having to re-sequence or reprompt bioinformaticians for recalculating data.

Guessing they won't be super-happy if I ask them to change how they work. But I can give it a try 😄 For instance if they would be fine with loading a narrower set of panels. Would it be possible for them (or us bioinformaticians) to add on extra if needed?

> Or maybe we take a discussion with some relevant persons at your end and ours to see what could be generalized to help. Would it eg help if we worked in a more fine grained panel app panel handling than the current single “PanelApp Green” directly in scout?

I didn't follow the last part. Can you explain a bit more what you mean with "Current single PanelApp Green" ?

It sounds like a wider discussion on panels will be needed at some point. 

Another approach which wouldn't need extra switches would be to show the "removed" tag in text also in the dropdown as such:

```
albinism (removed)
Albinism
all_genes
OldAnemi (removed)
Anemi
... and so on
```

Then it would be clear what is removed, which is the main point. They would still have a cluttered list, but that is a much smaller problem than risking selecting something removed. What do you think?

**Comment by dnil** [comment]
> I didn't follow the last part. Can you explain a bit more what you mean with "Current single PanelApp Green" ?

we currently have in app support for downloading either all panel app panels as separate scout panels (which we avoid in Solna as it gives too much clutter) and also to make one merged pan-disease panel with all PanelApp green genes automagically- same as with all morbid Omim genes. But this could certainly be reworked: we had an early plan to have a ui component to select sets of relevant panel app panels from a foldable tree of them.

> It sounds like a wider discussion on panels will be needed at some point.
> 
> Another approach which wouldn't need extra switches would be to show the "removed" tag in text also in the dropdown as such:
> 
> ```
> albinism (removed)
> Albinism
> all_genes
> OldAnemi (removed)
> Anemi
> ... and so on
> ```
> 
> Then it would be clear what is removed, which is the main point. They would still have a cluttered list, but that is a much smaller problem than risking selecting something removed. What do you think?

Simple and effective! Me like - sounds like a plan!

**Pull request merged**
