### PR TITLE
Tentative fix to file downloads issue

### LINKED ISSUE #3093: MT report access
Given the recent server move in Solna, this is likely a servers issue, but I'll post it here for now:
```
2022-01-19 11:28:44,461 - scout.server.app - ERROR: Exception on /cust003/21323/mt_report [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
 File "/home/worker/app/scout/server/blueprints/cases/views.py", line 251, in mt_report
   os.makedirs(temp_excel_dir, exist_ok=True)
 File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
   mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/worker/app/scout/server/blueprints/cases/static/21323_mt_reports'
```

### LINKED ISSUE #3094: Not possible to download mtDNA report
It is not possible to download the mtDNA report. I get the error message about Internal Server Error. 

Did something happen during todays update?

### PR DESCRIPTION
**Pull request by northwestwitch**
Tentative fix to #3094 and #3093. This fixes also the download of the verified variants.

**How to test**:
1. Install on cg-vm1 and check that MYT reports and validated vars files can be downloaded

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by DN
- [x] tests executed by DN. CR

### CODE REVIEW

**Comment by dnil** [comment]
verified variants are now 🆗

**Comment by northwestwitch** [comment]
Ok the new error is caused by [this issue in chanjo-report](https://github.com/Clinical-Genomics/chanjo-report/issues/17) and not by Scout itself. I think we might merge this one.. @dnil ?

**Review by dnil — APPROVED** [review]
👍🏻

**Comment by northwestwitch** [comment]
This is the fist PR that has these labels:  😆 

image

**Comment by northwestwitch** [comment]
Yess, fixed it!!!

image

**Pull request merged**
