### PR TITLE
Minor release 4.83

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Edit ACMG classifications from variant page (only for classifications with criteria)
- [x] Events for case CLI events (load case, update case, update individual)
- [x] Support for loading and displaying local custom IGV tracks
- [x] MANE IGV track to be used as a local track for igv.js (see scout demo config file)
- [x] Optional separate MT VCFs, for `nf-core/raredisease`
### Changed
- [x] Avoid passing verbs from CaseHandler - functions for case sample and individual in CaseEventHandler
- [x] Hide mtDNA report and coverage report links on case sidebar for cases with WTS data only
- [x] Modified OMIM-AUTO gene panel to include genes in both genome builds
- [x] Moved chanjo code into a dedicated extension
- [x] Optimise the function that collects "match-safe" genes for an institute by avoiding duplicated genes from different panels
- [x] Users must actively select "show matching causatives/managed" on a case page to see matching numbers
- [x] Upgraded python version from 3.8 to 3.11 in Docker images
### Fixed
- [x] Fix several tests that relied on number of events after setup to be 0
- [x] Removed unused load case function
- [x] Artwork logo sync sketch with png and export svg
- [x] Clearer exception handling on chanjo-report setup - fail early and visibly
- [x] mtDNA report crashing when one or more samples from a case is not in the chanjo database
- [x] Case page crashing on missing phenotype terms
- [x] ACMG benign modifiers
- [x] Speed up tests by caching python env correctly in Github action and adding two more test groups
- [x] Agile issue templates were added globally to the CG-org. Adding custom issue templates to avoid exposing customers
- [x] PanelApp panel not saving genes with empty `EnsembleGeneIds` list
- [x] Speed up checking outdated gene panels
- [x] Do not load research variants automatically when loading a case

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by DN
- [x] tests executed by DN, CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Tested updating the OMIM panel: 🆗 

image

**Comment by northwestwitch** [comment]
Tested updating PanelApp green: 🆗 

image

**Comment by northwestwitch** [comment]
Re-uploaded [strongbison](https://scout-stage.scilifelab.se/cust000/15026-mip7), used for testing cli case events and that no research variants were loaded

**Comment by northwestwitch** [comment]
Mane local track can be tested with [this variant](https://scout-stage.scilifelab.se/cust002/F0047445-4/c80a832722da5ea8051860b3e1811806)

**Comment by dnil** [comment]
Benign strength modifiers no longer contribute to the pathogenic side:
Screenshot 2024-06-10 at 14 31 44

**Comment by dnil** [comment]
But this is perhaps not super elegant:
Screenshot 2024-06-10 at 14 31 09

**Comment by dnil** [comment]
> Mmm the force update option updates the panel but not the date. This happens because I'm still using the panel files from last time I guess. But still..

If I recall correctly, that was a somewhat intended or at least accepted feature, but yes, it is not obvious. Perhaps make an issue anyway?

**Comment by northwestwitch** [comment]
> If I recall correctly, that was a somewhat intended or at least accepted feature, but yes, it is not obvious. Perhaps make an issue anyway?

Yes I think I will, because when you have the same date and 2 different panels in terms of content it can be confusing

**Comment by dnil** [comment]
Load split out MT VCFs 
Screenshot 2024-06-10 at 15 07 01
...
Screenshot 2024-06-10 at 15 07 58
99 MT vars show inserted BUT no MT vars appear when filtering?!
Screenshot 2024-06-10 at 15 13 00
Chromosome naming, ranking or load error?

**Comment by northwestwitch** [comment]
> Chromosome naming, ranking or load error?

MT vs M?

**Comment by dnil** [comment]
> > Chromosome naming, ranking or load error?
> 
> MT vs M?

Could be yes: checking..

**Comment by dnil** [comment]
So, all good on the MT vars. Well, they are still not run with `distance=0` but let's not worry about that for the time being.

**Comment by dnil** [comment]
When artificially emptying phenotype_terms (we still have not been able to fathom how that happens in practice):
Screenshot 2024-06-10 at 15 48 27
the case page is still live and well:
Screenshot 2024-06-10 at 15 48 10

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
deployed on hasta prod now:

image

**Comment by northwestwitch** [comment]
Deployed on cg-prod-services as well:

image

**Pull request merged**
