### PR TITLE
Bulk dismiss SNVs, SVs and cancer SNVs

### LINKED ISSUE #2081: Dismissing variants from variants page loads variants with default filters..
Something seems to be off with parameter passing to the dismiss form - dismissing clears filter..

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #2081 

This PR:
- removes the code to dismiss single variants from variants pages (all types of variants).
- Adds a system to dismiss many variants at the time for 
  - SNVs (rare disease track)
  - SVs (rare disease track)
  - Cancer SNVs (cancer track)

Screenshot:
image

I've tried to apply this system also to cancer SVs and STRS but I had problems:
- cancer SVs  returns an error that I couldn't fix yet 
- and STRS page contains a form to show bam files and since this multi-checkbox system must be included in another form, but you can't have a form inside a form, I just reverted the code to how it was before the dismiss.

Of course the things above might be fixed, but it will take time, and we don't have much time for the patch of current version..

**How to test**:
1. On stage, try to dismiss SNVs, SVs and cancer SNVs.
1. Make sure that if you were filtering the variants using any filter, these filters are still used when the page reloads after dismissing one or more variants
1. It shouldn't be possible to dismiss single variants any more from STRs and cancer SVs (cancer SVs behavior might be tested on a local instance of scout after loading the demo cancer sample)

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is ready for review. Doesn't pass the linting of Javascript for some extra spaces but it's not I won't sleep at night over thinking about it.

**Comment by dnil** [comment]
I'd say dismissal of cancer SVs and STRs are very low usage at the moment: at least that is the case on the Solna instance.   Perhaps just make a new issue for them? I can have a look at the STR page later: might be possible to do something along the lines of the pagination label trick to fix the out-of-form experience.

**Comment by elevu** [comment]
On this case https://scout-stage.scilifelab.se/cust000/GIAluc14p19fam/variants?variant_type=clinical
I am getting this error when trying to dismiss: 
`enableDismiss is not defined`
Screen Shot 2020-09-10 at 18 26 13

**Comment by northwestwitch** [comment]
> On this case https://scout-stage.scilifelab.se/cust000/GIAluc14p19fam/variants?variant_type=clinical
> I am getting this error when trying to dismiss:
> `enableDismiss is not defined`
> Screen Shot 2020-09-10 at 18 26 13

Even after clearing the file cache?

**Comment by elevu** [comment]
Great! It works now! Just one tiny thing, maybe you can remove the dimiss variant table button block in buttons.html?

`
{% macro dismiss_variant_table_button(variant, institute, case, dismiss_variant_options) %}
`

**Review by elevu — COMMENTED** [review]
Awesome!

**Review by elevu — APPROVED** [review]
re-awesome :D

**Pull request merged**
