### PR TITLE
Automatic black 20.8b1, test compatibility with click>7

### PR DESCRIPTION
**Pull request by dnil**
Black updated to 20.8b1 yesterday. This causes some issues with the interaction of pre-commit and GitHub Actions linting. 
An updated black and lint agree well, but pre-commit is not quite there on the train yet. I would suggest disabling it for now?

**Expected outcome**:
The functionality should be working

**Review:**
- [x] code approved by CR
- [x] tests executed by github actions

### CODE REVIEW

**Comment by dnil** [comment]
Ok, I think that would be it from the black part. Please check, but from my point of view this works. 

Black does not show up X:ed, and Lint Action does not find anything to fuss about or actually change. Depending on ones local config it may be necessary to go with manually 
```bash
black -l 100 --exclude "/(\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|buck-out|dist)/"
git commit --no-verify
```
or similar to avoid having to see pre-commit formatting and lint-actions until pre-commit catches up.

The new version of black also has newer deps, so we will have problems in October. I suggest we resolve the Click situation soon. In principle it may have been resolved by switching the OAuth system?

Here's the pip summary:
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

mkdocs-material 4.6.1 requires markdown>=3.2, but you'll have markdown 3.0.1 which is incompatible.
black 20.8b1 requires click>=7.1.2, but you'll have click 6.7 which is incompatible.
```

**Comment by northwestwitch** [comment]
Why did we freeze click to <7 ??

**Comment by dnil** [comment]
I think the old OAuth lib had to do with it, but there may be more. Let's see!

**Comment by northwestwitch** [comment]
> I think the old OAuth lib had to do with it, but there may be more. Let's see!

🤞

**Comment by dnil** [comment]
Doesn't look like much, but help me demarcate here: should I just back out black out of the dev req for now, and solve the click thing in a separate PR, or do it all at once?

**Comment by northwestwitch** [comment]
I think click >=7 has modified the error messages slightly

**Comment by dnil** [comment]
Agree, so not much to change, IF thats the only thing. Maybe I give it a couple of iterations then.

**Comment by northwestwitch** [comment]
> Doesn't look like much, but help me demarcate here: should I just back out black out of the dev req for now, and solve the click thing in a separate PR, or do it all at once?

I have no idea how many changes would that be honestly, let's pytest locally and see how many of them fail perhaps?

**Comment by dnil** [comment]
I'm missing an "update brach" option - will it appear after approval? Or is that because master fails?

**Comment by northwestwitch** [comment]
We're good @dnil! All tests pass now! 👯

**Review by northwestwitch — APPROVED** [review]
Looks fine!

**Comment by northwestwitch** [comment]
> "update brach" option - will it appear after approval? Or is

Haven't seen that option in a long while

**Comment by northwestwitch** [comment]
Merging in 3, 2, 1..

**Comment by dnil** [comment]
No, you are right, its keeping track of mergeability now instead.

**Pull request merged**
