### PR TITLE
Minor release v4.70

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Download a list of Gene Variants (max 500) resulting from SNVs and Indels search'
- [x] Variant PubMed link to search for gene symbol and any aliases
### Changed
- [x] Clearer gnomAD values in Variants page
### Fixed
- [x] CaseS page uniform column widths
- [x] Include ClinVar variants into a scrollable div element on Case page
- [x] `canonical_transcript` variable not initialized in get_hgvs function (server.blueprints.institutes.controllers.py)
- [x] Catch and display any error while importing Phenopacket info
- [x] Modified Docker files to use python:3.8-slim-bullseye to prevent gunicorn workers booting error

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by DN
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by northwestwitch** [comment]
Deployed on stage now!

**Comment by northwestwitch** [comment]
I could reproduce the `canonical_transcript`  error by searching for the following mongodb query:

`db.variant.find({category: 'snv','genes.canonical_transcript': {$exists: false}, rank_score : {"$gt":5}})`

In practice you can look for a variant with this query:

image

**Comment by northwestwitch** [comment]
Old scout version (4.69):

image

```
2023-06-22 10:43:25,870 - [scout.server.app](http://scout.server.app/) - ERROR: Exception on /cust002/gene_variants [POST] [in /venv/lib/python3.8/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/worker/app/scout/server/utils.py", line 85, in decorated_function
    context = func(*args, **kwargs)
  File "/home/worker/app/scout/server/blueprints/institutes/views.py", line 163, in gene_variants
    data = controllers.gene_variants(
  File "/home/worker/app/scout/server/blueprints/institutes/controllers.py", line 592, in gene_variants
    update_variant_genes(store, variant_obj, genome_build)
  File "/home/worker/app/scout/server/blueprints/institutes/controllers.py", line 643, in update_variant_genes
    (canonical_transcript, hgvs_nucleotide, hgvs_protein) = get_hgvs(gene_obj)
  File "/home/worker/app/scout/server/blueprints/institutes/controllers.py", line 675, in get_hgvs
    return (canonical_transcript, hgvs_nucleotide, hgvs_protein)
UnboundLocalError: local variable 'canonical_transcript' referenced before assignment
```


This branch: 🆗 

image

**Review by dnil — APPROVED** [review]
👍

**Pull request merged**
