### PR TITLE
Export gene panels to PDF

### PR DESCRIPTION
**Pull request by northwestwitch**
A super simple export function to save gene panels to PDF.

### CODE REVIEW

**Comment by northwestwitch** [comment]
image

**Comment by northwestwitch** [comment]
image

**Comment by northwestwitch** [comment]
Relative to issue #922

**Comment by northwestwitch** [comment]
The HTML code used to build the PDF looks a bit nicer but I think that the PDF is not that ugly

**Comment by henrikstranneheim** [comment]
Nice!

**Comment by dnil** [comment]
Well done! Thats solves the issue. Do you think it would get too sluggish or visually busy showing what other panels the gene is on, like on the variant page?

**Comment by northwestwitch** [comment]
We could try! I wouldn't like to print all panels the gene belongs to on
the page because it would be a bit messy, but maybe a link that brings out
a pop-up when you touch it or something..

**Comment by northwestwitch** [comment]
If we include the html version I mean, otherwise we could put links to the
panels on the pdf. The thing is: how useful would be to know that a gene is
part of a gene panel namething short (otherwise for the genen in many
panels the info won't fit)?

**Comment by northwestwitch** [comment]
I meant "named something short", I'm writing from my cell phone and I don't
have saved my github password here to edit stuff, sorry! :)

**Comment by dnil** [comment]
The number of panels it is on might also be nice enough, but most users could guess these acronyms. It is just a bonus feature: the main issue being publishing what genes were part of the test. But if I were the doctor choosing between a few partly overlapping panels to order, it would help to be able to quickly see which panel has the best complement of genes.

Actually, why don't we just accept and merge this, and make that an update issue?

**Comment by northwestwitch** [comment]
I know! We could write the acronyms and we explain them at the end of the
report!

**Comment by northwestwitch** [comment]
I've introduced another field in the export table to show all panels a gene belongs to, with a footer explaining it. Take a look at it when you have time @dnil!

**Comment by moonso** [comment]
Looks great, is this ready @northwestwitch ?

**Comment by northwestwitch** [comment]
Ready!

**Pull request merged**
