### PR TITLE
Fix ugly  panel#2098

### PR DESCRIPTION
**Pull request by elevu**
This PR changes the style of the pinned variant card and solves issue #2098 .
Now it looks like this:
Screen Shot 2020-09-15 at 08 55 42

**How to test**:
1. on localhost or staging, pin a variant and look that the pinned variant card looks fine.

**Review:**
- [x] code approved by CR
- [x] tests executed by EM, CR

### CODE REVIEW

**Comment by elevu** [comment]
Ready for review, this branch is deployed on staging now!

**Comment by northwestwitch** [comment]
I can review!

**Review by northwestwitch — CHANGES_REQUESTED** [review]
Rare cases page looks much better now.

You could perhaps also fix:
- [ ] Cases with pinned cancer variants. Look for instance at: https://scout-stage.scilifelab.se/cust000/KMP-00104_balsamic
- [ ] Cases with pinned structural variants (https://scout-stage.scilifelab.se/cust000/620573fam50M)
- [ ]Cases with pinned cancer structural variants (testable on a local instance after importing the demo cancer case : `scout --demo load case scout/demo/cancer.load_config.yam`

**Comment by elevu** [comment]
ahh, missed it was different code to fix for the other kind of variants. Will do!

**Comment by elevu** [comment]
> * [ ]  Cases with pinned cancer variants. Look for instance at: https://scout-stage.scilifelab.se/cust000/KMP-00104_balsamic
Screen Shot 2020-09-15 at 10 52 51


> * [ ]  Cases with pinned structural variants (https://scout-stage.scilifelab.se/cust000/620573fam50M)
Screen Shot 2020-09-15 at 10 55 45
This could be centered more but doing it will make it more complicated to style the other types of pinned cases and would be less consistent with the general style.. Do you think I should center it anyway?

> * [ ]  Cases with pinned cancer structural variants 
Screen Shot 2020-09-15 at 10 58 18

**Review by northwestwitch — APPROVED** [review]
Looks much better now! 🥇

**Pull request merged**
