### PR TITLE
Fix #3926 - update igv.js to v2.15.6

### LINKED ISSUE #3926: Bugfixes in IGV 2.15.5
I don't think I have encountered this one, but perhaps we should update out of caution.

https://github.com/igvteam/igv.js/releases/tag/v2.15.5

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by DN

### CODE REVIEW

**Review by northwestwitch — APPROVED** [review]
Looks good! 👍🏻

**Comment by dnil** [comment]
Thanks! It still needs some fixing: it does fix something that was broken before (current main version):
Screenshot 2023-05-03 at 07 32 34
BUT it also has its own new issues requesting cram data:
Screenshot 2023-05-03 at 07 35 11

**Comment by dnil** [comment]
Heh, everything looks just fine with v2.15.4, so imagine there will be a fix soonish.. 😸

**Comment by dnil** [comment]
Not much that looks related here: https://github.com/igvteam/igv.js/compare/v2.15.4...v2.15.5, but perhaps the igv-utils bump has something?

**Comment by dnil** [comment]
Yes, this looks like it. https://github.com/igvteam/igv-utils/compare/v1.4.4...v1.4.5

**Comment by dnil** [comment]
It looks like it wants a HEAD method on the `/remote/static`. I think I'll ask the IGV team to make sure?

**Comment by dnil** [comment]
https://github.com/igvteam/igv.js/issues/1640

**Comment by dnil** [comment]
✅ Looks good on local and stage.

Screenshot 2023-05-04 at 11 43 01

**Comment by northwestwitch** [comment]
> ✅ Looks good on local and stage.
> 
> Screenshot 2023-05-04 at 11 43 01

Nice!

**Pull request merged**
