### PR TITLE
DRAFT: Feature configparse 210217

### PR DESCRIPTION
**Pull request by mikaell**
Taking too long time. Must merge to Master. Pytests passes, then fails :(

### CODE REVIEW

**Comment by dnil** [comment]
Yeah I know the feeling.. Try breaking out smaller parts if possible and work on them one by one.. Also ping someone (best bet @northwestwitch?) if you want hints/help from someone who knows the day to day changes with merging conflicts!

**Comment by northwestwitch** [comment]
> who knows the day to day changes with merging conflicts!

Life brings so much suffering, yes! 😄

**Comment by northwestwitch** [comment]
This PR is introducing changes in the parsing of every key/value of the config file and for this reason we have to test it super carefully with a real case. But I was wondering if it would be possible somehow possible to leave the current test as they are, at least in a first moment, so we'd know that the result of the parsing is the same as before?

**Comment by mikaell** [comment]
> This PR is introducing changes in the parsing of every key/value of the config file and for this reason we have to test it super carefully with a real case. But I was wondering if it would be possible somehow to leave the current test as they are, at least in a first moment, so we'd know that the result of the parsing is the same as before?

Yes. That is possible. In fact, that is what I've done and it works.

**Pull request closed without merging**
