### PR TITLE
added links for clinvar submitted variants under cases page

### PR DESCRIPTION
**Pull request by northwestwitch**
Now you see a small green or yellow label under the clinvar submission column for each snv/sv submitted for a case

### CODE REVIEW

**Comment by moonso** [comment]
Could you just update CHANGELING.md as well. I think we all needs to be reminded on doing this for every PR

**Comment by northwestwitch** [comment]
Sure, I'll do it! Is there any automatic way to remind you about these things? I'll google!

**Comment by ingkebil** [comment]
I'll take the liberty to start merging the commits needed for the validation

**Comment by northwestwitch** [comment]
Please don't merge #858. It will break the code

**Comment by dnil** [comment]
If you are in a hurry, better wait with #842 as well (or merge and disable panel uploads). Almost working, but I'm not positive I will be able to find the time today to look at it.

**Pull request merged**
