### PR TITLE
Improve variant page2

### PR DESCRIPTION
**Pull request by moonso**
## Second version 

This PR adds a functionaThis PR refactors the backend code for the single variant views. This is a mayor code refactoring, many lines have been splitted into own functions and some functions have been merged. In particular there is only one variant controller for all types of variants 🗡 . Hopefully it will increase the loading time for a single variant...

**How to test**:
1. Install this branch on stage
1. Browse all different types of variants

**Expected outcome**:
The functionality should be better

**Review:**
- [x] code approved by dNil
- [x] tests executed by dNil

### CODE REVIEW

**Comment by dnil** [comment]
I kind of think it will *decrease* the loading time, but I may be proven wrong in the end.. 😉

**Comment by dnil** [comment]
Still some things to work on! It's on stage now; see e.g. 
https://scout-stage.scilifelab.se/cust002/F0017223/2d7d3b9e082606dfdcfab03beae686b1
https://scout-stage.scilifelab.se/cust002/F0017223/sv/variants/dd15157cbef16a5038ff732e79d0128f
https://scout-stage.scilifelab.se/cust000/20190327_cancer/67c73695d3b99f374f9abdd091cdb44b?cancer=yes
https://scout-stage.scilifelab.se/cust000/SWEDAC-2019-HG-05-Trio-NovaSeq/d157ad402acdc2b03231552fc47b628e?str=yes

**Comment by moonso** [comment]
Nice, thanks. Thought both of those would be covered by tests... => more tests!!

**Comment by dnil** [comment]
Ok, as far as I can tell things are nice and shiny now. Quick and no crashes. I have not repeated @northwestwitch side-by-side comparison, but a random sample of the issues seem ok. I say we merge. Anyone against?

**Comment by northwestwitch** [comment]
Go on with the merge! Really good job, bith of you! 👏

**Pull request merged**
