### PR TITLE
Update to IGV.js 2.2.11

### PR DESCRIPTION
**Pull request by mikaell**
Update igv javascrit from 1.0.9 to 2.2.11. Addresses issue #1199.

This PR to update igv javascript from 1.0.9 to 2.2.11. Tests below are for 

Contact: @mikaell

### How to test
(Running Scout in demo)
1. open corresponding <filename>.config.yaml (e.i. scout/demo/643594.config.yaml)
2. edit samples:bam_path to point to a bam-file (can be found at ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1/data)
3. load the config
`$ scout --demo load case scout/demo/<filename>.config.yaml -u`
4. start scout and login
5. click the igv-button in the "Clinical Structural Variants" or in "Clinical SNV and Indels".

### Expected outcome
a. the igv view will load in a separate browser window (or tab).
b. inspect page source HTML header, where igv 2 now is called
`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/igv@2.2.11/dist/igv.min.js"></script>`

### Review
- [x] code approaved by @northwestwitch 
- [x] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Looks like your branch is not updated. You can click on Update branch so you sync with the current master!

**Comment by mikaell** [comment]
> Looks like your branch is not updated. You can click on Update branch so you sync with the current master!

Done! (By clicking the Update-button in the Github GUI. I'm not used to working this way, so correct me if that was wrong)

**Comment by northwestwitch** [comment]
Testing how IGV browser looks for the same variant first on master:

image

Then I cleaned the browser cache (you never know..)

The viewer from this branch looks like this:

image

There's a bit more space for the tracks, which is good (possibly the change done by @dnil?).

I think it's fine to merge!

**Comment by northwestwitch** [comment]
It's on stage. @adrosenbaum you have worked with stage cases with bam files, do you remember any? We just need one. Thanks!

**Comment by dnil** [comment]
Yes! This one has the split screen, and split out to see mate! 👊🏻
@northwestwitch: you can try F0029911 (cust002)! 2019-11698 is up.

**Comment by northwestwitch** [comment]
Otherwise other testable cases on clinical-db are: 
meetpossum - CEPH-1463-mip7
gladthrush - 15078-mip7
casualgannet - 15035-mip7
helpedfilly - 15030-mip7
strongbison - 15026-mip7
sharppigeon - F0007437-mip7

**Comment by northwestwitch** [comment]
The only thing that looks a bit off is this: 
image

**Comment by mikaell** [comment]
@northwestwitch I suspect the logo is design -though I agree it looks weird. Like shading. Maybe it can be removed if we run our own css-file.

**Comment by northwestwitch** [comment]
> @northwestwitch I suspect the logo is design -though I agree it looks weird. Like shading. Maybe it can be removed if we run our own css-file.

Don't worry about the logo. Let's merge. We can fix it after, it's not affecting the visualization of the tracks!

**Comment by northwestwitch** [comment]
You can merge, but don't forget to update the changelog first!

**Pull request merged**
