### PR TITLE
fix #1416

### LINKED ISSUE #1416: Weird variant lines in variants template
Look at the rank col!

image

### PR DESCRIPTION
**Pull request by northwestwitch**
fix #1416

**How to test**:
1. git checkout to this branch
1. Make sure that rank cell in variants page doesn't look like #1416

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by dNil
- [x] tests executed by dNil

### CODE REVIEW

**Comment by dnil** [comment]
When more exactly did this behaviour appear? Mine look nicely justified and centered, so don't know where to look for a change? Stacking all the different things that might appear in that cell in a jumble to the left doesn't quite sound like the solution, but maybe if I knew what drove it there I would understand better?

Screenshot 2019-10-23 at 10 31 32

**Comment by northwestwitch** [comment]
> When more exactly did this behaviour appear? Mine look nicely justified and centered, so don't know where to look for a change? Stacking all the different things that might appear in that cell in a jumble to the left doesn't quite sound like the solution, but maybe if I knew what drove it there I would understand better?
> 
> Screenshot 2019-10-23 at 10 31 32

For instance here:
https://scout-stage.scilifelab.se/cust000/WNB128N/variants?variant_type=clinical&gene_panels=OMIM-AUTO 

I think it happens when the content of a line doesn't fit the line (for instance many gene annotations or Func. annotation)..

**Comment by northwestwitch** [comment]
Otherwise of course it's better with the official col- thingy

**Comment by northwestwitch** [comment]
The double badge thing might be solved by a pop-up explaining where the classificstion comes from?

**Comment by dnil** [comment]
Nah, lets ignore it for the present case. It's like if the matching pathogenic would include the current case. Simply not elegant. It used to (and should still) have a distinct appearance - different kind of badge - that would indicate that it is not from the same case at any rate.

**Comment by dnil** [comment]
But ok, lets leave it with tooltips - otherwise we have to touch the variant controller again... Lets revisit that at another time.

**Comment by dnil** [comment]
How about this compromise then? Not the most elegant, but good for now perhaps?
Screenshot 2019-10-23 at 17 07 40

**Comment by northwestwitch** [comment]
Ok! Why there are badges with numbers?

**Comment by dnil** [comment]
Thats the manual ranks. Cant say I quite like that representation, but we've had that for a long time. At some point we should make badgeable abbreviations for them as well.

**Pull request merged**
