### PR TITLE
Update igv.js to v 3.0.1

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug.
- There was a new major release of igv.js yesterday ---> https://github.com/igvteam/igv.js/releases/tag/v3.0.0

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by DN
- [x] tests executed by CR

### CODE REVIEW

**Comment by dnil** [comment]
Looks good in general. I guess we should go through it carefully - some small things appear to have changed, and perhaps need configuration or patching. 

One is the variant colouring for the coverage track 
Screenshot 2024-08-05 at 08 36 11
compared to prod
Screenshot 2024-08-05 at 08 42 59.

**Comment by northwestwitch** [comment]
> Looks good in general. I guess we should go through it carefully

It's a major. Let's monitor their issues to see if there are bugs

**Comment by dnil** [comment]
> > Looks good in general. I guess we should go through it carefully
> 
> It's a major. Let's monitor their issues to see if there are bugs

Yep - looks very smooth for a major change so far! I made an issue https://github.com/igvteam/igv.js/issues/1860 for the mismatches for now.

**Review by dnil — CHANGES_REQUESTED** [review]
While it looks very smooth for a major, we should wait for a first patch. This will become blocking at some point for the very nifty LR base modification visualisation introduced in v3.

**Comment by northwestwitch** [comment]
Ah look, they have fixed the bug and there is a patch now---> https://github.com/igvteam/igv.js/releases/tag/v3.0.1

**Comment by dnil** [comment]
> Ah look, they have fixed the bug and there is a patch now---> https://github.com/igvteam/igv.js/releases/tag/v3.0.1

Yes, time zones working wonders! 😉

**Review by dnil — APPROVED** [review]

**Comment by dnil** [comment]
I also asked about the splice junction track (https://github.com/igvteam/igv.js/issues/1863). I can't say it is the perfect timing to upgrade, but v3 has nice features and `igv.js` is well maintained.

**Pull request merged**
