### PR TITLE
Fix password visibility in LDAP login form

### LINKED ISSUE #3349: Passwords are not hidden when using LDAP login
Passwords are not hidden when using LDAP login.

bild

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #3349 

**How to test**:
1. Try login with an LDAP user

**Expected outcome**:
Password shouldn't be visible during typing

**Review:**
- [x] code approved by DN
- [X] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Before:

image


After:

image

**Comment by mhkc** [comment]
Looks good. I will be able to review this next week

**Review by dnil — APPROVED** [review]
Looks good! 👍

**Comment by dnil** [comment]
> Looks good. I will be able to review this next week

Ah, sorry, too tempting! But good if you test it on your side of course! Feel free to take another one instead! 😉

**Comment by northwestwitch** [comment]
I've tested locally with a Dockerized LDAP server and it works fine, also the login. I think I'll just merge then. Thanks both!

**Pull request merged**
