### PR TITLE
Fix multigene cancer variant summary

### LINKED ISSUE #2826: Problems in cancer scout after the last Scout uppdate
Hi, after the last Scout update a few things are not working as they should in Cancer Scout:

- [x]  Links till “matching causatives from other cases” are not working, e.g.
https://scout.scilifelab.se/cust087/F0041371/cancer/504a020f0068b44557720d5c04c4da0e?cancer=yes

- [x] In the variant page, the gene information is not about the gene in which the mutation was found, e.g. CSDE1 - NRAS
https://scout.scilifelab.se/cust087/F0041371/cancer/91bdff58f63b755cb9ac067040311edb?cancer=yes (in the list with variants it was correctly listed as variant in NRAS)

- [x]  Link to COSMIC is not to the correct variant, e.g.:
Example A: https://scout.scilifelab.se/cust087/F0041371/cancer/504a020f0068b44557720d5c04c4da0e?cancer=yes
There are 3 well-described point mutations at this position, but the link does not include the one that was found in this patient even though it is reported in COSMIC (https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=42635557)

Example B:
https://scout.scilifelab.se/cust087/F0041371/cancer/6a2cb83e3f6bfbda297bb9625b55d58a?cancer=yes
COSMIC link to c.2601C>A instead of C>T --> non-synonymous change which is reported in hematological cases rather than the synonymous aa change that was found in the patient

### PR DESCRIPTION
**Pull request by northwestwitch**
At the moment cancer variant summary shows the info for a single gene even if the variant hits several genes (fix #2826 and partially fixing #2835).

My fix is perhaps naive since I'm removing most of the info obtained in the jinja parsing (see code) to leave only gene ID and gene name. But I was thinking that:
- Most (if not all) of the jinja parsed info is showed later in the page anyway
- That code is a bit hard to read and to maintain. And the choice of the primary transcript or NM transcript to show with associated exon is a bit arbitrary and could be misleading (see also #2835, first problem) . Perhaps a simpler solutions wound't be so bad..

**How to test**:
1. On clinical-db stage go to a cancer variant hitting multiple genes, esample: https://scout-stage.scilifelab.se/cust000/balsamic-validation-gmsmyeloid-tumor-only-2/cancer/ac4fa05770c2e462ed36d23fe673ea4e?cancer=yes
2. Master branch should show just one gene info in variant summary
3. Install this branch and 2 genes should be shown instead

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Before:
image


After:
image

**Comment by northwestwitch** [comment]
@dnil a quick review if you have time? It's becoming more urgent as 2 users already complained for this bug

**Comment by dnil** [comment]
Ah, I thought it was just that they didnt understand the new feature from @mhkc; I'll take a look when things quiet down later in the morning!

**Comment by northwestwitch** [comment]
Closing this, as it's a duplicate of #2840

**Pull request closed without merging**
