### PR TITLE
Provide SVG logo

### LINKED ISSUE #4633: Add SVG logos
We had a request for SVG artwork. Also it seems the old sketch is not exactly up to date with the PNGs.

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.
- Fix #4633 

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. open the Files changed tab
2. look at SVG logos
3. if you really want to, install Sketch and check out the sketch file deltas - I've tried to recreate the appearance in the PNGs by changing the default font there to my best guesstimate of what is in the PNGs.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by dnil** [comment]
> Could you provide a bit of description on how to test this PR? For instance I don't see the favicon if I deploy locally

In case this wasn't entirely in jest, the current `favicon.ico`, being a partial rendition of the previous `Sc`ilifelab logo that fortuitosly coincided with the beginning of `Sc`out I suggest we keep that for now?

**Comment by northwestwitch** [comment]
> > Could you provide a bit of description on how to test this PR? For instance I don't see the favicon if I deploy locally
> 
> In case this wasn't entirely in jest, the current `favicon.ico`, being a partial rendition of the previous `Sc`ilifelab logo that fortuitosly coincided with the beginning of `Sc`out, I would suggest we keep that for now.

When I deploy the branch still looks like this?

image

**Comment by dnil** [comment]
Indeed. As stated, that is precisely as intended. The old "favicon.png" from the artwork folder (or the sketch track called favicon) was also not in current use as the favicon. No change to the active code is expected, but collaborators will now have svg images for download and use at their leisure on e.g. posters.

**Comment by northwestwitch** [comment]
> Indeed. As stated, that is precisely as intended. The old "favicon.png" from the artwork folder (or the sketch track called favicon) was also not in current use as the favicon. No change to the active code is expected, but collaborators will now have svg images for download and use at their leisure on e.g. posters.

See that it required an explanation? :)

**Review by northwestwitch — APPROVED** [review]
Nice! 👍🏻

**Comment by northwestwitch** [comment]
> Not really? Im still convinced you're just trolling. `favicon` is retrieved as

I'm not. I was missing the purpose, now I know!

**Comment by dnil** [comment]
> I'm not. I was missing the purpose, now I know!

Ah. Next it's time to me you are not actually a mind reader - seems appropriate. In hindsight adding a sentence or two would have saved time and effort. 😆

**Comment by northwestwitch** [comment]
> Ah. Next it's time to remind me you are not actually a mind reader - seems appropriate. In hindsight adding a sentence or two would have saved time and effort. 😆

No worries!

**Pull request merged**
