### PR TITLE
hotfix version 4.6.1

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR fixes the bug described in #1268

**How to test**:
This bug is reproducible and testable by loading the cancer case in demo data:
1. To reproduce: from root folder of a local scout repo (being in master branch)
```
scout --demo load case scout/demo/cancer.load_config.yaml
```
 You will observe the error described in  #1268 ('father' key is missing in parse case function).

2. git checkout to this fix branch:
```
git checkout  release_4.6.1
```
Repeat the load case command described above and the upload of the case should be successful.

**Expected outcome**:
Case should be correctly inserted

**Review:**
- [x] code approved by Daniel Nilsson
- [x] tests executed by Chiara Rasi
- [x] "merge and deploy" approved by @ingkebil

### CODE REVIEW

**Comment by northwestwitch** [comment]
Tested the command and from the bugfix branch and after the fix the case load works, see screenshot:
image

**Comment by northwestwitch** [comment]
@ingkebil when you have time, we'd like to deploy a hotfix for scout. Thanks!

**Comment by northwestwitch** [comment]
Thanks @dnil !!

**Comment by dnil** [comment]
NP! And when this cools down slightly, we should add a test actually loading a couple of different files.. 😊

**Comment by northwestwitch** [comment]
> NP! And when this cools down slightly, we should add a test actually loading a couple of different files.. 😊

Agreed!

**Comment by ingkebil** [comment]
Looks good! :hammer:

**Comment by northwestwitch** [comment]
> Looks good! 🔨

Thanks! I'm merging. Could you please help me to deploy it to prod (can't become hiseq.clinical), Thanks!

**Comment by northwestwitch** [comment]
@ingkebil on hasta, not clinical-db (where I can update it by myself).

**Comment by ingkebil** [comment]
Deployed! :tada:

**Comment by northwestwitch** [comment]
Thanks!

**Pull request merged**
