### PR TITLE
Show MANE functional annotations on variant's summary

### LINKED ISSUE #4431: Show the CSQ/Function of related MANE transcript in gene summary in variant view
Hej again from Lund,

Here comes a request from our geneticists:

If I understand it correctly, the variant consequence displayed in the summary table is the most severe consequence picked out from all associated transcripts. 

This leads to cases where—while the MANE transcript is associated with a low impact consequence—some sometimes really obscure transcript can steal the show with a frameshift. 

What was suggested during the meeting was something conveying the following info:

bild

What do you think?

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug.
- Display functional annotations associated to MANE transcripts on variant summary. Closes #4431

Tested locally with a demo variant from a pretend build 38 case (after adding a MANE select tx to the variant as well)

image

image

Dark mode:

image

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by ALKC
- [x] tests executed by CR, ALKC

### CODE REVIEW

**Comment by northwestwitch** [comment]
Hi @alkc I have this other PR ready for the issue you opened last week. It should be an easy review, same code touched by the other one. Thanks!

**Comment by alkc** [comment]
Works nicely!

bild

Small question btw: is there a reason the column is called "Function" rather than "Consequence" ?

**Comment by northwestwitch** [comment]
> Small question btw: is there a reason the column is called "Function" rather than "Consequence" ?

I've just copied the title from the column nearby, but good point, let's change the naming in both! 😄

**Comment by dnil** [comment]
> > Small question btw: is there a reason the column is called "Function" rather than "Consequence" ?
> 
> I've just copied the title from the column nearby, but good point, let's change the naming in both! 😄

Hihi, either works - the long form is "Functional consequence", but we needed an abbrev.. 😁

**Review by alkc — APPROVED** [review]

**Comment by alkc** [comment]
> Thanks for the review and the testing @alkc

You're welcome!

Just to document what was tested/reviewed:

I reviewed the code and tested this branch on a case variant where the consequence annotation in the summary table had previously confused our clinicians.

**Pull request merged**
