### PR TITLE
Bump version to 4.7.2

### PR DESCRIPTION
**Pull request by dnil**
Adjust changelog for master *after* release.

**Review:**
- [x] code approved by CR

### CODE REVIEW

**Comment by moonso** [comment]
Why do you have two PRs for one release?

**Comment by dnil** [comment]
For adjustment of changelog as per dev instructions. We can't push that in directly anymore, due to the review & testing requirement hooks.

**Comment by northwestwitch** [comment]
I also didn't understand. But it's good with the release notes, so ok!

**Comment by moonso** [comment]
OMG

**Comment by northwestwitch** [comment]
I'm going to merge this last before deploying today

**Comment by dnil** [comment]
Id suggest after deploy, but its a human-read only text file, so whichever is better for you!

**Pull request merged**
