### PR TITLE
Minor release 4.91

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] MANE badges on list of variant's Genes/Transcripts/Proteins table, this way also SVs will display MANE annotations
- [x] Export variant type and callers-related info fields when exporting variants from variants pages
- [x] Cases advanced search on the dashboard page
- [x] Possibility to use only signed off panels when building the PanelApp GREEN panel
- [x] Variant link to Franklin in database buttons (different depending on rare or cancer track)
### Changed
- [x] On genes panel page and gene panel PDF export, it's more evident which genes were newly introduced into the panel
- [x] WTS outlier position copy button on WTS outliers page
- [x] Update IGV.js to v3.0.9
- [x] Managed variants VCF export more verbose on SVs
- [x] `/api/v1/hpo-terms` returns pymongo OperationFailure errors when provided query string contains problematic characters
- [x] When parsing variants, prioritise caller AF if set in FORMAT.
- [x] Expand the submissions information section on the ClinVar submissions page to fully display long text entries
- [x] Jarvik for PP1 added to ACMG modification guidelines
- [x] Display institute _id + display name on dashboard filters
- [x] ClinVar category 8 has changed to "Conflicting classifications of pathogenicity" instead of "interpretations"
- [x] Simplify always loading ClinVar CLNSIG P, LP and conflicting annotations slightly
- [x] Increased visibility of variant callers's "Pass" or "Filtered" on the following pages: SNV variants (cancer cases), SV variants (both RD and cancer cases)
- [x] Names on IGV buttons, including an overview level IGV MT button
- [x] Cases query no longer accepts strings for the `name_query` parameter, only ImmutableMultiDict (form data)
- [x] Refactor the loading of PanelApp panels to use the maintained API - Customised PanelApp GREEN panels
- [x] Better layout for Consequence cell on cancer SNVs page
- [x] Merged Qual and Callers cell on cancer SNVs page
### Fixed
- [x] Empty custom_images dicts in case load config do not crash
- [x] Tracks missing alignment files are skipped on generating IGV views
- [x] ClinVar form to accept MedGen phenotypes
- [x] Cancer SV variantS page spinner on variant export
- [x] STRs variants export
- [x] ClinVar submission enquiry status for all submissions after the latest
- [x] Typing error when running commands using python 3.9
- [x] Refactored and fixed the function creating alignment files (scout.utils.case_append_alignments)
- [x] Fix missing "Repeat locus" info on STRs export

**Review:**
- [x] code approved by DN
- [x] tests executed by DNIL, CR

### CODE REVIEW

**Comment by dnil** [comment]
Great! We should get a hasta release out asap for the cat 8 issue. We may be in a decent position to get #4976 and #4985 in here as well - Ill have a look.

**Comment by northwestwitch** [comment]
Database update (all tables) - Hasta stage:

# Stage updates

## Download files for updating

scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml download everything --api-key blablabla



## Update HPO terms 

scout  --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update hpo --hpoterms hpo.obo --hpo-to-genes phenotype_to_genes.txt



# Updating diseases

scout  --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update diseases -f .



## Updating genes

scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update genes -f .



## Update the OMIM AUTO panel

scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update omim --institute cust002 --genemap2 genemap2.txt --mim2genes mim2genes.txt



## Update the PanelApp green genes panel

scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update panelapp-green -i cust002 --force

**Comment by dnil** [comment]
✅ The issue https://github.com/Clinical-Genomics/scout/issues/4789 is indeed fixed by IGV 3.0.9:
Screenshot 2024-11-20 at 10 24 39

**Comment by dnil** [comment]
✅ Caller AF is now prioritised on a previously problematic balasamic variant, with AD values way off:
Screenshot 2024-11-20 at 11 15 55

**Comment by dnil** [comment]
✅ Same count of ClinVar hits with latest prod version (4.90.1) compared to PR, indicating that the simplified clinvar pathogenic check is ok.
Screenshot 2024-11-20 at 12 53 14
Screenshot 2024-11-20 at 11 25 18

**Comment by dnil** [comment]
✅ STR TRID export
Screenshot 2024-11-20 at 13 21 50

**Review by dnil — APPROVED** [review]
I think we are good to go!

**Comment by northwestwitch** [comment]
# Prod updates 

## Update HPO terms
scout  update hpo --hpoterms hpo.obo --hpo-to-genes phenotype_to_genes.txt


## Updating diseases
scout update diseases -f .


## Updating genes
scout update genes -f .


## Update the OMIM-AUTO panel
scout update omim --institute cust002 --genemap2 genemap2.txt --mim2genes mim2genes.txt


## Update the PanelApp green genes panel

scout update panelapp-green -i cust002 --force

**Comment by northwestwitch** [comment]
Deployed on hasta prod:

image

**Comment by dnil** [comment]
Deployed on `cg-services-prod`:
Screenshot 2024-11-21 at 17 23 58

**Pull request merged**
