### PR TITLE
Release v4.31

### PR DESCRIPTION
**Pull request by dnil**
This PR marks a new Scout release. We apply semantic versioning. This is a minor release. The interfaces are unchanged, new features have been added and bugs have been fixed.

### Added
- gnomAD annotation field in admin guide
- Export also dynamic panel genes not associated to an HPO term when downloading the HPO panel
- Primary HGNC transcript info in variant export files
- Show variant quality (QUAL field from vcf) in the variant summary
- Load/update PDF gene fusion reports (clinical and research) generated with Arriba
- Support new MANE annotations from VEP (both MANE Select and MANE Plus Clinical)
- Display on case activity the event of a user resetting all dismissed variants
- Support gnomAD population frequencies for mitochondrial variants
- Anchor links in Casedata ClinVar panels to redirect after renaming individuals
### Fixed
- Replace old docs link www.clinicalgenomics.se/scout with new https://clinical-genomics.github.io/scout
- Page formatting issues whenever case and variant comments contain extremely long strings with no spaces
- Chromograph images can be one column and have scrollbar. Removed legacy code.
- Column labels for ClinVar case submission
- Page crashing looking for LoqusDB observation when variant doesn't exist
- Missing inheritance models and custom inheritance models on newly created gene panels
- Accept only numbers in managed variants filter as position and end coordinates
- SNP id format and links in Variant page, ClinVar submission form and general report
- Case groups tooltip triggered only when mouse is on the panel header
### Changed
- A more compact case groups panel
- Added landscape orientation CSS style to cancer coverage and QC demo report
- Improve user documentation to create and save new gene panels
- Removed option to use space as separator when uploading gene panels
- Separating the columns of standard and custom inheritance models in gene panels
- Improved ClinVar instructions for users using non-English Excel

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
The usual checklist:

## [4.31]
### Added
- [ ] gnomAD annotation field in admin guide
- [ ] Export also dynamic panel genes not associated to an HPO term when downloading the HPO panel
- [ ] Primary HGNC transcript info in variant export files
- [ ] Show variant quality (QUAL field from vcf) in the variant summary
- [ ] Load/update PDF gene fusion reports (clinical and research) generated with Arriba
- [ ] Support new MANE annotations from VEP (both MANE Select and MANE Plus Clinical)
- [ ] Display on case activity the event of a user resetting all dismissed variants
- [ ] Support gnomAD population frequencies for mitochondrial variants
- [ ] Anchor links in Casedata ClinVar panels to redirect after renaming individuals
### Fixed
- [ ] Replace old docs link www.clinicalgenomics.se/scout with new https://clinical-genomics.github.io/scout
- [ ] Page formatting issues whenever case and variant comments contain extremely long strings with no spaces
- [ ] Chromograph images can be one column and have scrollbar. Removed legacy code.
- [ ] Column labels for ClinVar case submission
- [ ] Page crashing looking for LoqusDB observation when variant doesn't exist
- [ ] Missing inheritance models and custom inheritance models on newly created gene panels
- [ ] Accept only numbers in managed variants filter as position and end coordinates
- [ ] SNP id format and links in Variant page, ClinVar submission form and general report
### Changed
- [ ] A more compact case groups panel
- [ ] Added landscape orientation CSS style to cancer coverage and QC demo report
- [ ] Improve user documentation to create and save new gene panels
- [ ] Removed option to use space as separator when uploading gene panels
- [ ] Separating the columns of standard and custom inheritance models in gene panels
- [ ] Improved ClinVar instructions for users using non-English Excel

**Comment by northwestwitch** [comment]
This branch is on clinical-db stage now

**Comment by northwestwitch** [comment]
How is the situation in current master regarding the MT gnomAD frequency for genome build 37? Always None? Tested a few and looks like it. Both the values parsed from the VCF and the link. 
While there isn't much to do for the values parsed from the VCF, especially because we are all moving to build 38 anyway, the link to gnomAD can be adjusted to use gnomAD version 3.11 regardless of the genome build, right? Perhaps in another pull request?

**Comment by dnil** [comment]
> How is the situation in current master regarding the MT gnomAD frequency for genome build 37? Always None? Tested a few and looks like it. Both the values parsed from the VCF and the link.
> While there isn't much to do for the values parsed from the VCF, especially because we are all moving to build 38 anyway, the link to gnomAD can be adjusted to use gnomAD version 3.11 regardless of the genome build, right? Perhaps in another pull request?

That sounds right to me; perhaps we double check that with HS & AJ before changing so we are very sure the links are correct, and document that so no-one else goes 37 with some old MT build and gets the wrong position. But there is no need to keep them for 37: 

```
$ zgrep MT /home/proj/production/rare-disease/references/references_9.0/grch37_gnomad_reformated_-r2.1.1-.vcf.gz
$ 
```
and 
Screenshot 2021-03-25 at 15 09 35

**Comment by northwestwitch** [comment]
> > How is the situation in current master regarding the MT gnomAD frequency for genome build 37? Always None? Tested a few and looks like it. Both the values parsed from the VCF and the link.
> > While there isn't much to do for the values parsed from the VCF, especially because we are all moving to build 38 anyway, the link to gnomAD can be adjusted to use gnomAD version 3.11 regardless of the genome build, right? Perhaps in another pull request?
> 
> That sounds right to me; perhaps we double check that with HS & AJ before changing so we are very sure the links are correct, and document that so no-one else goes 37 with some old MT build and gets the wrong position. But there is no need to keep them for 37:
> 
> ```
> $ zgrep MT /home/proj/production/rare-disease/references/references_9.0/grch37_gnomad_reformated_-r2.1.1-.vcf.gz
> $ 
> ```
> 
> and
> Screenshot 2021-03-25 at 15 09 35

Moving this to a dedicated issue!

**Review by northwestwitch — APPROVED** [review]

**Pull request merged**
