### PR TITLE
Patch version 4.72.1

### PR DESCRIPTION
**Pull request by northwestwitch**
### Fixed
- [x] Jinja filter that renders long integers
- [x] Case cache when looking for causatives in other cases causing the server to hang

**Review:**
- [x] code approved by DN
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Tested on stage, this branch:

image


Main branch:

image

**Comment by dnil** [comment]
> Tested on stage, this branch:
> 
> image
> Main branch:
> 
> image

Those spaced-number columns are a bit overfull and not really readable - we should really fix it or revert!

**Comment by vwirta** [comment]
> > Tested on stage, this branch:
> > image
> > Main branch:
> > image
> 
> Those spaced-number columns are a bit overfull and not really readable - we should really fix it or revert!

what about adding a comma sign?

**Comment by dnil** [comment]
> > > Tested on stage, this branch:
> > > image
> > > Main branch:
> > > image
> > 
> > 
> > Those spaced-number columns are a bit overfull and not really readable - we should really fix it or revert!
> 
> what about adding a comma sign?

Was that passive agressive Valtteri, or in good faith? Ill bite a little.. Commas, apostrophes or multiplication signs in numbers are really weird things and frowned upon by IUPAC, IBWM etc. See e.g. https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping for a starting discussion. 😁

**Comment by dnil** [comment]
> Commas or dots on the other hand would solve the issue of the numbers being displayed on different lines..

And having no space, let alone no comma or other number format disrupting symbol in there would also solve that one, while being shorter and easier to read.

**Comment by northwestwitch** [comment]
> and easier to read.

Not easier to read for me,. but shorter, yes!

**Review by dnil — APPROVED** [review]
We still need to fix those spaces-in-numbers, but lets go with this once we have the patch in.

**Pull request merged**
