### PR TITLE
Szilvas' Cancer SVs

### PR DESCRIPTION
**Pull request by dnil**
**This PR adds a functionality - Cancer SVs!**

Thank you @szilvajuhos! This is Good Stuff that we should try to get into the base repo. We should add some tests and unify the views a little bit before merging, but you've done a really Good Thing already!

How to test:

1. Load a manta cancer SV track
1. Note that a cancer sv button appears on the case
1. Look, click and filter through functionality on the variants and variant pages for the cancer_sv to see that all is working as far as can be expected from current annotation status.
1. Compare to other variants forms and note any glaring functionality differences

One immediate thing is the addition of a test file, ideally from the previously existing test case, but anything fit for the public domain is fine really. @moonso is this something we have / can produce with small effort? I'm guessing the current bams are not complete enough that I could just fire up manta on and get something meaningful? Otherwise I'm sure @hassanfa or @szilvajuhos have test cases that we could use.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by CR, Travis CI

### CODE REVIEW

**Comment by hassanfa** [comment]
I do have bunch of Manta files and I'd be happy to test this new functionality. With Scout-stage a bit fragile, let me know when this branch is around and I will try to upload a case asap.

**Comment by hassanfa** [comment]
Or even better, I'll try it on my local instance. I'll keep you posted.

**Comment by szilvajuhos** [comment]
Thank you indeed pulling my changes, seems the merge was not perfect on the airport :S Whatever, just re-installed scout and cleaning up stuff.

**Comment by northwestwitch** [comment]
Same for this one, we should do a final review and merge it as soon as it is ready!

**Comment by dnil** [comment]
Ping @szilvajuhos and @hassanfa: any Manta-SV data around that could be used for testing - or reports that it has been tested to good effect? Ideally I'd have @moonso look at the merge: it looks to me like there is an issue with the variants / variant controller split here?

**Comment by hassanfa** [comment]
Sorry about the delay. Working on it right now.

**Comment by hassanfa** [comment]
I tried uploading, but can't find the clinical SV button. @szilvajuhos Do you have a screenshot of what it should look like?

**Comment by moonso** [comment]
@dnil would you like to be responsible for getting this merged before black? It is highly requested from what I've heard

**Comment by northwestwitch** [comment]
Guys I can take a look at this PR, so we merge it in the next release. Could  anyone share with me a manta sv file, (also minified) so I can test with that?

**Comment by moonso** [comment]
Sounds good @northwestwitch ! The Sv-file that are included in rare disease uses Manta so it should be possible to reuse. Perhaps duplicate it and rename the sample columns

**Comment by northwestwitch** [comment]
I think that the PR is workable now. SV variants show and look parsed correctly. The problem is that test coverage goes down quite a lot, so I'll add some tests!

**Comment by northwestwitch** [comment]
Ok, I've just realized that the code for sv_variants and cancer_sv variants as well as the templates are very redundant. I need to work on this a bit more

**Comment by dnil** [comment]
Great! Wouldn't it be good to capture and display these:
Screenshot 2020-01-22 at 07 56 25

**Comment by northwestwitch** [comment]
I'm trying to parse a manta output file from @hassanfa to use it as a test file in this PR but this file doesn't have the GT fields for any of the variants (it's also missing in the header). Of course the parsing fails. Question: is GT fields meaningful for the the cancer SVs or Scout should adapt for SVs without GT or @hassanfa should start to enforce the GT fields in his outfiles?? Good thing is that his VCFs contain SOMATIC AND SOMATICSCORE fields, but only when the analysis has paired normal and tumor (they're missing in the outfiles of the tumor-only analyses).

Suggestions?

**Comment by moonso** [comment]
I think we should adopt scout to handle files without GT calls. Let me know if you need some help or input on that

**Comment by northwestwitch** [comment]
> I think we should adopt scout to handle files without GT calls. Let me know if you need some help or input on that

OK..! Then I need some more time to fix this PR. Thanks @moonso, I'll let you know if I need help!

**Comment by northwestwitch** [comment]
Fixed the missing GT field. Loading of the VCF file from @hassanfa now works. The result is a bit rustic, with a "None" field in SV variant pages. But I guess it's fine from now, given the fact that this is the SV variant page that we are borrowing and not a dedicated Cancer SV variant page (which we should create in the future)  
image

**Comment by northwestwitch** [comment]
I think I'm done with this PR!

The parsing and collecting values from the VCF part was working well already (good job @szilvajuhos !!). I've modified the web-interface related code to make it more slim and reuse functions for the sv_variants page, but maintaining svs and cancer_svs pages separate.

I've included tests for the variant parsing and loading. Coverage went up. 
It's also collecting the SOMATICSCORE values (when available), but they're not yet displayed because a dedicated cancer_sv_variant page is missing.

I've tested it and looks like it's working, but could anyone give it another try, with another vcf file possibly? Thanks!

**Comment by moonso** [comment]
Nice @northwestwitch !! I think we should merge. It is not as critical since this is completely new functionality

**Comment by northwestwitch** [comment]
Ok! 👍

**Pull request merged**
