### PR TITLE
Tentatively Fix #1237

### LINKED ISSUE #1237: SV Research view on semi-old case
500 Internal server error on a semi-old SV case this morning:
https://scout.scilifelab.se/cust002/F0005034/sv/variants
Anyone with log access that can shed some light on this? :-)

### PR DESCRIPTION
**Pull request by dnil**
This is from this morning: only adressess the error, not underlying causes.

### CODE REVIEW

**Comment by northwestwitch** [comment]
I think we should understand and fix what is causing this error as well. 
I've just tried to load the research variants fo the test case on my local computer. (scout --demo load research -c internal_id -i cust000 -f).

It works and loads 3 variants. If you go to the SV research variants page they're displayed but the link for just one of them works...

**Comment by dnil** [comment]
Feel free: I won't have time until possibly late afternoon!

**Comment by northwestwitch** [comment]
For testing purposes there is a case in stage which has the same issue: https://scout-stage.scilifelab.se/cust000/15078-miptest/sv/variants?variant_type=research

When this works we'll know that the bugfix will work also on prod!

**Comment by northwestwitch** [comment]
Hi, I still don't have access to clinical-db. Waiting for IT to fix it!

**Comment by northwestwitch** [comment]
As soon as I figure out how to install stuff on clinical-db I'm going to install this branch on stage (https://github.com/Clinical-Genomics/servers/issues/146)

**Comment by northwestwitch** [comment]
This branch is on stage. Please disregard what I wrote above and do **NOT** use https://scout-stage.scilifelab.se/cust000/15078-miptest/sv/variants?variant_type=research to test this PR because the sample has a problem which is not the same as #1237.

The error from stage.scilifelab.se/cust000/15078-miptest/sv/variants?variant_type=research is actually the following:
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 17, in decorated_function
    context = f(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/variants/views.py", line 227, in sv_variants
    if panel['is_default']:
KeyError: 'is_default'

That is an error that should also be fixed!

**Comment by northwestwitch** [comment]
This branch is now on stage on clinical-db

**Comment by northwestwitch** [comment]
Fixed #1261 and the bug affecting SV page when a structural variant is encompassing a gene with no 'common' key. This happens to 2 of the 3 research variants of the demo case (after you run the command :  scout --demo load research -c internal_id -i cust000 -f)

**Comment by northwestwitch** [comment]
This PR fixes 3 bugs affecting the visualization of SV variants.

### 1. Bug 1: pages for variants with no gene.common fields crash.

**How to test**:
1. On local computer run: scout --demo load research -c internal_id -i cust000 -f
1. On local installation of Scout: Filter for SV variants and you'll see 3 variants. 

**Expected outcome**:
The links to their pages should work and variant page should be displayed correctly.

### 2. Bug 2: Key error on panel['is_default']

**How to test**:
1. On scout-stage go to this page: https://scout-stage.scilifelab.se/cust000/15078-miptest/sv/variants?variant_type=research

**Expected outcome**:
Page works

### 3. Bug 3: variant.region_annotations key is missing (#1237)

**How to test**:
On scout stage open sample F0001963 (cust002) ---> https://scout-stage.scilifelab.se/cust002/F0001963
Open research SVs page for this sample (should work) and filter for research SV on chromosome 21

**Expected outcome**:
Filter should return a list of variants with chrom=21

**Review:**
- [ ] code approved by
- [ ] tests executed by

**Comment by northwestwitch** [comment]
@dnil I've included the code to fix another couple of bugs to this PR. Give it a try when you have time.
Scout stage is still affected by bugs (current master is installed there) so you can test before and after. Let me know if (and when) to install this branch on stage!

**Pull request merged**
