### PR TITLE
Fix publish docs include

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

Screenshot 2021-04-26 at 10 10 13

**How to test**:
1. simply wait for next release? 

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Review by northwestwitch — APPROVED** [review]
👍 

Now we'll have to wait for next release to see if it works. But let's push the docs manually in the meanwhile.

**Comment by dnil** [comment]
> Now we'll have to wait for next release to see if it works. But let's push the docs manually in the meanwhile.

Yes, done!

**Comment by dnil** [comment]
We'll just have to wait for Coveralls to get back online again?

**Comment by northwestwitch** [comment]
> We'll just have to wait for Coveralls to get back online again?

yes

**Comment by dnil** [comment]
Tested by deploying:
Screenshot 2021-04-27 at 14 37 19

**Pull request merged**
