### PR TITLE
Fix #4436 - update GitHub Actions

### LINKED ISSUE #4436: Outdated actions
Time to increment..
Screenshot 2024-02-19 at 10 57 19

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

- Fix #4436 - naively update versions. Let's see if something more needs changing. 😊 

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by GitHub Actions

### CODE REVIEW

**Comment by dnil** [comment]
Ok, that resolved most node 20 warnings, and without error. There are still two actions, Ana06/get-changed-files and samuelmeuli/wearerequired/lint-action that appear to use an old version. I guess we give them a little time to update, and if they appear abandoned we can always switch to similar actions.

**Comment by dnil** [comment]
Ah, no, wait - the codecov one failed!

[coverage](https://github.com/Clinical-Genomics/scout/actions/runs/7958007238/job/21722253422#step:7:34)
Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1

**Comment by northwestwitch** [comment]
> In the end we didn't need the Dependabot path; explicitly adding the path to our codecov token secret was enough. Apparently the default is gone/changed - or we simply used the tokenless upload before? Who knows! 😁

It happened the same to me in in another repo (don't remember which one!)

**Review by northwestwitch — APPROVED** [review]
💯

**Pull request merged**
