### PR TITLE
Add Gene Name/ID in Scout Cancer View

### PR DESCRIPTION
**Pull request by mikaell**
Add gene name or id in Scout's cancer view in the table entry
'Gene:Transcript:Exon:HGVS'.

This commit also changes the table column name from
"Variant:Transcript:Exon:HGVS" to "Gene:Transcript:Exon:HGVS".

---
Reference: QoL changes to Variant list view for cancer cases #1629

This PR adds a functionality or fixes a bug.

**How to test**:
1. how to install it

Pull and install Scout as usual.

1. how to test it, possibly with real cases/data

* Go to the cancer variants view.

**Expected outcome**:

* "Variant:Transcript:Exon:HGVS"-Header should be replaced by "Gene:Transcript:Exon:HGVS".
* Gene name or id should be a part of the value in the  "Gene:Transcript:Exon:HGVS"-column.

Screenshot 2020-03-11 at 10 17 47

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "merge and deploy" approved by

### CODE REVIEW

**Comment by hassanfa** [comment]
@northwestwitch @moonso What do you think about this? Yay or Nay?

**Comment by dnil** [comment]
@hassanfa a good general procedure is to pull this to clinical-db scout-stage (or a fully populated local instance if needed). There you should presumably also see gene_symbols in all their glory. 😸

**Comment by hassanfa** [comment]
> @hassanfa a good general procedure is to pull this to clinical-db scout-stage (or a fully populated local instance if needed). There you should presumably also see gene_symbols in all their glory. 😸

It is like that in stage. Gene_symbol is not showing when it is only one gene: 
image

But when there are two genes, it shows up:

image

I think @mikaell doesn't have the gene_id to gene_symbol in his local DB.

**Comment by dnil** [comment]
Precisely! But if you now update scout-stage to @mikaells branch (this) it should now show up, giving a good indication that it works - and you can tick that tested checkbox in the process! ✅ 😄

**Comment by hassanfa** [comment]
aha! ok! 😁 Slow morning for me. I'm on it!

**Comment by dnil** [comment]
Sorry for being obscure! It is not like it absolutely *needs* testing: I guess your question was more about wether it was needed when the gene symbol is anyway visible two columns away.

**Comment by hassanfa** [comment]
You were clear, I was just slow in understanding. Good point. If we'd to follow the nomenclature used in TCGA and/or mycancergenome, we need to change it a bit further. E.g. columns are: chr7:g.140753336A>T BRAF V600E

If we'd to follow HGVSc or HGVSg, then it would be transcript:mut (ENS123123:c.123C>T) or chr:gdnamut (1:g.12356C>T).

I think we wanted to have duplicate gene info in Variant ID column so it is unified across all. 

Should we alter this further to match the commonly used ones (tcga, cosmic, cbioportal, mycancergenome, etc)? I think Scout should have it as close possible to common way of showing variants as possible.

**Comment by mikaell** [comment]
> I think it looks good. Maybe also update the CHANGELOG?

Done!

**Comment by mikaell** [comment]
> Precisely! But if you now update scout-stage to @mikaells branch (this) it should now show up, giving a good indication that it works - and you can tick that tested checkbox in the process! ✅ 😄

Maybe I should start testing some stuff on stage :) I'll drop by Friday afternoon, if someone has time to show me the routines.

**Comment by northwestwitch** [comment]
Please don't merge this before we merge #1787 (almost done with the latter!)

**Comment by northwestwitch** [comment]
> Please don't merge this before we merge #1787 (almost done with the latter!)

Done!

**Pull request merged**
