### PR TITLE
Add omim inheritancemodel

### PR DESCRIPTION
**Pull request by moonso**
Fetch "Digenic recessive" from OMIM and show as `DR` wherever applicable

### CODE REVIEW

**Comment by northwestwitch** [comment]
I think the official OMIM term for digenic inheritance is "DR"

**Comment by northwestwitch** [comment]
Sorry I wanted to review it but I messed up, reopened now!

**Comment by moonso** [comment]
Just made a spelling mistake on the PR. In scout it shows as DR

**Comment by northwestwitch** [comment]
Yeah. That's the official nomenclature

**Pull request merged**
