### PR TITLE
Skip loading when there are no variants. Fix #1158

### LINKED ISSUE #1158: Do not crash when importing variants from an empty VCF file

### PR DESCRIPTION
**Pull request by moonso**

### CODE REVIEW

**Comment by northwestwitch** [comment]
@dnil if you have time review this one first, because it's needed in production!

**Comment by dnil** [comment]
Looks good! Wouldn't it be  possible to add a test as well here? I find it ideal to have such old-bug-tests around making sure a bug can never pop back in again.

**Comment by moonso** [comment]
I'm working on it!

**Comment by northwestwitch** [comment]
> Looks good! Wouldn't it be possible to add a test as well here? I find it ideal to have such old-bug-tests around making sure a bug can never pop back in again.

You kno

**Comment by dnil** [comment]
I made a header only file for testing; could upload that, but I kind of guess you already did the same, but even closer to the original problem? 😄

**Comment by dnil** [comment]
> You know that you don't have tests on yours? ;)

The irony hasn't escaped me. But mine is an graphical interface oriented feature one.. ;-)

**Comment by moonso** [comment]
Tests added 🌟

**Pull request merged**
