### PR TITLE
Ucsc-hg38-sv-view

### PR DESCRIPTION
**Pull request by ViktorHy**
This PR adds a functionality or fixes a bug.
OR
This PR marks a new Scout release. We apply semantic versioning. This is a major/minor/patch release for reasons.

**How to test**:
1. Open data loaded with different genome-builds hg19 or hg38

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

links are working for both hg19 and hg38 depending on genome-build loaded per sample

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by moonso** [comment]
Sure, think I know how to fix that. Give me a minute

**Comment by moonso** [comment]
Tests are running now!

**Comment by dnil** [comment]
Just waiting to see how coveralls handles this.. 😆

**Comment by moonso** [comment]
Hi @ViktorHy , I added you as a contributor so that you can push directly to this repo if you like.  In hope that we will work against and deploy the same version of Scout at some point

**Comment by moonso** [comment]
Ok there are some other things I need to modify. I'll get back

**Comment by moonso** [comment]
These problems will be solved by #1927

**Comment by moonso** [comment]
@ViktorHy could you either 

1. close this and open the same PR directly in this repo since you are now a collaborator
or 
1. Fetch latest version of master and merge into your PR

**Comment by ViktorHy** [comment]
Ok closing.

**Pull request closed without merging**
