### PR TITLE
Adding varsome button

### PR DESCRIPTION
**Pull request by ninanorgren**
This PR adds a Varsome button for transcript and build specific variants

**Expected outcome**:
Opens a link to Varsome with the variant in question

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by dnil** [comment]
Nice and clean history now! Thank you @ninanorgren!

**Comment by northwestwitch** [comment]
Thanks @ninanorgren, I'll review and get back back to you after lunch. 

@moonso It would be easier if she could become also a collaborator so she'll be able to open pull requests directly in out repo. For instance now the current master was updated and this pull request became outdated but I can't either update or make changes to it from here. I can't even merge it whenever it's approved..

**Comment by dnil** [comment]
Agreed! I was about try it via the command line instead. Alas, I should have assigned, and will also go have lunch and let you finish it C. Two small things I noticed while starting a review an testing: 

- In scout/server/blueprints/variant/utils.py, a ´genome_build(str)' is missing from the `update_transcripts_information(` doctstring. 
 - the class of the new links td needs an update: a weird additional internal boundary outline is rendered in the cells as is now

**Comment by moonso** [comment]
@ninanorgren is added as collaborator

**Comment by northwestwitch** [comment]
Hi again @ninanorgren. From now on opening PRs to scout should be easier! If you fix this one starting from our master we can help you keeping it alive and fix eventual problems!

**Comment by northwestwitch** [comment]
Because now it looks like this for us and we can't really interact with the branch:

image

**Comment by ninanorgren** [comment]
Okay, so should I do a new branch from your repo than and submit a new PR instead of this one?

**Comment by dnil** [comment]
I think we can just cherry-pick these for you in a new branch if you want, so you dont have to do it again.. Hold on..

**Comment by dnil** [comment]
Ok, now exists as #1862. As you are a collaborator you should be able to edit that one as well, correct?

**Comment by northwestwitch** [comment]
> Okay, so should I do a new branch from your repo than and submit a new PR instead of this one?

You could try to fix this by rebasing with our current master, but there is something weird about this PR, because for instance your other dockerize PR can be kept up to date every time we merge something on the code, this one can't. And it looks like part of your code is stuck in a situation we had several commits ago (some days ago), when the tests didn't complete (they're all yellow indefinitely). This is fixed in our current master.

**Comment by northwestwitch** [comment]
Ah ok, @dnil fixed it!

**Comment by dnil** [comment]
Sorry about the hassle @ninanorgren: don't be discouraged, it will be a lot easier next time. I'm closing this as well now to lessen the confusion, and we can continue this in #1862.. Three is a charm I guess.. 😅

**Pull request closed without merging**
