### PR TITLE
Load STRs regardless of rank score threshold

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

**How to test**:
1. try loading an STR file produced with Stranger 0.7 and note how few variants are loaded if rank score threshold is at 5 or higher
2. try with patch version and find variants loaded

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Review by northwestwitch — APPROVED** [review]
I think this is fine to regardless of us doing an hotflix or a normal release tomorrow. I'd probably go for a hotfix.

**Comment by northwestwitch** [comment]
What I would do: rebase this on on scout 4.29 and go for an hotfix. I don't feel very comfortable about making a Friday release and then leaving for a week holiday..

**Comment by northwestwitch** [comment]
We can merge this one right @dnil ?

**Comment by dnil** [comment]
It is fine in the sense that it is working on local. I still have not seen the hot fix working (stage issues?) so there could be more..

**Comment by dnil** [comment]
Ok on hasta stage now - see hotfix branch. So let's merge this one, and deploy the hotfix.

**Pull request merged**
