### PR TITLE
Update case.py

### LINKED ISSUE #1221: Problem uploading delivery report to scout in production (works on stage)
cg upload delivery-report-to-scout acase
----------------- UPLOAD ----------------------
.../P_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py:2334: SAWarning: Pathed join target File.version has already been joined to; skipping
  "been joined to; skipping" % prop
uploading delivery report /.../delivery-report.html to scout for case: acase
Fetching case acase
Saving report for case acase in database
Saving case acase
Traceback (most recent call last):
  File ".../P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File ".../P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File ".../python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File ".../python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File ".../python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File ".../python3.7/site-packages/cg/cli/upload.py", line 205, in delivery_report_to_scout
    _add_delivery_report_to_scout(context, report, case_id)
  File ".../python3.7/site-packages/cg/cli/upload.py", line 165, in _add_delivery_report_to_scout
    scout_api.upload_delivery_report(path, case_id, update=True)
  File ".../python3.7/site-packages/cg/apps/scoutapi.py", line 96, in upload_delivery_report
    update=update)
  File ".../python3.7/site-packages/scout/load/report.py", line 48, in load_delivery_report
    return adapter.replace_case(case_obj)
  File ".../python3.7/site-packages/scout/adapter/mongo/case.py", line 440, in replace_case
    return_document=pymongo.ReturnDocument.AFTER
  File ".../python3.7/site-packages/pymongo/collection.py", line 2789, in find_one_and_replace
    session=session, **kwargs)
  File "...ython3.7/site-packages/pymongo/collection.py", line 2652, in __find_and_modify
    acknowledged, _find_and_modify, session)
  File "...ython3.7/site-packages/pymongo/mongo_client.py", line 1102, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "...b/python3.7/site-packages/pymongo/mongo_client.py", line 1079, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/...python3.7/site-packages/pymongo/collection.py", line 2647, in _find_and_modify
    retryable_write=retryable_write)
  File "...python3.7/site-packages/pymongo/collection.py", line 245, in _command
    retryable_write=retryable_write)
  File "/...python3.7/site-packages/pymongo/pool.py", line 517, in command
    collation=collation)
  File ".../python3.7/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "...python3.7/site-packages/pymongo/helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: cannot index parallel arrays [updated_at] [collaborators]

### PR DESCRIPTION
**Pull request by dnil**
Fix #1221 - I believe. Thanks @patrikgrenfeldt for explaining what you are doing - that made the location obvious. In a twist of irony it appears it was your code.. 😉

### CODE REVIEW

**Comment by dnil** [comment]
Happy if someone (@patrikgrenfeldt?) can test this on stage, preferably on stage with actual new delivery upload procedure!

**Comment by northwestwitch** [comment]
I'm wondering of we should revert to before #1219, because after this fix we won't have cases with array values for updated_at

**Comment by patrikgrenfeldt** [comment]
Good catch @dnil, I didn't know a comma could turn a value assignment into
an array assignment, awesome! I'll test this as soon as possible

Den ons 1 maj 2019 07:36Chiara Rasi <notifications@github.com> skrev:

**Comment by dnil** [comment]
> I'm wondering of we should revert to before #1219, because after this fix we won't have cases with array values for updated_at

Still there are a couple of cases in the.db now: we should at least keep #1219 until those arrays have been flattened!

**Comment by patrikgrenfeldt** [comment]
If you did put #1219 in production I think some cases might have been affected otherwise I'd guess the index issue prevented any changes. I haven't seen any signs of successful uploads in the logs.

**Comment by patrikgrenfeldt** [comment]
Can I trust that stage with the fix behaves the way that production will behave with the fix?

**Comment by northwestwitch** [comment]
> Can I trust that stage with the fix behaves the way that production will behave with the fix?

I think so, if it doesn't we will fix it. The delivery report upload is not working in production anyway.

**Pull request merged**
