### PR TITLE
Adds functionality to load PanelApp genes

### LINKED ISSUE #784: PanelApp again
It's panel update season again, and we are doing a lot of comparing to PanelApp. It is maturing well, and may be time to add import to Scout. We tentatively think "level 3" aggregation is a good panel level, and important to be able to pull only "Green" reviewed gene symbols.

API instructions available [here](https://panelapp.genomicsengland.co.uk/#!Webservices).

### PR DESCRIPTION
**Pull request by moonso**
Fix #784

### CODE REVIEW

**Comment by moonso** [comment]
Not ready but feel free to test `scout load panel --panel-app` 🛩

**Comment by dnil** [comment]
Ooooh! This is good stuff indeed!

**Comment by dnil** [comment]
Ok, I've tested! Great start! I think it is already very useful. Updates seem possible, trusting PanelApp versioning, right?

Therese a lot of panels obviously. To make it effective, we shall need to be able to group panels since many of these are more specific than would be practical with the level of detail we typically get on a referral.

Perhaps the best path is to reintroduce a panel-group, where a panel(-group) could consist not only of gene symbols, but also of references to other panels? This will also help us with adding some coarse-grained structure to e.g. the neuromuscular disorders where as you may recall with some pain contained some 16 different sub panels at one point.

It may also be practical to mirror some of the PanelApp hierarchy as well, e.g. introducing a "parent" for panels. It could be just descriptive for starters, keeping the levels readable in scout, making it easier to pick the right ones to add?

**Comment by moonso** [comment]
Ok I'm gonna merge this for now and then we can elaborate on improvements later

**Pull request merged**
