### PR TITLE
Podman systemd

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality: Scout by Podman / systemd

I was missing this today: this looked so nice, don't really see why we shouldn't put it on the main repo as well. I guess you guys didn't do too much perl, but remember the the core design features: "there is more than one way to do it" along with the core virtues: laziness, impatience and hubris. 😸 

It needs a bit of updating, both just for master-version, but also some slight collisions with kubernetes and Docker alternatives, right?

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Oh no, it has 1000000 conflicts! Tomorrow I can try to isolate the PR-specific code and create a clean PR out of it

**Comment by dnil** [comment]
> Oh no, it has 1000000 conflicts! Tomorrow I can try to isolate the PR-specific code and create a clean PR out of it

Thank you, that would be great - otw just bump it over to @eriksjolund or me. I don't have a great linux playground running at home (hm, actually a raspberry pi..), but I have dev boxes at SciLifeLab and the hospital where I could test again when its time.

**Comment by eriksjolund** [comment]
This branch 
https://github.com/Clinical-Genomics/scout/tree/systemd_services_podman
only added files into the new directory _./systemd_ 
I would guess that it does not have any merge conflicts.

Regarding testing. One idea is to use systemd services in GitHub Actions:
See my minimal example here:
https://github.com/eriksjolund/user-systemd-service-actions-workflow



All references of  _docker.io/eriksjolund/scout:dockerhub_ should probably be changed to something else in the branch
https://github.com/Clinical-Genomics/scout/tree/systemd_services_podman

**Comment by eriksjolund** [comment]
I created this PR instead
https://github.com/Clinical-Genomics/scout/pull/2292

I created a new branch from master and then added the files I had written previously (with some small modifications).

**Comment by northwestwitch** [comment]
Closing this then!

**Pull request closed without merging**
