### PR TITLE
Version 4.89

### PR DESCRIPTION
**Pull request by dnil**
This PR marks a new Scout release. We apply semantic versioning. This is a minor release since it adds new features in a backwards compatible manner.

### Added
- [x] Button on SMN CN page to search variants within SMN1 and SMN2 genes
- [x] Options for selectively updating OMICS variants (fraser, outrider) on a case
- [x] Log users' activity to file by specifying `USERS_ACTIVITY_LOG_PATH` parameter in app config
- [x] `Mean MT coverage`, `Mean chrom 14 coverage` and `Estimated mtDNA copy number` on MT coverage file from chanjo2 if available
- [x] Subject id search from caseS page (supporting multiple sample types e.g.) - adding indexes to speed up caseS queries
- [x] Advanced cases search to narrow down results using more than one search parameter
- [x] Coverage report available for any case with samples containing d4 files, even if case has no associated gene panels
- [x] RNA delivery reports
### Changed
- [x] Documentation for OMICS variants and updating a case
- [x] Include both creation and deletion dates in gene panels pages
- [x] Moved code to collect MT copy number stats for the MT report to the chanjo extension
- [x] On the gene panelS page, show expanded gene panel version list in one column only
- [x] IGV.js WTS loci default to zoom to a region around a variant instead of whole gene
- [x] Refactored logging module
- [x] Case general report no longer shows ORPHA inheritance models. OMIM models are shown colored.
- [x] Chromosome alias tab files used in the igv.js browser, which now contain the alias for chromosome "M" - _Tested by collaborators_
- [x] Enable Gens CN button also for non-wgs cancer track cases
### Fixed
- [x] Broken heading anchors in the documentation (`admin-guide/login-system.md` and `admin-guide/setup-scout.md` files)
- [x] Avoid open login redirect attacks by always redirecting to cases page upon user login
- [x] Stricter check of ID of gene panels to prevent file downloading vulnerability
- [x] Removed link to the retired SPANR service. SPIDEX scores are still parsed and displayed if available from variant annotation.
- [x] Omics variant view test coverage
- [x] String pattern escape warnings
- [x] Code creating Alamut links for variant genes without canonical_transcript set
- [x] Variant delete button in ClinVar submissions page
- [x] Broken search cases by case similarity

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by CR
- [ ] tests executed by DN, CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Users monitoring is working fine:

image


We should actually change the settings of scout demo after the testing so it will stop writing on /tmp/tmp_scout_users_activity.log

**Comment by northwestwitch** [comment]
The alamut link fix also works. Checked using [this case](https://scout-stage.scilifelab.se/cust004/18701400006fam)

**Review by northwestwitch — APPROVED** [review]
I think we are good with this one! 👍🏻

**Comment by dnil** [comment]
Right, and the log file is disabled by default, and a servers issue for enabling, so we should be all good with this release.

I guess we will ideally want to start the log anyway during deploy to get a feel for how it's working? Do you have a PR on servers already perhaps, since you had the stage one? 😸 Otw no biggie, we can start it whenever later.

**Comment by northwestwitch** [comment]
> Do you have a PR on servers already perhaps, since you had the stage one? 😸 Otw no biggie, we can start it whenever later.

Yes. I closed it. We can reuse that I guess

**Pull request merged**
