### PR TITLE
Organize pages around each institute 

### LINKED ISSUE #1972: CLin Var submission
Cool with the editing possibility!
we have some suggestions. see slide below

[Suggestion 20-06-24.pptx](https://github.com/Clinical-Genomics/scout/files/4824996/Suggestion.20-06-24.pptx)

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR is basically only a portal restructuring without adding new functionalities. So don't worry about the files changed, it's mostly stuff moved from cases blueprints to institutes blueprint. The aim is to make it more user friendly. I was working on #1965 and then I realized that I didn't want to add yet another feature without finding it a proper space in the portal.

So I've wrapped up the following pages:
- cases
- causatives
- variant search (ex gene variants)
- users (small new page)
- clinvar submissions
- institute settings 

into one sidebar, and I've made it the landing page when you click on one institute:

image

In my vision also other pages should be moved there in the future, for instance gene panel creation, and a new page showing all cases that have been submitted to matchmaker (if scout is connected to it).

I think having the information this way is much more user friendly. Case and variants pages are left unchanged.

I've included fix #1972 since I was working on those pages.

**How to test**:
1. This PR might seem huge but it's just reshuffling the already existent pages. 
1. A reviewer should not focus much on the code (it's mostly all old functions) but on the general effect of having the app restructured in this way. And it would be nice to check that all the links and the pages work, of course!
1. Install the branch on scout stage and navigate around

**Expected outcome**:
Compare the PR against scout prod and see the changes and if they make sense.
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by MM
- [x] tests executed by MM, CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is done and ready for review. There are several other PRs open and ready as well but it would be great if this one could be addressed first, since it contains changes in many files and it will be potentially very complicated to maintain. Could you help with a review whenever you have time @mikaell or @moonso ?

**Comment by moonso** [comment]
I have a look now! Is it deployed on stage?

**Comment by northwestwitch** [comment]
Thank you @moonso! 🙏 Have an amazing summer as well!

**Comment by northwestwitch** [comment]
I've fixed the causatives issue and included a page scroll in most of the pages. Tested on stage and it looks OK now. Merging as soon as the tests pass!

**Pull request merged**
