### PR TITLE
Version 4.67 - Speedups and Clinical SV filter change

### PR DESCRIPTION
**Pull request by dnil**
This PR marks a new Scout release. We apply semantic versioning. This is a minor release, offering fixes and speedups to existing features, as well as some settings changes for clinical SV filtering.

Admins, note that after the patch, you will want to update your mongodb indices, in particular the `case` one. You can do this from the Scout CLI with:
`scout index --update -c case`

### Added
- [x] Prepare to filter local SV frequency
### Changed
- [x] Speed up instituteS page loading by refactoring cases/institutes query
- [x] Clinical Filter for SVs includes `splice_polypyrimidine_tract_variant` as a severe consequence
- [x] Clinical Filter for SVs includes local variant frequency freeze ("old") for filtering, starting at 30 counts
- [x] Speed up caseS page loading by adding status to index and refactoring totals count
release.
- [x] HPO file parsing is updated to reflect that HPO have changed a few downloadable file formats with their 230405 
### Fixed
- [x] Page crashing when a user tries to edit a comment that was removed
- [x] Warning instead of crashed page when attempting to retrieve a non-existent Phenopacket
- [x] Fixed StJude ProteinPaint gene link (URL change)
- [x] Huge list of genes in case report for megabases-long structural variants.
- [x] Fix displaying institutes without associated cases on institutes page
- [x] Fix default panel selection on SVs in cancer case report

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Ah yes, tests are failing in general, this is a bug

**Comment by northwestwitch** [comment]
Updating HPO terms:
- `scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update hpo --hpoterms hpo.obo --henes phenotype_to_genes.txt`

image


Updating diagnoses (OMIM):
- `scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update diseases -f .`

image

**Review by northwestwitch — APPROVED** [review]
💯

**Comment by northwestwitch** [comment]
Testing deployment and updating the database on Hasta stage:

- Deployment works fine:

image

- Downloading all the files necessary for updating the database works as well (`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml download everything --api-key xyz`):

image

- Testing updating the HPO (`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update hpo --hpoterms hpo.obo --hpo-to-genes phenotype_to_genes.txt`):

image

- Testing updating the OMIM diseases (`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update diseases -f .`):

image

- Testing updating genes (`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update genes -f .`):

image

- Update the OMIM-AUTO panel (`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update omim --institute cust002 --genemap2 genemap2.txt --mim2genes mim2genes.txt`):

image

- Update the PanelApp green genes panel (`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update panelapp-green -i cust002 --force`):

image

**Comment by northwestwitch** [comment]
- Deployed on Hasta prod:

image

- Updated the HPO terms (`scout update hpo --hpoterms hpo.obo --hpo-to-genes phenotype_to_genes.txt`):

image

- Updated the OMIM diseases (`scout update diseases -f .`):

image

- Updated genes (`scout update genes -f .`):

image

- Updated the OMIM-AUTO panel (`scout update omim --institute cust002 --genemap2 genemap2.txt --mim2genes mim2genes.txt`):

image


- Updated the PanelApp green genes panel (`scout update panelapp-green -i cust002 --force`):

image

**Comment by dnil** [comment]
Oh, and the case index 😅:
```
[daniel.nilsson@hasta:~] [P_base] $ scout index --update -c case
2023-05-05 15:37:09 hasta.scilifelab.se scout.commands.base[125942] INFO Running scout version 4.67
2023-05-05 15:37:09 hasta.scilifelab.se scout.commands.base[125942] DEBUG Debug logging enabled.
2023-05-05 15:37:09 hasta.scilifelab.se scout.commands.base[125942] WARNING Support for launching Scout using a .yaml config file is deprecated and will be removed in the next major release (5.0). Use a PYTHON (.py) config file instead.
2023-05-05 15:37:10 hasta.scilifelab.se scout.adapter.client[125942] INFO Connected to MongoDB 4.4.9
2023-05-05 15:37:10 hasta.scilifelab.se scout.adapter.mongo.base[125942] DEBUG Database name: scout
2023-05-05 15:37:10 hasta.scilifelab.se scout.server.app[125942] INFO Enable Phenopacket API
This will delete and rebuild indexes(if not --update) for the given collections (or the whole database). Are you sure? [y/N]: y
2023-05-05 15:37:25 hasta.scilifelab.se scout.commands.index_command[125942] INFO Running scout index
2023-05-05 15:37:25 hasta.scilifelab.se scout.adapter.mongo.index[125942] INFO Updating indexes for collections: ('case',)
2023-05-05 15:37:25 hasta.scilifelab.se scout.adapter.mongo.index[125942] INFO Adding index : collaborators_status_updated_at
```

**Pull request merged**
