### PR TITLE
Prepare version 4.60

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Mitochondrial deletion signatures (mitosign) can be uploaded and shown with mtDNA report
- [x] A `Type of analysis` column on Causatives and Validated variants pages
- [x] List of "safe" gene panels available for matching causatives and managed variants in institute settings, to avoid secondary findings
- [x] svdb_origin as a synonym for FOUND_IN to complement set for variants found by all callers
### Changed
- [x] Hide removed gene panels by default in panels page
- [x] Removed option for filtering cancer SVs by Tumor and Normal alt AF
- [x] Hide links to coverage report from case dynamic HPO panel if cancer analysis
- [x] Remove rerun emails and redirect users to the analysis order portal instead
- [x] Updated clinical SVs igv.js track (dbVar) and added example of external track from https://trackhubregistry.org/
### Fixed
- [x] If trying to load a badly formatted .tsv file an error message is displayed.
- [x] Avoid showing case as rerun when first attempt at case upload failed
- [x] Dynamic autocomplete search not working on phenomodels page
- [x] Callers added to variant when loading case (but `set=Intersection` from MIP/svdb)
- [x] Now possible to update managed variant from file without deleting it first
- [x] Missing preselected chromosome when editing a managed variant
- [x] Preselected variant type and subtype when editing a managed variant
- [x] Typo in dbVar ClinVar track, hg19

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the paxa software installed on `hasta`:
 - Log in into hasta: `ssh <USER.NAME>@hasta.scilifelab.se`
 - Activate the staging environment with the command `us` (Use Stage)
 - Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the server cg-vm1 as server.
1. Log out from the hasta server.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by
- [x] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
I've installed this branch on stage, so we can test it

**Comment by northwestwitch** [comment]
Oh no, the Hg19 SVs track is not found any more, I'll fix!

image

image

**Comment by northwestwitch** [comment]
I forgot that we have to modify the config files of Scout also if we want to redirect to the order portal to rerun samples. But we should modify at the same time that we do the deploy of the new release, otherwise the old release will still look for the params to send the email in the config files!

**Comment by northwestwitch** [comment]
> I forgot that we have to modify the config files of Scout also if we want to redirect to the order portal to rerun samples. But we should modify at the same time that we do the deploy of the new release, otherwise the old release will still look for the params to send the email in the config files!

Perhaps we can have both rerun URL to the orderportal and  and rerun email params for a while. When the new release of scout is deployed in scout the rerun email params won't be used any more and we can removed them

**Comment by northwestwitch** [comment]
> Perhaps we can have both rerun URL to the orderportal and and rerun email params for a while. When the new release of scout is deployed on prod the rerun email params won't be used any more and we can removed them

This is done --> https://github.com/Clinical-Genomics/servers/pull/914

**Comment by dnil** [comment]
Loading `justhusky` on `scout-stage` from `hasta`, with mitodel files manually added to load config.
✅ Screenshot 2022-10-11 at 17 12 57
Also tests caller load:
Screenshot 2022-10-11 at 17 11 13
Screenshot 2022-10-11 at 17 10 54
Looks good, but also saw this:
Screenshot 2022-10-11 at 17 12 03
This is correct in a way from Scout, since the vcf has `set=Intersection;` (but no `FOUND_IN` tag). In contrast e.g. `svdb_origin=tiddit|cnvnator|manta;` gives a better picture. It is fine for the one or two caller set's but breaks when all three are just given as Intersection. Lets give this a think. We should forward the issue to MIP again - perhaps it is already fixed with the latest of 11.1? But since it is bugged in Scout also already, some level of fixing now is also on the table. We could temp disable a couple of currently unused callers, move the caller constants to config, or add parsing of `svdb_origin`.

**Comment by dnil** [comment]
✅ 
Screenshot 2022-10-11 at 17 30 49

**Review by dnil — APPROVED** [review]

**Comment by dnil** [comment]
✅ Deployed on hasta:
```
Installing collected packages: scout-browser
  Attempting uninstall: scout-browser
    Found existing installation: scout-browser 4.58
    Uninstalling scout-browser-4.58:
      Successfully uninstalled scout-browser-4.58
Successfully installed scout-browser-4.60
θ61° [daniel.nilsson@hasta:~/scout_update_221012] [P_scout] $ 
```

**Comment by northwestwitch** [comment]
Deployed on cg-prod-services:

image

image

**Pull request merged**
