### PR TITLE
Release 4.5.1

### PR DESCRIPTION
**Pull request by northwestwitch**
Small fixes:

- update requirement to use PyYaml version >= 5.1
- Safer code when loading config params in cli base

- [x] Approved for merge and deploy by @ingkebil

### CODE REVIEW

**Comment by ingkebil** [comment]
Some remarks:
- you're releasing two fixes even though the intended release was for one fix only.
- the second fix has not been tested.

I will approve the merge and deploy now and I would suggest that if you want to be able to release small fixes like this, you either switch properly to git flow (and add a development branch) which would have allowed you to release only the intended fix and keep the other minor change for your next release.
If you do not think git flow works out for you, you can always switch to a rolling release cycle by using github flow.
Both are described in detail here: http://www.clinicalgenomics.se/development/dev/models/

Let me know if you need any help! :)

**Comment by northwestwitch** [comment]
Thanks. The other fix (safer base cli) was tested, approved and merged into master already (it was already in the readme). 

Every time we have released a new version of Scout we have been describing in the readme everything that has changed from the previous version. I think this is really good if you want to keep track of all the changes at the release level.

Regarding the 2 models (git flow and rolling release) I think we have to have a discussion about it with @dnil @moonso and @henrikstranneheim (if he wants). But I'll read the documentation!

**Comment by northwestwitch** [comment]
Could someone approve @ingkebil @moonso @dnil ? Thanks!

**Comment by dnil** [comment]
Dont forget to motivate the minor version change! 😉

**Comment by northwestwitch** [comment]
> 👍

Thanks!!!

**Comment by ingkebil** [comment]
Feel free to deploy on clinical-db. I'll deploy later today on hasta. I will also remove the restriction to deploy scout on hasta so you can do it.

**Comment by northwestwitch** [comment]
Thanks!

**Comment by ingkebil** [comment]
It's deployed on hasta now

**Comment by northwestwitch** [comment]
Great, thanks! @adrosenbaum whatever you need to test should work now :)

**Pull request merged**
