### PR TITLE
Release version 4.75

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Hovertip to gene panel names with associated genes in variant view, when variant covers more than one gene
- [x] Tests for panel to genes
- [x] Download of Orphadata en_product6 and en_product4 from CLI
- [x] Parse and save `database_found` key/values for RNA fusion variants
- [x] Added fusion_score, ffpm, split_reads, junction_reads and fusion_caller to the list of filters on RNA fusion variants page
- [x] Renamed the function `get_mei_info` to `set_mei_info` to be consistent with the other functions
- [x] Fixed removing None key/values from parsed variants
### Changed
- [x] Allow use of projections when retrieving gene panels
- [x] _Do not save custom images as binary data into case and variant database documents (tested by collaborators in Lund)_
- [x] _Retrieve and display case and variant custom images using image's saved path (tested by collaborators in Lund)_
- [x] Cases are activated by viewing FSHD and SMA reports
- [x] Split multi-gene SNV variants into single genes when submitting to Matchmaker Exchange
- [x] Alamut links also on the gene level, using transcript and HGVS: better for indels. Keep variant link for missing HGVS
- [x] Thaw WTForms - explicitly coerce form decimal field entries when filters fetched from db
### Fixed
- [x] Removed some extra characters from top of general report left over from FontAwsome fix
- [x] Do not save fusion variants-specific key/values in other types of variants
- [x] _Alamut link for MT variants in build 38 (tested by collaborators in Lund)_
- [x] Convert RNA fusions variants `tool_hits` and `fusion_score` keys from string to numbers
- [x] Fix genotype reference and alternative sequencing depths defaulting to -1 when values are 0
- [x] DecimalFields were limited to two decimal places for several forms - lifting restrictions on AF, CADD etc.

**Review:**
- [x] code approved by DN
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by northwestwitch** [comment]
Deployed on both cg-vm1 and hasta stage now!

**Comment by northwestwitch** [comment]
I've removed and re-uploaded [this fusion case](https://scout-stage.scilifelab.se/cust000/ACC8869A1-1M-FUSION) to test the changes that apply to this category

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
Deployed on hasta prod:

image

**Comment by dnil** [comment]
Deployed:
Screenshot 2023-12-20 at 16 19 57

**Pull request merged**
