### PR TITLE
Darker background

### LINKED ISSUE #1496: Scout DarkMode
The new colours are officially great, :tada: but the white is a bit harsh on the eyes.

### PR DESCRIPTION
**Pull request by northwestwitch**
fix #1496

**How to test**:
1. Clean browsing data of your browser (cached images and files would suffice)
1. Checkout to this branch on a local instance of Scout and note the difference in color in all cards backgrounds.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by
- [x] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is also a very easy review

**Comment by dnil** [comment]
Nicer on the eyes, though not exactly a dark mode.
There are some aesthetic issues though. For one, there is an issue with what might have been yesterdays other fix of bs4: the new(?)`<ul class="list-group">` items get a white background and need another solution. Perhaps there is a clash with the css-definition of `list-group` for the sidebar? 

Here's an example:
Screenshot 2019-12-17 at 19 26 22

**Comment by northwestwitch** [comment]
Fixed the elements which were white:

image

**Comment by dnil** [comment]
Some collateral damage - sidebar separator.. 

Screenshot 2019-12-18 at 14 29 09

Also the active tabs: perhaps that was intended?

Screenshot 2019-12-18 at 14 30 44

**Comment by northwestwitch** [comment]
> Some collateral damage - sidebar separator..
> 
> Screenshot 2019-12-18 at 14 29 09
> 
> Also the active tabs: perhaps that was intended?
> 
> Screenshot 2019-12-18 at 14 30 44

I'll fix the sidebar. Regarding the tabs: it was not intended but maybe it's good to have the active one different from the other ones, what do you think?

**Comment by dnil** [comment]
Yes, it is kind of useful to see the active one; I suppose the standard way of doing that is to follow the color of the active tab-card foreground, and having the menu lining/surround be the same color as the inactive tabs?

**Comment by northwestwitch** [comment]
I've tested by making the active tabs content white but I didn't like how they became more visible than the rest in the variant pages. So I've decided to turn the tab headers grey as well:
image

I think I'm done with this PR, ready for a new review!

**Comment by moonso** [comment]
@dnil could you have a final look?

**Pull request merged**
