### PR TITLE
Release notes 4.7.2

### PR DESCRIPTION
**Pull request by dnil**
### Added
- Show earlier ACMG classification in the variant list

### Fixed
- Fixed igv search not working due to igv.js dist 2.2.17
- Fixed searches for cases with a gene with variants pinned or marked causative.
- Load variant pages faster after fixing other causatives query

- [x] code approved by CR
- [x] "merge and deploy" approved by @ingkebil 

This is a patch version bump because contains 3 bug fixes

### CODE REVIEW

**Comment by ingkebil** [comment]
Hi guys, can you motivate the version bump? Thanks

**Comment by dnil** [comment]
Sure! Largely a patch release with fixes to existing functionality. The only feature is a small UI change that mirrors display of previous ACMG P/LP evaluation to small labels on the variants list that can and could also be found on the respective variant pages.

**Comment by northwestwitch** [comment]
Ah yes, I added the motivation to the PR description

**Comment by dnil** [comment]
Hi @northwestwitch, @ingkebil: I'm wfh today; will you meet @emiliaol et al to check when would be a good time for them to have this out? Its a fairly nice analysis speed improvement for customers.

**Comment by northwestwitch** [comment]
> Hi @northwestwitch, @ingkebil: I'm wfh today; will you meet @emiliaol et al to check when would be a good time for them to have this out? Its a fairly nice analysis speed improvement for customers.

Done. She says it's best not to touch the prod cli environment today so I guess we could update clinical-db today and hasta tomorrow.  I'll send the email to the customers now. Today at 12 sounds good?

**Pull request merged**
