### PR TITLE
Upgrade python to 3.11 in Docker images

### PR DESCRIPTION
**Pull request by northwestwitch**
Switch from python 3.8 to python 3.11

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. Run docker-compose up and make sure the server works

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by DNIL
- [x] tests executed by CR, automatic tests

### CODE REVIEW

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
image

Thanks for your trust @dnil  😆

**Comment by dnil** [comment]
Ahem, looks good, but seems we need to solve the deps install.. 😅

**Comment by northwestwitch** [comment]
Could be this? https://github.com/brentp/cyvcf2/issues/274

**Comment by dnil** [comment]
> Could be this? [brentp/cyvcf2#274](https://github.com/brentp/cyvcf2/issues/274)

Yes, or a slight variation thereof. Looks like the htslib build/include - could be some missing headers on the base image I guess.

**Comment by northwestwitch** [comment]
I think on linux it is failing even before, see the error message in. the actions. I'm getting a different error here with mac

**Comment by dnil** [comment]
> I think on linux it is failing even before, see the error message in. the actions. I'm getting a different error here with mac

Yes, it appears they think it is architecture dependent from the PR. I would have guessed distributes dependent based on the protest on the includes, but I guess that could be from arch and autoconfig. Many moving parts there..

**Comment by northwestwitch** [comment]
> Yes, it appears they think it is architecture dependent from the PR. I would have guessed distributes dependent based on the protest on the includes, but I guess that could be from arch and autoconfig. Many moving parts there..

To reproduce on your mac: `docker buildx build --platform=linux/amd64`

**Comment by northwestwitch** [comment]
This work now. The problem was that the new base image (python3.11-venv) was built without specifying --platform linux/amd64. After rebuilding and pushing it again to Docker Hub everything is fixed!

**Pull request merged**
