### PR TITLE
Prepare patch version 4.58.1

### PR DESCRIPTION
**Pull request by northwestwitch**
### Fixed
- [x] Case search with search strings that contain characters that can be escaped

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the paxa software installed on `hasta`:
 - Log in into hasta: `ssh <USER.NAME>@hasta.scilifelab.se`
 - Activate the staging environment with the command `us` (Use Stage)
 - Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the server cg-vm1 as server.
1. Log out from the hasta server.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**Review:**
- [x] code approved by DN
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is deployed on cg-vm1 now!

**Comment by northwestwitch** [comment]
It's working on stage:

image

**Review by dnil — APPROVED** [review]
👍

**Comment by dnil** [comment]
✅ Deployed
```
[hiseq.clinical@cg-prod-services ~]$ systemctl --user stop scout@v4.58.1.service
[hiseq.clinical@cg-prod-services ~]$ systemctl --user start scout@v4.58.1.service
[hiseq.clinical@cg-prod-services ~]$ podman ps |grep scout
b07ddb36fb68  docker.io/clinicalgenomics/scout-server:v4.58.1        /bin/sh -c gunico...  11 seconds ago  Up 11 seconds ago  0.0.0.0:7073->8000/tcp  scout-v4.58.1

```

**Pull request merged**
