### PR TITLE
Autozygosity; 3.2.0 based due to issue with 3.3.0 demo. 

### PR DESCRIPTION
**Pull request by dnil**
Seems the base difference is minor; should be trivially mergeable though not automatic.

### CODE REVIEW

**Comment by moonso** [comment]
Hi @dnil ! 
I just fixed the problem with variant ranks in v3.3.0, could you please make the PR/rebase on that one?

**Comment by dnil** [comment]
Since rebasing is so much fun. ;-)
I’ll have a look in the afternoon.

**Comment by moonso** [comment]
👯

**Comment by dnil** [comment]
Ok, added to release-v3.3.0 branch. Closing this one.

**Pull request closed without merging**
