### PR TITLE
Drop classification float

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

The classification summary was hidden by the sticky navbar. One could play with offsets and have the secondary-flow below the navbar, but I'm not sure it helps anyone much? Here is a suggestion to just keep it scrolling with the page.

Screenshot 2022-06-13 at 11 00 34

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the paxa software installed on `hasta`:
 - Log in into hasta: `ssh <USER.NAME>@hasta.scilifelab.se`
 - Activate the staging environment with the command `us` (Use Stage)
 - Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the server cg-vm1 as server.
1. Log out from the hasta server.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
</details>
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Sorry, I messed up the changelog when I merged my previous PR, fixed in thie one now!

**Comment by northwestwitch** [comment]
This fix works and the buttons are available again, but I noticed that they don't change color interactively when a user checks the checkboxes of the functionality.

Example in release version 4.53 --> Benign classification button becomes blue if I check  `Frequency >=hi_freq_cutoff `BA1 checkbox

image

In this branch the buttons above stay the same:

image

**Comment by dnil** [comment]
Well noted! I also reverted to a fixed pos, but at the bottom. Like so now:

Screenshot 2022-06-13 at 11 55 05

**Review by northwestwitch — APPROVED** [review]
Works perfectly now. Very nice looks as well! 💯 

Here is the light mode test:

image

**Pull request merged**
