### PR TITLE
Prepare version 4.68

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Rare Disease Mobile Element Insertion variants view
### Changed
- [x] Updated igv.js to 2.15.6
### Fixed
- [x] Docker stage build pycairo.
- [x] Restore SNV and SV rank models versions on Causatives and Verified pages
- [x] Saving `REVEL_RANKSCORE` value in a field named `revel` in variants database documents

**Review:**
- [x] code approved by DN
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by northwestwitch** [comment]
I've been thinking, perhaps a small release with what we have so fare (mostly bug fixes) would be nice to have before merging a big new feature (#3918 -  RD MEI view)

**Comment by northwestwitch** [comment]
Ah nice, the issue in #3940 (CyVCF2 updated lib causing the docker deployment failure)  is fixed now!

**Comment by northwestwitch** [comment]
This branch is deployed on cg-vm1 now

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
Deployed on Hasta stage:

image


And Hasta prod:

image

**Comment by northwestwitch** [comment]
Deployed on cg-vm1:

image


And prod-services:

image

**Pull request merged**
