### PR TITLE
Add missing links in documentation

### PR DESCRIPTION
**Pull request by northwestwitch**
I've realized that in a previous PR I forgot to include the links of some new doc files in the mkdocs file. I'm adding these missing file now and I'm fixing also a couple of other links that didn't work from before. 
Note that **you might need to install mkdocs as a dependency**.

**How to test**:
1. run `mkdocks serve` on master branch and make sure these pages don't work:
- From http://0.0.0.0:4000/user-guide/ the links to the ACMG classification and the dashboard (on the bottom of the list)
- http://0.0.0.0:4000/admin-guide/containers/container-deploy/
- http://0.0.0.0:4000/admin-guide/containers/kubernetes/
- http://0.0.0.0:4000/admin-guide/containers/systemd/

**Expected outcome**:
Run `mkdocs serve` from this branch and the links above should work

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Ready for review

**Comment by dnil** [comment]
Actually good with test. I was missing `markdown-include` on my test env. If you wish, you could include that in the dev requirements here?

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
> Actually good with test. I was missing `markdown-include` on my test env. If you wish, you could include that in the dev requirements here?

Sure!

**Comment by dnil** [comment]
> > Actually good with test. I was missing `markdown-include` on my test env. If you wish, you could include that in the dev requirements here?
> 
> Sure!

..or I do it in #2321. Ahem. :facepalm: Your call!

**Pull request merged**
