### PR TITLE
Replace GQ with VAF in cancer snv variants 

### LINKED ISSUE #2285: Replace Genotype quality with VAF?
HI! 
Since I have learned that the genotype quality -1 is a "bugg", can we replace it with VAF? 

image

Best Regards, Hero

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #2285 

**How to test**:
1. Locally, go to a cancer SNV variant and note that on master branch the GQ field is -1
2. Switch to this branch and note that the GQ field is replaced by VAF and the numbers are the same as in variantS page as well as in the general report.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by
- [x] tests executed by mikaell

### CODE REVIEW

**Review by mikaell — APPROVED** [review]
Looks good!

**Comment by dnil** [comment]
Hold it just one minute or two - I was just checking and thought I spotted an issue..

**Comment by dnil** [comment]
I think it has an issue with tumor only samples (and thus presumably also with showing the wrong value for the pairs?)
Screenshot 2021-01-26 at 11 22 32

Need to join the others now, will look more carefully in the afternoon if you haven't proven me wrong already by then!

**Comment by northwestwitch** [comment]
> I think it has an issue with tumor only samples (and thus presumably also with showing the wrong value for the pairs?)

Ok! I'll check!

**Comment by northwestwitch** [comment]
@dnil you were right, the VAFs were missing in some cases. This should be fixed now that I've changed the code to collected these values from cancer.tumor and cancer.normal variant keys

**Comment by dnil** [comment]
Lucky guess on my part; really hard to spot when the ADs are not shown next to it. We should really include current test files with the demo, paired and unpaired with proper AD counts. Perhaps we could get some of cust666 - ping @hassanfa ?

**Comment by northwestwitch** [comment]
i'm going to test this one on stage!

**Comment by dnil** [comment]
Good call!

**Comment by hassanfa** [comment]
> Lucky guess on my part; really hard to spot when the ADs are not shown next to it. We should really include current test files with the demo, paired and unpaired with proper AD counts. Perhaps we could get some of cust666 - ping @hassanfa ?

Yes, there are bunch of test data in cust666. Feel free to use them. If you need original files, please reach out.

**Comment by northwestwitch** [comment]
Ok, tested with:
- [ ] [tumor only](https://scout-stage.scilifelab.se/cust000/actualgecko/cancer/variants and it works)
- [ ] [paired tumor/normal](https://scout-stage.scilifelab.se/cust000/20190327_cancer_T_N/cancer/variants?variant_type=clinical)

They both work!

**Comment by dnil** [comment]
Concur - well done!

**Comment by northwestwitch** [comment]
> Concur - well done!

I even fixed a bug that I've created in my previous PR 🤣

**Pull request merged**
