### PR TITLE
Link to chanjo2 genes overview on gene panel page

### LINKED ISSUE #4000: Support for chanjo2
Add the option to use [chanjo2](https://chanjo2-stage.scilifelab.se/docs) to get coverage stats.

For now the chanjo2 endpoints are open, but we will probably restrict the access to most of them when it goes in  production. 

We should also replace chanjo-report with a new solution (in scout? In chanjo2?)

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug.
- Final piece of scout-chanjo2 integration (closes #4000)
- Adds a link to the genes overview on gene panel page

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test.**:
1. Testable on our stage server with case [safeguinea](https://scout-stage.scilifelab.se/cust000/F0006358-mip7)
2. Go to a case with gene panels
3. On the case page, click on one of the panels
image

4. Once on the gene panel page, check the link to the genes overview report of chanjo2:

image

**Expected outcome**:
The genes overview page should be visible.
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by Jakob37** [comment]
I'll test!

**Comment by Jakob37** [comment]
The test case works for me:

5_chanjo2_final_testing

5_chanjo2_final2

My onco sample also worked (realized that it had a default panel specified in the yml, if added to the `gene_panels` array as well, then it appeared in Scout.

Same errors as before when attempting to load the wgs sample.

**Review by Jakob37 — APPROVED** [review]
Looks great 🎉

**Comment by northwestwitch** [comment]
> Looks great 🎉

Thanks for testing @Jakob37! 🙏🏻

**Pull request merged**
