### PR TITLE
Fix region|function freq. overlapping in SV variants cells

### LINKED ISSUE #3575: Functional annotations overlapping frequencies
When checking the new version, this came up;
Screenshot 2022-09-07 at 14 56 39

We should wrap/fix column width or give prio to freq worst case: it is the more important info.

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #3575 

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the paxa software installed on `hasta`:
 - Log in into hasta: `ssh <USER.NAME>@hasta.scilifelab.se`
 - Activate the staging environment with the command `us` (Use Stage)
 - Run the command `paxa` and follow the instructions. Make sure to specify scout-stage as the resource you request and the server cg-vm1 as server.
1. Log out from the hasta server.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by DN
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by northwestwitch** [comment]
I've deployed this branch on stage @dnil , check it out when you have time!

**Comment by dnil** [comment]
Thanks, much better! Is it a little bit funny that the few-genes cells work differently (comma separated list) than the many gene cells (multiple single lines)? Nah, since the many ones are folded from the start, it works, right?

Now that I've thought it, I would still think the frequency column should go earlier in the table, like at least before the region anno. I would make it Length, Frequency, Gene, Region, Function instead, which is more how you think about the variants. Makes sense?

**Comment by northwestwitch** [comment]
> Thanks, much better! Is it a little bit funny that the few-genes cells work differently (comma separated list) than the many gene cells (multiple single lines)? Nah, since the many ones are folded from the start, it works, right?
> 
> Now that I've thought it, I would still think the frequency column should go earlier in the table, like at least before the region anno. I would make it Length, Frequency, Gene, Region, Function instead, which is more how you think about the variants. Makes sense?

Makes sense. I've changed the order of columns like you suggest for SVs and cancer SVs. SNVs and STRs are different and didn't have that order to start with

**Comment by northwestwitch** [comment]
> Thanks, much better! Is it a little bit funny that the few-genes cells work differently (comma separated list) than the many gene cells (multiple single lines)? Nah, since the many ones are folded from the start, it works, right?

Deployed the latest now. Yes the cells with many genes start folded.

**Comment by dnil** [comment]
> Makes sense. I've changed the order of columns like you suggest for SVs and cancer SVs. SNVs and STRs are different and didn't have that order to start with

Sorry for being late - I'm the too-many-meetings person today. Looks great! Yes, SNVs have an order closer to this actually, and we don't do region/consequences for the STRs - in the cases they are truly known, they are sort of clear from the catalog/litterature before calling and annotation. Bonus points for also remembering the cancer SVs!

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
> Sorry for being late - I'm the too-many-meetings person today.

No worries, I figured! Thanks for the review!

**Pull request merged**
