### PR TITLE
Rename "Clinical significance" to "Germline classification" in ClinVar variant files

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug.
- Partial fix for #4391  - first item

The tricky thing is that there are **open submissions with variants having old key naming (clinsig)**. We want these variants to be exported correctly and the new Germline classification column filled in as for the variants saved after this PR is merged.
<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. Locally or on stage, go to main branch and create a new ClinVar submission object. It's also OK if you have available a submission object with a variant added using an old branch 
2. On the ClinVar submissions page, export the Variant csv file and make sure that there is a populated column named `Clinical significance` with values in it.
3. Switch to this branch and add a new variant. Make sure there are no errors and go to ClinVar submissions page
4. Export again the Variant csv file and make sure that the `Clinical significance` column is now renamed to `Germline classification` and is filled in for both variants.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by TB
- [x] tests executed by TB

### CODE REVIEW

**Comment by TereseBo** [comment]
Clinical significance column is not renamed in the css download:

Screenshot 2024-02-07 at 12 43 52

**Review by TereseBo — CHANGES_REQUESTED** [review]
Column name in the css-file has not been replaced, it's in I believe it's found in: /scout/constants/clinvar.py

**Comment by northwestwitch** [comment]
> Column name in the css-file has not been replaced, it's in I believe it's found in: /scout/constants/clinvar.py

Weird, same variant, on a local instance with this branch:

image


Could you tell me your steps, to understand what we are doing different?

**Comment by TereseBo** [comment]
Works excellent when using the correct branch to test:

image

**Review by TereseBo — APPROVED** [review]

**Pull request merged**
