### PR TITLE
Test update fontwesome

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.
OR
This PR marks a new Scout release. We apply semantic versioning. This is a major/minor/patch release for reasons.

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by dnil** [comment]
Well, the slightly-older variant with 6.4.2 was not the drop in replacement at least:
Screenshot 2023-11-29 at 10 16 28

**Comment by dnil** [comment]
Perhaps yes. 5.9:
Screenshot 2023-11-29 at 10 25 27

**Comment by dnil** [comment]
The 5.9 all.js at least has clinvar:
Screenshot 2023-11-29 at 10 27 32

**Comment by dnil** [comment]
Ah, the 6.4.2 `all.js` kind of looks like the thing!

**Comment by northwestwitch** [comment]
> Ah, the 6.4.2 `all.js` kind of looks like the thing!

Yes! 🥳

**Comment by dnil** [comment]
Specifically:
Screenshot 2023-11-29 at 10 34 55
Screenshot 2023-11-29 at 10 34 25

**Comment by northwestwitch** [comment]
I think the link to the PDF reports might be broken:

image

**Comment by dnil** [comment]
yes, looks broken. Also, while 6.5.0 does have at least the non-o version, it is a little bugged methinks, with the glyph reading "PNG" instead? I'll test some of the 5.15 stuff as well - I missed the >5.9 versions.. :)

**Comment by dnil** [comment]
This feels rather good again, but let's keep looking for missing ones! I found the copy-to-clipboard one.

**Comment by dnil** [comment]
The last patch of the previous major should be a decently stable place, right?

**Comment by dnil** [comment]
Ok, pdf report icons are back, and some others with them:

Screenshot 2023-11-29 at 11 29 22

**Review by northwestwitch — APPROVED** [review]
This is fixing all the problems we've seen on prod! 🚀

**Pull request merged**
