### PR TITLE
Exporting all MT variants into excel files (one per sample) + test

### PR DESCRIPTION
**Pull request by northwestwitch**
Created a CLI for this functionality. I'll work on the web app code next. 
This is addressing #793

- Creates an excel document for each sample in a case. Saves files in a specified outfolder or in the working directory

### CODE REVIEW

**Comment by northwestwitch** [comment]
What?? They deprecate methods you are using until the day before (or very recently at least)! @moonso could you help me fix this error? I know for a fact that you've been busy specifically with this stuff: https://github.com/mongomock/mongomock/pull/4549

**Comment by moonso** [comment]
Hi @northwestwitch what do you mean here? Maybe you can lock the mongomock version if it breaks?

**Comment by northwestwitch** [comment]
Or I'll update the method with the new syntax, thanks!

**Comment by northwestwitch** [comment]
It's not!

**Comment by northwestwitch** [comment]
I'm working on a similar export function from the web app. I'll test them both on stage and get back to you when this is done, thanks!

**Comment by northwestwitch** [comment]
I think I'm done with this PR. I've installed the branch on stage and it looks like it's working. (asked also the clinicians to test it, so I fix it if anything is off). 

For the CLI I've installed it on rasta stage and the installation works, but then there are the usual problems related to the db connection and I couldn't really test it there. I think it would be better tested on your local computer and then in production (it doesn't really affect anything else I think).

**Pull request merged**
