### PR TITLE
Take care of empty bam paths values

### PR DESCRIPTION
**Pull request by northwestwitch**
This is an urgent bug fix

The current master branch doesn't handle well when both these keys are present in case config file:
1. An empty `bam_path`
1. A valid `alignment_path`

**How to test**:
1. Install it on hasta stage and upload a case with the above configuration
1. Make sure that the correct bam path is passed along and saved in the database.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by MM
- [x] tests executed by HS

### CODE REVIEW

**Comment by northwestwitch** [comment]
Waiting to see if the upload of a test case on hasta stage worked!

**Comment by henrikstranneheim** [comment]
1. The current master branch doesn't handle well when both these keys are present in case config file:

    An empty bam_path
    A valid alignment_path

**How to test:**

Install it on hasta stage and upload a case with the above configuration
Screenshot 2020-02-19 at 14 44 28

Screenshot 2020-02-19 at 14 44 52

Works with vitalmouse on hasta

**Comment by northwestwitch** [comment]
@henrikstranneheim and I would meed to deploy this bugfix ASAP.

My question is: do we want to merge to master and deploy everything we have done since the latest release of should we do a patch, based on the latest version + this PR?

I vote for the first option @moonso @dnil ?

**Comment by dnil** [comment]
So far I think no release accepts alignment_path only current master, so a patch would be rather strange? If you are in a hurry to get that out I also suggest making a proper release.

**Comment by northwestwitch** [comment]
> So far I think no release accepts alignment_path only current master, so a patch would be rather strange? If you are in a hurry to get that out I also suggest making a proper release.

One could pull the other changes from #1689 into last release branch, but since we have done several other things it would be nice to release them out, so they're used. And it's not even Friday this time (we always make new releases on Friday lately :D)

**Comment by moonso** [comment]
I vote for releasing everything, it is about time anyway

**Comment by northwestwitch** [comment]
We release everything then! 👍

**Comment by henrikstranneheim** [comment]
🤞

**Pull request merged**
