### PR TITLE
DRAFT: Feature chromograph 200820

### PR DESCRIPTION
**Pull request by mikaell**
This PR adds a functionality. Deeper and improved integration with Chromograph output. Prepared for a CG patch (in the works) that will generate fitting conf-files.

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by mikaell** [comment]
Got lost in other stuff. Now this is on the move again. Prepare for a proper PR any time soon 😄

**Comment by mikaell** [comment]
If the tests pass, this is ready for review.

**Comment by northwestwitch** [comment]
Hi @mikaell there are 2 Chromograph PRs open at the moment, which one is the official one, and can we close the other?

**Comment by mikaell** [comment]
> Hi @mikaell there are 2 Chromograph PRs open at the moment, which one is the official one, and can we close the other?

Closing this one! 200820.

**Pull request closed without merging**
