### PR TITLE
Minor release 4.78

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Case status labels can be added, giving more finegrained details on a solved status (provisional, diagnostic, carrier, UPD, SMN, ...)
- [x] _New SO terms: `sequence_variant` and `coding_transcript_variant`_  (Tested by collaborator)
- [x] More MEI specific annotation is shown on the variant page
- [x] Parse and save MANE transcripts info when updating genes in build 38
- [x] `Mane Select` and `Mane Plus Clinical` badges on Gene page, when available
- [x] ClinVar submission can now be downloaded as a json file
- [x] API endpoint to pin variant
- [x] Display common/uncommon/rare on summary of mei variant page
### Changed
- [x] In the ClinVar form, database and id of assertion criteria citation are now separate inputs
- [x] Customise institute settings to be able to display all cases with a certain status on cases page (admin users)
- [x] Renamed `Clinical Significance` to `Germline Classification` on multistep ClinVar form
- [x] Changed the "x" in cases.utils.remove_form button text to red for better visibility in dark mode
- [x] Update GitHub actions
- [x] Default loglevel up to INFO, making logs with default start easier to read
- [x] Add XTR region to PAR region definition
- [x] Diagnoses can be searched on diagnoses page without waiting for load first
### Fixed
- [x] Removed log info showing hgnc IDs used in variantS search
- [x] Maintain Matchmaker Exchange and Beacon submission status when a case is re-uploaded
- [x] Inheritance mode from ORPHA should not be confounded with the OMIM inheritance model
- [x] Decipher link URL changes
- [x] Refactored code in cases blueprints to use "disease" instead of "omim" to encompass also ORPHA terms

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by northwestwitch** [comment]
On hasta, downloaded all files and updated genes OK:

image


MANE transcripts parsed allright:

image


image

**Comment by dnil** [comment]
✅ This is the XTR region
Screenshot 2024-02-27 at 15 39 41
(Research) variants in the genes there are now properly flagged "PAR" on the variant page GT card. 
Screenshot 2024-02-27 at 15 39 15

**Comment by dnil** [comment]
✅ MEI freq on variant Summary card
Screenshot 2024-02-27 at 15 42 57
Screenshot 2024-02-27 at 15 43 07

**Comment by northwestwitch** [comment]
Case re-upload with Matchmaker submission retention tested with this case: cust000/15030-mip7

Created a submission 
image

Then if re-uploaded the case the MME submission is still there:

image

**Review by dnil — APPROVED** [review]
👍

**Comment by northwestwitch** [comment]
Deployed on hasta prod:

image

**Comment by dnil** [comment]
And on `cg-prod-services`:
Screenshot 2024-02-28 at 11 01 13

**Pull request merged**
