### PR TITLE
New minor release 4.58

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Documentation on how to create/update PanelApp panels
- [x] Add filter by local observations (archive) to structural variants filters
- [x] ~~Add more splicing consequences to SO term definitions~~ Tested by our collaborators in Umeå
- [x] Institute settings option to force show all variants on VariantS page for all cases of an institute
- [x] Filter cases by validation pending status
- [x] Link to The Clinical Knowledgebase (CKB) (https://ckb.jax.org/) in cancer variant's page
### Fixed
- [x] Added a not-authorized `auto-login` fixture according to changes in Flask-Login 0.6.2
- [x] Renamed `cache_timeout` param name of flask.send_file function to `max_age` (Flask 2.2 compliant)
- [x] Replaced deprecated `app.config["JSON_SORT_KEYS"]` with app.json.sort_keys in app settings
- [ ] Bug in gene variants page (All SNVs and INDELs) when variant gene doesn't have a hgnc id that is found in the database
- [x] Broken export of causatives table
- [x] Query for genes in build 38 on `Search SNVs and INDELs` page
- [x] Prevent typing special characters `^<>?!=\/` in case search form
- [x] Search matching causatives also among research variants in other cases
- [x] Links to variants in Verified variants page
- [x] Broken filter institute cases by pinned gene
- [x] Better visualization of long lists of genes in large SVs on Causative and Verified Variants page
- [x] Reintroduced missing button to export Causative variants
- [x] Better linking and display of matching causatives and managed variants
### Changed
- [x] State that loqusdb observation is in current case if observations count is one and no cases are shown  
- [x] Better pagination and number of variants returned by queries in `Search SNVs and INDELs` page
- [x] Refactored and simplified code used for collecting gene variants for `Search SNVs and INDELs` page
- [x] Fix sidebar panel icons in Case view
- [x] Fix panel spacing in Case view
- [x] Removed unused database `sanger_ordered` and `case_id,category,rank_score` indexes (variant collection)
- [x] Verified variants displayed in a dedicated page reachable from institute sidebar
- [x] Unified stats in dashboard page
- [x] Improved gene info for large SVs and cancer SVs
- [x] Remove the unused `variant.str_variant` endpoint from variant views
- [x] Easier editing of HPO gene panel on case page
- [x] Assign phenotype panel less cramped on Case page
- [x] Causatives and Verified variants pages to use the same template macro
- [x] Allow hyphens in panel names

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
It's going to be a big one with many things to test. By my side I'd like to include 2 more PRs which are more or less ready I think:

- #3542
- #3518

**Comment by northwestwitch** [comment]
The feature "State that loqusdb observation is in current case if observations count is one and no cases are shown" can be tested in [this variant](https://scout-stage.scilifelab.se/cust002/F0008420-2/73b4e33b38e35a3dce30dfbe3f41a5e9)

**Comment by northwestwitch** [comment]
Search matching causatives also among research variants in other cases can be tested with [this variant](https://scout-stage.scilifelab.se/cust000/15035-mip7/e80d3ae5119c67d95bed8f8752a4e515)

**Comment by northwestwitch** [comment]
I've re-deployed this branch on cg-vm1 to test again now. Do you want to add anything else to this release @dnil? Otherwise I'd wrap it up

**Comment by dnil** [comment]
Thanks, super well done! I'll check a little, but it looks very solid. How about #3555 as well perhaps?

**Comment by northwestwitch** [comment]
> How about #3555 as well perhaps?

Yes, would be good to include it. I can review when you are ready

**Comment by northwestwitch** [comment]
> As for the bug with missing data in the `gene_variants`, we are still very confident it is better now than before, though it remains to be seen if the particular repeating issue actually stops, right?

right!

**Review by dnil — APPROVED** [review]

**Comment by dnil** [comment]
Ok, I've re-tested a few more. Looks swell - let's go release!

**Comment by northwestwitch** [comment]
We would have figured out anyway, but it's very likely that the deployment on Hasta would fail if we don't update Flask and Flask-login libs first.

So let's remember to do the following before:

```
conda activate P_scout
pip install --upgrade flask 
pip install --upgrade flask-login
```

**Comment by dnil** [comment]
It's good to keep them updated at any rate. 

The Flask login thingy with 0.6.2 was mostly for the tests methinks, and my uninitiated view of the flask 2.2 'cache_timeout' to 'max_age' change was that they finally actually did the change they had deprecation flagged for a long(er) time. But I dont actually know when they introduced the replacement function - I assumed 2.0? 😊

**Comment by northwestwitch** [comment]
> I assumed 2.0?

Should be 2.2 ( a minor!), check [the changelog](https://flask.palletsprojects.com/en/2.2.x/changes/)

**Comment by northwestwitch** [comment]
Deployed on hasta:

image

image

Unfortunately the procedure to deploy scout-prod in hasta has changed some |2 weeks ago](https://github.com/Clinical-Genomics/deployment/commit/27d6e3685af5e2bc7995fbfe55710ba69f28dac0) and the script doesn't work:

image

**Comment by northwestwitch** [comment]
Ok, we've managed to deploy on Hasta prod by using the following commands:

```
conda activate P_scout
pip install scout-browser==4.5
```

image

The script for deployment should be fixed ASAP!

**Comment by dnil** [comment]
Deployed ok also on `cg-prod-services`:
```
[hiseq.clinical@cg-prod-services ~]$ systemctl --user start scout@v4.58.service
[hiseq.clinical@cg-prod-services ~]$ podman ps
CONTAINER ID  IMAGE                                                  COMMAND               CREATED        STATUS            PORTS                   NAMES
9dde5e41b0d7  docker.io/clinicalgenomics/cg-deployment:latest        /bin/sh -c gunico...  5 months ago   Up 5 months ago   0.0.0.0:7082->8000/tcp  cg_deployment-latest
565aaf569998  docker.io/clinicalgenomics/loqusdbapi:latest           /bin/sh -c gunico...  4 months ago   Up 4 months ago   0.0.0.0:7079->8000/tcp  loqusdbapi-rd-latest
...
c274b3b953ea  docker.io/clinicalgenomics/scout-server:v4.58          /bin/sh -c gunico...  4 seconds ago  Up 5 seconds ago  0.0.0.0:7073->8000/tcp  scout-v4.58
```

**Comment by dnil** [comment]
> Should be 2.2 ( a minor!), check [the changelog](https://flask.palletsprojects.com/en/2.2.x/changes/)

Yes, looks like it was at least there in 2.1. I think they got around the minor major issue by saying it was deprecated before the 2.0 release, but delayed the actual change to 2.2. 🤷

**Comment by northwestwitch** [comment]
> > Should be 2.2 ( a minor!), check [the changelog](https://flask.palletsprojects.com/en/2.2.x/changes/)
> 
> Yes, looks like it was at least there in 2.1. I think they got around the minor major issue by saying it was deprecated before the 2.0 release, but delayed the actual change to 2.2. 🤷

People do as they like in their repos, I like it! :pirate_flag:

**Pull request merged**
