### PR TITLE
Version 4.77

### PR DESCRIPTION
**Pull request by dnil**
This PR marks a new Scout release. We apply semantic versioning. This is a minor release that adds new features or corrects previous unintended behaviours without breaking backwards compatibility.

### Added
-  [x] Orpha disease terms now include information on inheritance
- [x] Case loading via .yaml config file accepts subject_id and phenotype_groups (if previously defined as constant default or added per institute)
- [x] Possibility to submit variants associated with Orphanet conditions to ClinVar
- [x] Option update path to .d4 files path for individuals of an existing case using the command line
- [x] More constraint information is displayed per gene in addition to pLi: missense and LoF OE, CI (inluding LOEUF) and Z-score.
### Changed
- [x] Introduce validation in the ClinVar multistep form to make sure users provide at least one variant-associated condition
- [x] CLI scout update individual accepts subject_id
- [x] Update ClinVar inheritance models to reflect changes in ClinVar submission API
- [x] Handle variant-associated condition ID format in background when creating ClinVar submissions
- [x] Replace the code that downloads Ensembl genes, transcripts and exons with the Schug web app
- [x] _Add more info to error log when transcript variant frequency parsing fails.  -Tested by collaborator-_
- [x] GnomAD v4 constraint information replaces ExAC constraints (pLi).
### Fixed
- [x] Text input of associated condition in ClinVar form now aligns to the left
- [x] Alignment of contents in the case report has been updated
- [x] Missing number of phenotypes and genes from case diagnoses
- [x] Associate OMIM and/or ORPHA diagnoses with partial causatives
- [x] Visualization of partial causatives' diagnoses on case page: style and links
- [x] Revert style of pinned variants window on the case page
- [x] Rename `Clinical significanc` to `Germline classification` in ClinVar submissions exported files
- [x] Rename `Clinical significance citations` to `Classification citations` in ClinVar submissions exported files
- [x] Rename `Comment on clinical significance` to `Comment on classification` in ClinVar submissions exported files
- [x] Show matching partial causatives on variant page
- [x] Matching causatives shown on case page consisting only of variant matching the default panels of the case - bug introduced since scout v4.72 (Oct 18, 2023)
- [x] Missing somatic variant read depth leading to report division by zero

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by dnil** [comment]
Deployed on cg-vm1 and hasta stage. Updating dbs:

**Comment by northwestwitch** [comment]
> * Add more info to error log when transcript variant frequency parsing fails.

So we can assume that "Replace the code that downloads Ensembl genes, transcripts and exons with the Schug web app" is tested

**Comment by dnil** [comment]
I'm reloading `magicalgnat` on stage with 4.77 on `hasta` to see that case loading is ok, esp the `subject_id`.

**Comment by northwestwitch** [comment]
I've tested:


By exporting files from cist000 [submission SUB4646465](https://scout-stage.scilifelab.se/cust000/clinvar_submissions) - the one on top - and converting them to json using [preclinvar prod](https://preclinvar.scilifelab.se/docs#/default/csv_2_json_csv_2_json_post), endpoint `csv_2_json`:

image


Note that the API still contain the old naming: clinicalSignificance. That's because changed have been applied only to submission by files (at least the latest API submission schema don't contain the new naming convention)

**Comment by dnil** [comment]
Ill just merge then?

**Comment by northwestwitch** [comment]
> Ill just merge then?

Yes!

**Comment by dnil** [comment]
✅ deployed to `hasta` prod
Screenshot 2024-02-14 at 15 58 55

**Pull request merged**
