### PR TITLE
bug fix #832

### LINKED ISSUE #832: KeyError: 'madeline_info'
The program crashes for cases where key 'madeline_info' is not specified. Specifically the code to fix, in the function names "pdf_case_report" is this:

if case_obj['madeline_info'] is not None:

### PR DESCRIPTION
**Pull request by northwestwitch**
This should fix the missing key error

### CODE REVIEW

**Comment by moonso** [comment]
Already fixed, thx anyway!

**Comment by northwestwitch** [comment]
Ok, you're welcome.. But where is it fixed?

**Comment by moonso** [comment]
https://github.com/Clinical-Genomics/scout/commit/9c13c50178b44b397897b26e83c72316831d3f83

**Comment by northwestwitch** [comment]
Ah ok, I didn't realize it was changed!

**Pull request closed without merging**
