### PR TITLE
Changed test matrices to run tests on MongoDB 3.2 to 5.0

### LINKED ISSUE #2902: Check that docker-compose and actions use MongoDB version 4.4
To mirror the database soon to be used in prod

### PR DESCRIPTION
**Pull request by northwestwitch**
I was wondering if we could improve the automatic tests by setting more "extreme" software versions, like in this PR. (Fix #2902)

**How to test**:
1. No tests needed, only github actions

**Review:**
- [ ] code approved by
- [ ] tests executed by GitHub Actions

### CODE REVIEW

**Comment by northwestwitch** [comment]
> Ah look, we need to fix an index situation before switching to the new database:

The error was actually triggered by a test fixtures

**Comment by dnil** [comment]
Sorry where was that fail? I only see good tests above? 😊

**Comment by northwestwitch** [comment]
> Sorry where was that fail? I only see good tests above?

See that the tests don't run and get stuck, I take it as a failure

**Review by dnil — APPROVED** [review]
Looks good to me!

**Pull request merged**
