### PR TITLE
Fix #1209. Add a flag to hide all non-research cases. 

### LINKED ISSUE #1209: New list of cases "research"
Would it be possible to add another list on top of the "active", "solved" and "archived", for cases that are still active, but more in a research mode. We have several cases that are quite old, that we are still working on, but not actively in a clinical setting. Cases we can't really let go, so want to dig deaper.

### PR DESCRIPTION
**Pull request by dnil**
Fix #1209 by adding a flag to hide all non-research cases. Reuses (seemingly unused) existing query option is_research.

### CODE REVIEW

**Comment by northwestwitch** [comment]
Nice @dnil! Could it be possible to fix this PR so you can filter by case status, using the search cases form in cases? The easy way would be writing **status=active** in the textfield.
It's something @sofievonlanthen pointed out and I think it will be useful for others as well. Tried to write just that (status=active) but then I see that the code enters the last else in the if name_query and it's gotten wrong.

**Comment by dnil** [comment]
Yep, can sure fix that: my initial thought was that might be more to my liking than the users, so I skipped it. Most happy to oblige! 😺

**Comment by northwestwitch** [comment]
@dnil I've got some time to work on this today. If you want I can fix it!

**Comment by dnil** [comment]
Thanks; I think I already have a working version of that! As soon as I have a few minutes I can check why its not here - I think I might have started something else in addition to that.. :)

**Comment by northwestwitch** [comment]
Ok but then I wait!

**Comment by northwestwitch** [comment]
Are you ready for a review?

**Comment by dnil** [comment]
Yeah, should be fine - I guess tests, though. Hm, you have a nice one on your search empty query..

**Comment by northwestwitch** [comment]
We could merge  #1211 and write the same type of tests for this one!

**Comment by northwestwitch** [comment]
I'll put it on stage

**Comment by northwestwitch** [comment]
It's on stage and nothing is working.!! Not my PR, which is merged, nor this one. But don't worry, because I've just found out that the script that is restarting the server after installing from the branch is not working. We had it fixed this morning and it's deployed but maybe we have to restart the server for it to take effect. I'll try to figure out!

**Comment by dnil** [comment]
Yeah, but with some text changed, so pretty confusing! Good luck!

**Comment by northwestwitch** [comment]
I know, but I think it's the same thing that happens when you modify the HTML and the backend in Flask : you see the changes in the HTML immediately but you have to restart the server to see the changes in the python code

**Comment by dnil** [comment]
Unless you use livereload, in which case it will occasionally work without restarting, depending on arcane arts. Oh, btw we should probably put the name search explanation in a tooltip or such; its getting big..

**Comment by northwestwitch** [comment]
Stage is working again. I've tested it briefly and looks good. If you are satisfied feel free to merge!

**Pull request merged**
