### PR TITLE
Genevariants urldecode hgvs

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

**How to test**:
1. check a list of gene variants for some variants with VEP HGVS including e.g. synonymous variants like p.Arg101%3D on current master
2. switch to branch and note that they now show URL-decoded like p.Arg101=

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Noooo now!!!! 🤣

**Comment by dnil** [comment]
Later! Note that I went on the new CHANGELOG. Lets not delay for that. 😬

**Comment by northwestwitch** [comment]
> Later! Note that I went on the new CHANGELOG. Lets not delay for that

Nope, I was about to click the button anyway! :)

**Review by northwestwitch — APPROVED** [review]
👍

**Pull request merged**
