### PR TITLE
Prepare release version 4.42

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Choose custom pinned variants to submit to MatchMaker Exchange
- [x] Submit structural variant as genes to the MatchMaker Exchange
- [x] Added function for maintainers and admins to remove gene panels
- [x] Admins can restore deleted gene panels
- [x] A development docker-compose file illustrating the scout/chanjo-report integration
- [x] Show AD on variants view for cancer SV (tumor and normal)
- [x] Cancer SV variants filter AD, AF (tumor and normal)
- [x] Hiding the variants score column also from cancer SVs, as for the SNVs
### Changed
- [x] Enforce same case _id and display_name when updating a case
- [x] Enforce same individual ids, display names and affected status when updating a case
- [x] Display and download HPO gene panels' gene in italics
- [x] Improved documentation for connecting to loqusdb instances (including loqusdbapi)
- [x] A faster-built and lighter Docker image
### Fixed
- [x] Use of deprecated TextField after the upgrade of WTF to v3.0
- [x] Freeze to WTForms to version < 3
- [x] Remove the extra files (bed files and madeline.svg) introduced by mistake
- [x] Cli command loading demo data in docker-compose when case custom images exist and is None
- [x] Increased MongoDB connection serverSelectionTimeoutMS parameter to 30K (default value according to MongoDB documentation)
- [x] Better differentiate old obs counts 0 vs N/A
- [x] Broken cancer variants page when default gene panel was deleted
- [x] Typo in tx_overview function in variant controllers file -- _Tested by collaborators in Lund_
- [x] Fixed loqusdbapi SV search URL
- [x] Removing old gene panels that don't contain the `maintainer` key.

**Review:**
- [x] code approved by DN
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by northwestwitch** [comment]
Before we create this release, I'd like to merge a couple of fixes, #2981 and #2980 by my side. What else would we like to include, how is it going with you new PR @dnil? We said we should try to merge the Pydantic parsing one (#2869) but it's not passing the tests yet.

**Comment by dnil** [comment]
Hm, I have one with cancer SV filtering in the works, but I need a moment to look at some recent Balsamic files. I can push it later in the afternoon to keep you posted. 
Screenshot 2021-11-24 at 10 57 30

**Comment by dnil** [comment]
> Hm, I have one with cancer SV filtering in the works, but I need a moment to look at some recent Balsamic files. I can push it later in the afternoon to keep you posted.
> Screenshot 2021-11-24 at 10 57 30

Ok, I've PRed it as https://github.com/Clinical-Genomics/scout/pull/2992.

**Comment by northwestwitch** [comment]
Fixed loqusdbapi SV search URL: 🆗 

image

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
This release is now deployed on clinical-db production:

image

image

**Pull request merged**
