### PR TITLE
Minor release 4.37

### PR DESCRIPTION
**Pull request by northwestwitch**
Apart from the items in the actual changelog, **I'd like to include also the open PRs marked as "bugfix"**

### Added
- [x] Highlight and show version number for RefSeq MANE transcripts. --Tested by Lund collaborators --
- [x] Added integration to a rerunner service for toggling reanalysis with updated pedigree information
- [x] SpliceAI display and parsing from VEP CSQ
- [x] Display matching tiered variants for cancer variants
- [x] Display a loading icon (spinner) until the page loads completely
- [x] ~~Display filter badges in cancer variants list~~
- [x] Update genes from pre-downloaded file resources
- [x] On login, OS, browser version and screen size are saved anonymously to understand how users are using Scout
- [x] API returning institutes data for a given user: `/api/v1/institutes`
- [x] API returning case data for a given institute: `/api/v1/institutes/<institute_id>/cases`
- [x] Added GMS and Lund university hospital logos to login page
- [x] Made display of Swedac logo configurable
- [x] Support for displaying custom images in case view
- [x] Individual-specific HPO terms
- [x] Optional alamut_key in institute settings for Alamut Plus software
- [x] Case report API endpoint
- [x] Tooltip in case explaining that genes with genome build different than case genome build will not be added to dynamic HPO panel.
### Fixed
- [x] Updated IGV to v2.8.5 to solve missing gene labels on some zoom levels
- [x] Demo cancer case config file to load somatic SNVs and SVs only.
- [x] Expand list of refseq trancripts in ClinVar submission form
- [x] Renamed `All SNVs and INDELs` institute sidebar element to `Search SNVs and INDELs` and fixed its style.
- [x] Add missing parameters to case load-config documentation
- [x] Allow creating/editing gene panels and dynamic gene panels with genes present in genome build 38
- [x] Fixed crash in institute settings page if "collaborators" key is not set in database
- [x] Bugfix broken Pytests
- [x] Bulk dismissing variants error due to key conversion from string to integer
- [x] Fix typo in index documentation
- [x] Don't stop Scout execution if LoqusDB call fails and print stacktrace to log --Simulated a disruption in LoqusDB locally-- 
- [x] Bug when case contains custom images with value `None`
- [x] Bug introduced when fixing another bug in Scout-LoqusDB interaction
- [x] Loading of OMIM diagnoses in Scout demo instance
- [x] Remove the docker-compose with chanjo integration because it doesn't work yet.
- [x] Fixed standard docker-compose with scout demo data and database
- [x] Clinical variant assessments not present for pinned and causative variants on case page.
- [x] MatchMaker matching one node at the time only
- [x] Typo in gene cell on cancer variants page
- [x] Removed link from previously tiered variants badge in cancer variants page
### Changed
- [x] Better naming for variants buttons on cancer track (somatic, germline). Also show cancer research button if available.
- [x] Load case with missing panels in config files, but show warning.
- [x] Changing the (Female, Male) symbols to (F/M) letters in individuals_table and case-sma.
- [x] Print stacktrace if case load command fails
- [x] Added sort icon and a pointer to the cursor to all tables with sortable fields
- [x] Moved variant, gene and panel info from the basic pane to summary panel for all variants.
- [x] Renamed `Basics` panel to `Classify` on variant page.
- [x] Revamped `Basics` panel to a panel dedicated to classify variants
- [x] Revamped the summary panel to be more compact.
- [x] Added dedicated template for cancer variants
- [x] Removed Gene models, Gene annotations and Conservation panels for cancer variants
- [x] Reorganized the orders of panels for variant and cancer variant views
- [x] Added dedicated variant quality panel and removed relevant panes
- [x] A more compact case page
- [x] Removed OMIM genes panel
- [x] Make genes panel, pinned variants panel, causative variants panel and ClinVar panel scrollable on case page
- [x] Update to Scilifelab's 2020 logo
- [x] Update Gens URL to support Gens v2.0 format --Tested by Lund collaborators -
- [x] Refactor tests for parsing case configurations
- [x] Updated links to HPO downloadable resources
- [x] Managed variants filtering defaults to all variant categories
- [x] Changing the (Kind) drop-down according to (Category) drop-down in Managed variant add variant
- [x] Moved Gens button to individuals table --Tested by Lund collaborators --
- [x] Check resource files availability before starting updating OMIM diagnoses
- [x] Fix typo in `SHOW_OBSERVED_VARIANT_ARCHIVE` config param

**Review:**
- [x] code approved by DN
- [x] tests executed by CR, DN

### CODE REVIEW

**Comment by northwestwitch** [comment]
I'm installing this branch on stage so I can start testing the features now

**Comment by dnil** [comment]
Hm, I dont see https://github.com/Clinical-Genomics/scout/pull/2731/ working. It could possibly be related to the gene db update status, but it does not seem so. I'll open/reopen an issue.

**Comment by northwestwitch** [comment]
> Hm, I dont see #2731 working. It could possibly be related to the gene db update status, but it does not seem so. I'll open/reopen an issue.

Could it be because there is only build 37 on stage? I remember we had some issue when updating the genes before summer!

**Comment by northwestwitch** [comment]
> Could it be because there is only build 37 on stage? I remember we had some issue when updating the genes before summer!

No it's not that, the gene is there!

**Comment by dnil** [comment]
> > Could it be because there is only build 37 on stage? I remember we had some issue when updating the genes before summer!
> 
> No it's not that, the gene is there!

Exactly, so genes is up to date, but I will not say that I currently know the update state of e.g. phenotypes on stage. Still, much more likely to be an actual issue with the dynamic panel addition.

**Comment by northwestwitch** [comment]
I was able to test the `Display matching tiered variants for cancer variants` thing by using these 2 cases on stage:
- https://scout-stage.scilifelab.se/cust000/20190327_cancer_T_N/cancer/variants?variant_type=clinical (with tiered var)
- https://scout-stage.scilifelab.se/cust000/20190327_cancer/cancer/variants (fiter for gene FBXW7)

image

It is a bit annoying that when you lick on the black tag it opens a link that goes on the top of the page..

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
Deployed now on Hasta stage (wow we had quite an old version installed in there!):

image

image

**Pull request merged**
