### PR TITLE
Add more server level tests.

### PR DESCRIPTION
**Pull request by dnil**
I thought I’d start with just accessing each page and find it viewable. Not finished but I guess mergeable if it should get stuck. 😸

### CODE REVIEW

**Comment by dnil** [comment]
Sure, good suggestion! I'll give it a shot!

**Comment by northwestwitch** [comment]
Nice!! 👍

**Comment by dnil** [comment]
60.4%; but still doesn't show on the badge. Need 80% for orange next. 😆 CLI tests will help, and there are a couple of main pages to just reload. If we keep adding a test or three for existing functions once in a while between PRs, we will get there

**Comment by henrikstranneheim** [comment]
👍

**Pull request merged**
