### PR TITLE
Added another key GNOMADAF_popmax to parse variant keys

### LINKED ISSUE #1609: Gnomad popmax key name
GnomAD has updated the popmax key from GNOMADAF_POPMAX -> GNOMADAF_popmax. And so have MIP 8.0.

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #1609

**How to test**:
This will be tested when uploading a test case from MIP 8.0. 
Unit testing it for now.

**Expected outcome**:
The functionality should be working

**Review:**
- [x] code approved by MM
- [x] tests executed by Travis CI

### CODE REVIEW

**Comment by northwestwitch** [comment]
> :)

Thanks!

**Comment by northwestwitch** [comment]
Oh no I forgot to update the changelog... Next PR!

**Comment by moonso** [comment]
https://media.giphy.com/media/1kIzz8gc3os9yY49cU/giphy.gif

**Comment by northwestwitch** [comment]
😂

**Pull request merged**
