### PR TITLE
	new file:   iscn.py

### PR DESCRIPTION
**Pull request by J35P312**
Added the iscn coordinate file
The iscn coordinates are formated according to this documentation:
http://varnomen.hgvs.org/bg-material/consultation/svd-wg004/

I devised a small test, feel free to implement it and run it =P:

```
import iscn_scout


print "intrachromosomal test\n"
variant_obj={}
variant_obj["chromosome"]="6"
variant_obj["reference"]="hg19"
variant_obj["position"]=1000
variant_obj["end"]=100000
variant_obj["alt"]="<DEL>"
variant_obj["sub_category"]="del"
variant_obj['cytoband']={}
variant_obj['cytoband']["start"]="p11.13"
variant_obj['cytoband']["end"]="q15.42"

print iscn_scout.get_iscn(variant_obj)


print "interchromosomal test\n"

variant_obj={}
variant_obj["chromosome"]="6"
variant_obj["reference"]="hg19"
variant_obj["position"]=1000
variant_obj["end"]=100000
variant_obj["alt"]="A]19:100000["
variant_obj["sub_category"]="bnd"
variant_obj['cytoband']={}
variant_obj['cytoband']["start"]="p11.13"
variant_obj['cytoband']["end"]="q15.42"

print iscn_scout.get_iscn(variant_obj)
```

### CODE REVIEW

**Comment by moonso** [comment]
Hi @J35P312 I think we need to discuss this a bit more, will you be at scilife anything this week?

**Comment by J35P312** [comment]
That sounds great, I should be back at friday!

**Comment by patrikgrenfeldt** [comment]
Have you had any discussion about this PR?

**Comment by moonso** [comment]
Yes it is still a bit unclear do me. We need to discuss again with @dnil and @J35P312

**Comment by moonso** [comment]
@J35P312 @dnil is this still requested? Should we keep this, open a new later or what do you think?

**Comment by dnil** [comment]
Right! Well, see discussion on #484. Things are better now with cytobands and a better display of both ends on a BND, but it would sure be nicer if we could deliver at least a crude ISCN, if not optimal. I'd encourage adding it to the SV variant page, at least. I also seem to recall @J35P312 made a better version of VCF to ISCN for another project, but not sure how easy it would be to integrate?

**Comment by moonso** [comment]
I'll be pleased to add this if someone explains how it should be done. Where is the explanation for the coordinates?

**Comment by moonso** [comment]
Closing this, we can always reopen if its back on the table

**Pull request closed without merging**
