### PR TITLE
Introduced a BETA IGV alignments visualization tool alongside the Pileup one

### PR DESCRIPTION
**Pull request by northwestwitch**
It's probably safer testing it for a while before replacing the current Pileup viewer with this one.

### CODE REVIEW

**Comment by northwestwitch** [comment]
I don't understand, all test pass on my local computer..

**Comment by moonso** [comment]
Hi @northwestwitch , nice work! I will try to have a look at why tests fails.
Good idea to keep pileup for a while until we are sure that this works

**Comment by northwestwitch** [comment]
Thanks! I'll be also trying to understand what's wrong at the tests level. And I'll update the changelog.

**Comment by moonso** [comment]
@northwestwitch it works fine on my local instance as well!! 
I added a line to handle MT variants.
You should fetch the branch to rasta and test on stage as well. Great job 👌!

**Comment by northwestwitch** [comment]
Thanks, but we have to pass the Travis CI first :(

**Comment by moonso** [comment]
I think we should lock all versions in `requirements.txt` to use the versions that work in our local installation. The error could be that travis downloads the latest versions of some packages like `pymongo` etc

**Comment by northwestwitch** [comment]
yes, I think that might be the case. I've tried to restart some old builds (once passing without problems) and everything seems to fail on Travis now.

**Comment by northwestwitch** [comment]
Python 3.7 was released yesterday. Do you believe in coincidences??? :)

**Comment by northwestwitch** [comment]
Fixed in #c21cf13

**Comment by northwestwitch** [comment]
Fixed by freezing the pymongo dependency to 3.6. I've patched master as well. @patrikgrenfeldt you might want to pull or fix the dependencies file in your pull request.

**Comment by northwestwitch** [comment]
I think I'm done with this feature. I'll need to test it on stage tho.

**Comment by northwestwitch** [comment]
I'll merge and update the code of Scout stage with this PR, so we can test it there. I think it would be nice to have the GV viewer in the newest Scout release in August. To be on the safe side I've introduced the link to the viewer with the label "BETA"

**Comment by henrikstranneheim** [comment]
That would be fantastic!

**Comment by northwestwitch** [comment]
I've updated the code but when I click on the igv viewer link I get a "BAD REQUEST" error. I'll fix it!

**Pull request merged**
