### PR TITLE
Fix gene variants search when looking for similar cases and none is found

### LINKED ISSUE #2313: Bug in gene variants still not fixed
To reproduce: go to [gene variants](https://scout-stage.scilifelab.se/cust000/gene_variants) and look for gene `POT1` with rank score > 5 and in similar case `WNB127AT`

```
2021-01-28 09:13:58,263 - scout.server.app - ERROR: Exception on /cust000/gene_variants [POST] [in /home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 24, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/institutes/views.py", line 218, in gene_variants
    query=form.data, institute_id=institute_id, category="snv", variant_type=variant_type
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/mongo/variant.py", line 326, in gene_variants
    variant_type=variant_type,
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/adapter/mongo/query.py", line 149, in build_variant_query
    select_cases = [similar[0] for similar in similar_cases]
TypeError: 'NoneType' object is not iterable
```

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #2313.

To reproduce on a local instance of Scout:
- Install demo case (`scout setup demo`)
- Install other demo case (`scout --demo load case scout/demo/643595.config.yaml`)
- Start the app and go to this page:http://localhost:5000/cust000/gene_variants
- Search for POT1, rank score > 15 in similar case 643595

**How to test**:
- [ ] Root branch should crash
- [ ] After switching to this branch it should work

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is ready for review

**Comment by northwestwitch** [comment]
Does anybody has time for a quick review @dnil @mikaell ?

**Comment by dnil** [comment]
I can look after lunch if it is still here! 😄

**Review by moonso — APPROVED** [review]
👍

**Comment by dnil** [comment]
FWIW I concur - I had a weird issue when one case had a phenotype added from phenotype groups, not the other, but could not reproduce after reloading. All subsequent tests have been ok with branch version. 😺

**Pull request merged**
