### PR TITLE
Do not open new browser tabs when downloading files

### LINKED ISSUE #2829: SCOUT opens Coverage window upon building "General report" (pdf)
If I would like to download the general report - a "flik" for the coverage analysis is automatically opened. 

The general report is downloaded as usual but it is not necessary to open the coverage data...

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #2829. What I've done in this PR is basically replacing all the changes from #2810 (target="_blank") with "download". Looks like it's working on Chrome and Safari.

**How to test**:
1. On a local instance of scout, use Safari as browser.
2. Go to demo case page and download the following files:
-  general report
- delivery report
- coverage qc report (is in the cancer case)
- HPO gene list (2 buttons)
- VCF2Cytosure

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by dnil** [comment]
Ah, nice! I didn't know about that one. Have you tried it on any MS native one (Edge/IE?). I mean, looks from html docs like it should be supported for recent versions, just curious to see that it really stops the spinner!

**Review by dnil — APPROVED** [review]

**Comment by northwestwitch** [comment]
> MS native one (Edge/IE?)

Nope!

**Comment by dnil** [comment]
Ok, I'll put it on stage and test!

**Comment by northwestwitch** [comment]
Specifications for the "download" attribute: https://www.w3schools.com/tags/att_a_download.asp.

**Pull request merged**
