### PR TITLE
Minor version 4.61

### PR DESCRIPTION
**Pull request by northwestwitch**
Prepare minor version 4.61

### Added
- [ ] Filter case list by cases with variants in ClinVar submission
- [ ] Filter case list by cases containing RNA-seq data - gene_fusion_reports and sample-level tracks (splice junctions and RNA coverage)
- [ ] Additional case category `Ignored`, to be used for cases that don't fall in the existing 'inactive', 'archived', 'solved', 'prioritized' categories
- [ ] Display number of cases shown / total number of cases available for each category on Cases page
- [ ] Moved buttons to modify case status from sidebar to main case page
- [ ] Link to Mutalyzer Normalizer tool on variant's transcripts overview to retrieve official HVGS descriptions
- [ ] Option to manually load RNA MULTIQC report using the command `scout load report -t multiqc_rna`
- [ ] Load RNA MULTIQC automatically for a case if config file contains the `multiqc_rna` key/value
- [ ] Instructions in admin-guide on how to load case reports via the command line
- [ ] Possibility to filter RD variants by a specific genotype call
- [ ] Distinct colors for different inheritance models on RD Variant page
- [ ] Gene panels PDF export with case variants hits by variant type
### Changed
- [ ] Instructions on how to call dibs on scout-stage server in pull request template
- [ ] Deprecated CLI commands `scout load <delivery_report, gene_fusion_report, coverage_qc_report, cnv_report>` to replace them with command `scout load report -t <report type>`
- [ ] Refactored code to display and download custom case reports
- [ ] Do not export `Assertion method` and `Assertion method citation` to ClinVar submission files according to changes to ClinVar's submission spreadsheet templates.
### Fixed
- [ ] Non-admin users saving institute settings would clear loqusdb instance selection
- [ ] Layout of variant position, cytoband and type in SV variant summary
- [ ] Broken `Build Status - GitHub badge` on GitHub README page

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by dnil** [comment]
Aaaah! 👀 🙄 That branch was not properly rebased!?

**Comment by northwestwitch** [comment]
Is this PR merged already??

**Comment by dnil** [comment]
Not directly, but it seems it snuck in via that PR yesterday where you noted it was based off this. I know I rebased it, but I had to stop once during conflict resolution. Likely I messed it up with actually adding this back in during the rebase.

**Comment by dnil** [comment]
Exactly.

**Comment by dnil** [comment]
Reverting #3670 in #3674.. Its just the version number and CHANGELOG heading, but hey, lets do it by the book.

**Pull request merged**
