### PR TITLE
QoL: Cleaner <TD> in Cancer View When Missing Tumor or Normal

### PR DESCRIPTION
**Pull request by mikaell**
Remove a stand alone slash ' / ' from Scout's cancer variant view
when Tumor or Normal is n/a.

This PR is QoL. Ref: https://github.com/Clinical-Genomics/scout/issues/1629

**How to test**:
1. how to install it
git clone 'feature-cancer_variant_view-200219'.

1. how to test it, possibly with real cases/data
Access cancer variant view page. 

**Expected outcome**:
If table data is "N/A", there will be no small-tag below (this previously contained a slash "/"). If table data exists, small-tag will display a ratio. 

Right click and select "Inspect Element" to confirm.

Compare Tumor and Normal fields in attached image:

Screenshot 2020-02-19 at 10 51 21

**Review:**
- [x] code approved by
- [ ] tests executed by
- [ ] "merge and deploy" approved by

### CODE REVIEW

**Comment by hassanfa** [comment]
Looks good to me.

Question: why is ref_depth `-1` in your example? Which VCF demo are you using?

**Comment by mikaell** [comment]
> Question: why is ref_depth `-1` in your example? Which VCF demo are you using? Probably it is not relevant to this PR though...

I haven't got the faintest idea. Pulled a new 'master' and applied my two liner. Must be something hanging around in my mongoDB.

**Comment by northwestwitch** [comment]
Is this ready to merge? We are creating a new release today and we could have it in it!

**Comment by hassanfa** [comment]
I think so. I forgot to approve for code and functionality.

The only catch is that there is a `-1` in ref count number, which I don't understand why it is happening. It is most likely @mikaell 's local installation and remanent of old data.

**Comment by dnil** [comment]
Test on stage perhaps? That would alleviate any concerns with -1 depth?

**Comment by northwestwitch** [comment]
I'm going to test it on stage now!

**Comment by northwestwitch** [comment]
Looking good:

image

**Comment by dnil** [comment]
No its not! 3658 / 18 😊 Please invert!

**Comment by dnil** [comment]
Also consider what it will look like for a single case?

**Comment by northwestwitch** [comment]
> Also consider what it will look like for a single case? Like with tumor-only?

That is the case I tested, the tumor only

**Comment by northwestwitch** [comment]
> No its not! 3658 / 18 😊 Please invert!

18/3658 ?

**Comment by northwestwitch** [comment]
I couldn't find any case with tumor / paired normal with N/A info for the normal

**Comment by dnil** [comment]
> > No its not! 3658 / 18 😊 Please invert!
> 
> 18/3658 ?

Yes, alt / ref.. That's sort of the natural way to show the ratio - even if I assume the percentage is actually alt / (ref + alt), so there could be some confusion. Perhaps just write the number of alt? That would solve both missing normal tissue and any confusion as to if the denominator is all counts or just ref counts?

**Comment by dnil** [comment]
lovingtiger at least have normal N/A so one can see there is no mixup. Good enough?

**Comment by northwestwitch** [comment]
> > > No its not! 3658 / 18 😊 Please invert!
> > 
> > 
> > 18/3658 ?
> 
> Yes, alt / ref.. That's sort of the natural way to show the ratio - even if I assume the percentage is actually alt / (ref + alt), so there could be some confusion. Perhaps just write the number of alt? That would solve both missing normal tissue and any confusion as to if the denominator is all counts or just ref counts?

Done in #1728

**Comment by northwestwitch** [comment]
But I've just swapped them in that PR

**Pull request merged**
