### PR TITLE
Fix case PDF report

### LINKED ISSUE #1461: fix PDF general report
image

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR fixes a bug in the export of the PDF case general report. fix #1461

**How to test**:
1. When clicking on a case report (from the case sidebar), the HTML report looks fine but the PDF version doesn't.
1. Try to export the report of a random variant from scout stage (Download PDF button on the general report) from master and this branch.

**Expected outcome**:
The report from this PR shouldn't have any layout errors
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by dNil
- [x] tests executed by dNil

### CODE REVIEW

**Comment by northwestwitch** [comment]
Ensembl rest API must be down at the moment and the relative tests are not passing. I'll restart the build later. 
Ready for review anyway!

**Comment by dnil** [comment]
Hm, not super smooth on stage: 

Screenshot 2019-11-29 at 07 40 05

Would you like to suggest a strategy? I suppose I could manually force an install of that version of weasyprint on the prod-stage environment?

**Comment by northwestwitch** [comment]
Hi, yes, manual installation is the way i did it yesterday. The page loojed weird because on stage weasyprint sas updated to version 0.50. I wrote this PR in the begibning to use the 0.42 and downgraded stage manually. But i know that before it was working eith the 0.42.3

**Comment by dnil** [comment]
```19-11-29 09:43:04,611 - scout.server.app - ERROR: Exception on /cust002/F0005295-2/case_report [GET] [in /home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 26, in decorated_function
   return render_template(template_name, **context)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
   ctx.app.jinja_env.get_or_select_template(template_name_or_list),
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
   return self.get_template(template_name_or_list, parent, globals)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
   return self._load_template(name, self.make_globals(globals))
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
   template = self.loader.load(self, name, globals)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
   source, filename, uptodate = self.get_source(environment, name)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
   return self._get_source_fast(environment, template)
 File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
   raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: cases/case_report2.html 
```

**Comment by northwestwitch** [comment]
Yes that's my test template, I was sure I remove it, I'll fix it now!

**Comment by northwestwitch** [comment]
Wait, there shouldn't be any more reference to "case_report2" in this branch. Are you positive that you installed the branch and you are not using what is already installed on stage?

**Comment by dnil** [comment]
Well, yes, the manual install is at:
`commit b6b30626ff62e2a9ddadd9a77637a60edf21bd68`. Ah, right, but it's not installed editable, so the conda version stuck anyway. Just a moment..

**Comment by dnil** [comment]
No, same difference?

**Comment by dnil** [comment]
Ah, the old process was still running.

**Comment by dnil** [comment]
The original issue is fixed! Well done!

Screenshot 2019-11-29 at 10 09 06

There are (still?) some beauty issues with overflowing text, but I suppose this is just not LaTeX. E.g. coordinates above or sex below:

Screenshot 2019-11-29 at 10 15 37

**Comment by dnil** [comment]
In practice we will gain three mm of green color ending up on the right side of a boundary, but lose the possibility to automatically update scout. Please help me with some arguments for why this is a good idea?

**Comment by northwestwitch** [comment]
I tried to make changes to our code in order to be able to update weasyprint as we go, but there was always something that didn't work.
The main problem here is that weasyprint doesn't support bootstrap. I think that we should either reformat the report to get rid of any bootstrap style or use another way to export pdfs other than weasyprint. The other day I've tried jsPDF but the result was really ugly (because of bootstrap) 
So I'd suggest getting rid of bootstrap someday soon and use this fix for the time being..

**Comment by northwestwitch** [comment]
> There are (still?) some beauty issues with overflowing text, but I suppose this is just not LaTeX. E.g. coordinates above or sex below:
> 
> Screenshot 2019-11-29 at 10 15 37

It's an html table, hard to fix the style according to the content. But I changed the code so now the gender part is an icon if male or female or 'n.a.' if unknown:
image

Thanks to your comment I've also realized that the report was still using the old icon system. I've now changes to use font awesome, as the rest of the bootstrap 4 pages!

**Pull request merged**
