### PR TITLE
Fetch refseq version from entrez and add it to clinvar form

### LINKED ISSUE #974: Collecting refseq versions to build improved clinvar submission files
This is not so easy, but in order to submit complete info via clinvar variant submission files we need to add  the refseq version to the submission. So far we save in Scout just the refseq code. Maybe it's easily fixable by querying some external database on the fly..

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds refseq versions to transcripts and makes them available to clinvar.
A much overdue fix #974
Could't find a solution to save version number when transcript database is populated via biomart but if you have a better solution I'll happily change this PR

**How to test**:
1. Now refseq versions are not available to clinvar, see pot1 variant example:
image
1. Install a branch and try to submit to clinvar the same variant

**Expected outcome**:
refseq versions should be displayed in clinvar form:
image

The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by MM
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
I'd like to test this on stage but I still can't connect to clinical-db. I don't merge for now

**Comment by dnil** [comment]
I can reach it since yesterday! If no-one else is using stage, I can walk through a few of the PRs there. Ok?

**Comment by northwestwitch** [comment]
> I can reach it since yesterday! If no-one else is using stage, I can walk through a few of the PRs there. Ok?

That would be great, many thanks!

**Comment by dnil** [comment]
Ooh, and nice one btw! Any plans for displaying these on genes / gene panel pages etc - where ever transcripts are shown? I think in particular the prior might come in handy for eg @KickiLagerstedt? 😺

**Comment by northwestwitch** [comment]
I can try to add it to this

**Comment by northwestwitch** [comment]
I suggest we merge this PR and we handle genes and gene panels in another one

**Comment by dnil** [comment]
Yeah, agreed. I can write an issue.

**Comment by dnil** [comment]
Ok, tested on stage! Works just fine: 

Screenshot 2019-08-30 at 15 00 10

**Pull request merged**
