### PR TITLE
Make Safe variant matching badge more visible on case page

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix this badge on case page:

image

To be like this:

image

and this:

image

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
> I see what you mean. In a way its more visible in dark mode as it is now, but on the light mode page this is both more consistent (matches with Prioritized e.g.) and more visible. Adapting might actually be best for both: one way would be to use `class=btn-info`, or keep badge as is and use "class=text-body" color for the foreground. Now that I think about it, wouldn't it also just work if you skip the fg/bg and go for badge-info directly?

I'll try!

**Comment by northwestwitch** [comment]
No, badge-info doesn't work. I think it's bootstrap 4.

image

**Comment by dnil** [comment]
> No, badge-info doesn't work. I think it's bootstrap 4.
> 
> image

Right you are; and it will be text-bg-info in bs 5.2. They do like to keep us on our toes.

**Review by dnil — APPROVED** [review]
💯

**Pull request merged**
