### PR TITLE
Parse and save MANE transcripts info when updating genes in build 38

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug.
- This will make the MANE info available for old variants more up-to-date, since it's collected from latest gene/transcripts records in the database
- Would also help to achieve #4431
- We could use this info instead of relying on VEP annotations when parsing variants

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. Locally, download the ensembl files containing genes and transcript info
2. Run scout --demo update genes -f <path to downloaded files>

**Expected outcome**:
- Transcripts with MANE Select and MANE Plus Clinical should be loaded in the database

**Review:**
- [x] code approved by DN
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
### Local test, loading genes:

image

### Check transcripts loaded with MANE Plus Clinical -> 64

image


### Check transcripts loaded with MANE Select -> 19K

image

**Comment by alkc** [comment]
Newbie question: how was MANE transcript data added prior to this update? Was it only via VEP annotations?

I'm happy that I saw this PR. I had just started to dive into a complaint from one of our geneticists that the MANE transcripts are incorrect for some of our genes and didn't quite know where to start looking.

**Comment by northwestwitch** [comment]
> Newbie question: how was MANE transcript data added prior to this update? Was it only via VEP annotations?

Yes exactly, until now MANE info was exclusively collected from VEP annotations in the VCF files 

This PR was made possible by the fact that we have recently changed how we download the Ensembl resource files (genes/transcripts and exons), see #4268 and its fix #4407. Ensembl resource files contain also MANE info and the data comes from queries performed on the [Ensembl Biomart](https://www.ensembl.org/info/data/biomart/index.html)

In theory, if you keep genes updated, you should have available the latest MANE tags. I think this resource should at least better for oldish cases, where MANE info was collected from the annotations available in VEP at the time the case was loaded.  

Not we just have to go inside the code and replace where MANE is obtained from the variant annotations with Mane tags taken from the transcripts collection.

**Comment by alkc** [comment]
Thank you for the explanation! 

We'll wait then for the release with this PR and see if it solves our issue.

**Pull request merged**
