### PR TITLE
Expand gene lists

### PR DESCRIPTION
**Pull request by robinandeer**
adds a view for listing genes in a gene panel

Left to complete:

- [x] read genes into mongo from gene lists
- [x] define how to link from scout config
- [x] define the new gene list collection

How do we handle versions of gene lists?

### CODE REVIEW

**Comment by moonso** [comment]
Right now the config looks like:
```ini
load = True
ped = tests/vcf_examples/P575_coriell/P575-coriell_pedigree.txt
load_vcf = tests/vcf_examples/P575_coriell/P575-coriell_500.selected.vcf
igv_vcf = tests/vcf_examples/P575_coriell/P575-coriell_500.selected.vcf
human_genome_build = GRCh
human_genome_version = 37
owner = CMMS
madeline = tests/vcf_examples/P575_coriell/P575-coriellped.xml
coverage_report = tests/vcf_examples/P575_coriell/P575-coriell.coverage.pdf
[gene_lists]
  [[MIT]]
    name = MIT
    version = 3.3
  [[PID]]
    name = PID
    version = 5.1
  [[EP]]
    name = EP
    version = 3.3
  [[IEM]]
    name = IEM
    version = 3.3
```
Can you change in pymip so that it looks like:
```ini
load = True
ped = tests/vcf_examples/P575_coriell/P575-coriell_pedigree.txt
load_vcf = tests/vcf_examples/P575_coriell/P575-coriell_500.selected.vcf
igv_vcf = tests/vcf_examples/P575_coriell/P575-coriell_500.selected.vcf
human_genome_build = GRCh
human_genome_version = 37
owner = CMMS
madeline = tests/vcf_examples/P575_coriell/P575-coriellped.xml
coverage_report = tests/vcf_examples/P575_coriell/P575-coriell.coverage.pdf
[gene_lists]
  [[MIT]]
    file = path/to/file
  [[PID]]
    file = path/to/file
  [[EP]]
    file = path/to/file
  [[IEM]]
    file = path/to/file
```
?

**Comment by moonso** [comment]
we should also allow type for the gene lists. like:

```ini
[gene_lists]
  [[MIT]]
    file = path/to/genelistfile
    type = research
```

**Comment by moonso** [comment]
@robinandeer I've done some updates that will break the functionality, we should make difference between gene lists and gene panels.
Please have a look and we can discuss more tomorrow.

**Comment by henrikstranneheim** [comment]
I think that is a good distinction panels (clinical) vs lists (research).

**Pull request merged**
