### PR TITLE
Add docker and workflows

### PR DESCRIPTION
**Pull request by elevu**
In this PR
- Dockerfile and docker compose was added was the React module
- the conf variable REACT_MODULE_URL was added
- the deployment jobs for react modules were removed

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Finally my check for inclusive language action traps something 🎣 

image

Ok perhaps too much 😆 

image

**Comment by dnil** [comment]
Hi! Did you intend to PR this against the scout/Add-mono-repo branch? Anything goes, but otherwise perhaps just talk to Moe and decide on changes to push directly to that branch, or work it out on the scout-react repo first, then PR here?

**Comment by elevu** [comment]
Ahaha, I will fix the inclusive language!
Yes, this PR is meant for the Add-mono-repo branch.
We have to work on this repo and not the Scout-react one since it involves Scout code as well.

Is it a problem getting PR notifications? I don't see another way of discussing code changes that is better than using the git functionality, unfortunately. 
In this case, I tagged Chiara for the PR since we have just discussed these changes. It would be nice to have early feedback since we are working on so many changes, but if you don't think feedback is needed at this stage, you can just approve the PR 😄

**Review by moedarrah — APPROVED** [review]
It looks good to me 👍

**Pull request merged**
