### PR TITLE
Attempt at fixing file system not mounted IGV crash

### LINKED ISSUE #3128: Fix crashes and tighten down file access for file endpoint.
When container mounts to expected fs go down, this can happen:
```
2022-02-02 14:42:09,150 - scout.server.app - ERROR: Exception on /remote/static [GET] [in /venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
   response = self.full_dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
   rv = self.dispatch_request()
 File "/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
 File "/home/worker/app/scout/server/blueprints/alignviewers/views.py", line 72, in remote_static
   if not range_header and (file_path.endswith(".bam") or file_path.endswith(".cram")):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
It wouldn't hurt adding some checks for if the user is asking for files belonging to cases they should have access to. It would take quite some guessing of case names etc to access, but it might be possible to combine with some other situation where we feel that info is trivial to show. Also worth glitch checking. 😬

### PR DESCRIPTION
**Pull request by northwestwitch**
Tentative fix #3128, only the crash part.

I couldn't reproduce locally, so any idea is welcome! My idea is to pass an empty path to the function that servers the file, so it will return "file not found" instead. Basically it will except here: https://github.com/Clinical-Genomics/scout/blob/679bcd1098cdf95010a75b7c56cec9e458e97adc/scout/server/blueprints/alignviewers/partial.py#L54

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. `ssh your.email@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by dnil** [comment]
Good start! I took the liberty of adding a try-except, to remove a crash on missing non-ranged files as well.
We should really think a little about if we don't want to add a layer of security so users can't just snatch each others files, but that can be a separate issue. As long as it doesn't happen by mistake, it is not immediately a bug. We have a reasonable amount of trust in the users.

**Comment by northwestwitch** [comment]
> if we don't want to add a layer of security so users can't just snatch each others files,

I'll think about something. Shouldn't be that hard, no?

**Comment by northwestwitch** [comment]
> if we don't want to add a layer of security so users can't just snatch each others files,

To do it properly, this needs a lot fo refactoring, so perhaps let's have it in another PR?

**Review by dnil — APPROVED** [review]
Right!

**Pull request merged**
