### PR TITLE
iSort

### PR DESCRIPTION
**Pull request by dnil**
This PR adds iSort to the repo GitHub actions and sorts the current deps accordingly.

**How to test**:
1. should pass tests - and the action should be working..

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by dnil** [comment]
Screenshot 2021-04-15 at 09 14 36

**Review by northwestwitch — APPROVED** [review]
If I get it right: 
- This PR sorts alphabetically all the module imports on current master
- Does the same to PR commits

Might be a bit annoying for who's writing PRs without having it installed, but the code gets so much more readable, I like it! 💯

**Comment by dnil** [comment]
Lets try! 😬

**Comment by northwestwitch** [comment]
Mmm I'm getting a lot of messages of this type when I update update the open PRs immediately after merging one:

image

**Comment by dnil** [comment]
I see - my email was down so I never saw them. A few from the transition are expected, eg with old PRs with unsorted parts, but it does seem the lint-and-fix may not quite be doing its job. I'll have a look after lunch!

**Pull request merged**
