### PR TITLE
Fix #1360 - STR next.

### LINKED ISSUE #1360: clinical STR - bug on page?
https://scout.scilifelab.se/cust003/19176/str/variants?variant_type=clinical

If I click on "next page" at the end of the page instead of being moved to another page with STR variants I'm moved to the clinical SNV page.

A bug?

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

**How to test**:
1. Install branch on an instance with cases with plenty of STR variants, eg from a trio
1. Select one such case, view STR variants and test that the Next button gets you to the next STR-variants page, not the next variants page.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by dNil, CR

### CODE REVIEW

**Comment by dnil** [comment]
Tested on stage.

Screenshot 2019-10-03 at 17 59 05

Screenshot 2019-10-03 at 18 00 08

Seems to be working fine. Ready for review.

**Comment by northwestwitch** [comment]
@dnil I'd like to merge first bootstrap4. Then it will be easier to integrate this

**Comment by dnil** [comment]
Hm, I'm not sure? Convince me on this one! I don't mind adapting the code for bs4, but branch wise I'm a little worried. This is a bug fix, where we might end up having to do a hot fix if ppl with trios want to analyse for STRs before we are ready to release bs4?

**Comment by northwestwitch** [comment]
Ok- I'll review

**Pull request merged**
