### PR TITLE
Moves some of the first pages to bs4

### PR DESCRIPTION
**Pull request by moonso**
There are some small problems with the layout. Could you have a look @northwestwitch ?

### CODE REVIEW

**Comment by northwestwitch** [comment]
Nice that you started working on this. I'll take a look as soon as I have some time, Friday at the latest

**Comment by northwestwitch** [comment]
Starting to look at this. I think it's a good start, and I like a lot the scout logo on the top left of the window. But it looks a bit funny:

image

I could continue working on this PR if you want @moonso

**Comment by moonso** [comment]
It's great if you can spend some time on this @northwestwitch . When everything works we can update one page at a time in other PRs

**Comment by northwestwitch** [comment]
It's actually quite nice working with this PR. 

Fixed some stuff, cases now look like this:
image

But I'm afraid this is another of those huge pull requests, because you can't really change some pages only and leave some other ones for later. All or nothing :-/

**Comment by northwestwitch** [comment]
I'm going to close this and open a new PR with another branch that is based and develops further to encompass all changes to scout interface

**Pull request closed without merging**
