### PR TITLE
Refactored and filtered general report data

### LINKED ISSUE #2813: Refactor json object returned by GET /case_report
This task is about refactoring the endpoint for `GET api/v1/insitute_id/case_id/case_report` to match a decoupled backend/frontend architecture.
I enclosed a file of a proposal of a refactored response. I have surely missed something :D 

I refactored according to the following principles:
- Business logic should be in the backend
- Only useful data should be sent
- The structure should be as similar as possible to how it is presented on the frontend
- Objects are better than dictionaries, for example 
the following code:

**before**
```
variants: [
  ['dimissed':[]],
  ['causative':[]]
]
```
**after**
```
variants: {
	dismissed: [],
	causative: []
}
```
These are general guidelines, it is of course fine if they are not perfectly followed. 

This tasks is a blocker for https://github.com/Clinical-Genomics/scout-react/issues/56

[get_case_report_after.txt](https://github.com/Clinical-Genomics/scout/files/7038744/get_case_report_after.txt)
[get_case_report_before.txt](https://github.com/Clinical-Genomics/scout/files/7038745/get_case_report_before.txt)

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #2813.

- Filtered case key/values
- Filtered case individuals key/values
- Filtered institute key/values
- Filtered variants key/values (there is still a lot of information but it's required in the report)
- Modified variants list and arranged in this object:
variants = {
 "causatives_detailed" : [],
 "partial_causatives_detailed" : [],
 "suspects_detailed": [],
 "classified_detailed": [],
 "tagged_detailed": [],
 "tier_detailed": [],
 "dismissed_detailed": []
} 

**How to test**:
1. Install on stage and compare with branch master. General report produced with this branch should be exactly the same as the one produced by master branch.
2. Use the api to retrieve report data. It should contain all the required json info to produce the report

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Review by elevu — APPROVED** [review]
💯

**Comment by northwestwitch** [comment]
Thanks for the review @elevu. Before merging, I'll install it on stage and test the loading of the current report (html and PDF) to make sure that it doesn't break anything

**Comment by northwestwitch** [comment]
Good that I've tested, first error:

```
2021-09-22 08:55:48,704 - scout.server.app - ERROR: Exception on /cust003/15065/case_report [GET] [in /home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 44, in decorated_function
    return render_template(template_name, **context)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/case_report.html", line 1330, in top-level template code
    <td class="text-break"><strong>{{ comment.content | fix_punctuation}}</strong></td>
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/templates/report_base.html", line 14, in top-level template code
    {% block body %}
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/case_report.html", line 60, in block "body"
    {{ pinned_panel() }}
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/cases/templates/cases/case_report.html", line 314, in template
    {% for pinned in variants.suspects_detailed|sort(attribute='variant_rank') %}
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/jinja2/filters.py", line 278, in do_sort
    return sorted(value, key=key_func, reverse=reverse)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'variant_rank'
```

**Comment by northwestwitch** [comment]
This is fixed now, check the report for this case: https://scout-stage.scilifelab.se/cust003/17013. I'm going to merge in 3, 2...

**Pull request merged**
