### PR TITLE
Bugfix loqusdb case count 200903

### PR DESCRIPTION
**Pull request by mikaell**
This PR fixes a bug.

**How to test**:
1. how to test it, possibly with real cases/data

Viewing variant details with a LoqusDB running in the background. The field total number of cases reflects what is in the LoqusDB.

**Expected outcome**:
The functionality should be working
Screenshot 2020-09-03 at 14 07 00

**Review:**
- [x] code approved by CR
- [x] tests executed by ViktorHy

### CODE REVIEW

**Review by northwestwitch — COMMENTED** [review]
Code-wise seems OK, but I have no idea how to test it. Perhaps @ViktorHy could give it a try before we merge?

**Comment by mikaell** [comment]
> Code-wise seems OK, but I have no idea how to test it. Perhaps @ViktorHy could give it a try before we merge?

Patch running on stage at clinical-db. One idea of test is:

1. Call loqusDB form command line with case count:`loqusdb --config /home/proj/production/servers/config/hasta.scilifelab.se/loqusdb.yaml  variants --to-json --variant-id SOME_ID --case-count`

2. Compare to the variant-details in Scout. The amount of total cases should be the same.

**Comment by northwestwitch** [comment]
@mikaell but he has 2 instances of loqus, we have just one on stage. 

Would it be possible to add an automatic test, for instance monkey patching the call to loqus(es), then showing that the variant page contains the right numbers?

**Review by northwestwitch — APPROVED** [review]
Don't forget the changelog!

**Comment by northwestwitch** [comment]
@mikaell if you update the changelog we can merge this one

**Comment by mikaell** [comment]
> @mikaell if you update the changelog we can merge this one

I need some automagic reminder to edit the changelog 😀

**Pull request merged**
