### PR TITLE
Version 4.79.1 - patch export variants without rankscore

### PR DESCRIPTION
**Pull request by dnil**
This PR marks a new Scout release. We apply semantic versioning. This is a patch release since it fixes an issue with an existing function without otherwise adding or modifying anything.

Test on stage:
- [x] Exporting variants without rank score causing page to crash

External and local test:
-  Display custom annotations also on cancer variant page

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Let's include also #4497 in this fix if we can. Now I fix it

**Comment by northwestwitch** [comment]
> Let's include also #4497 in this fix if we can. Now I fix it

Let's see when they test it. If it takes time we could also release this one and have a second patch later (we don't need to deploy it anyway since we don't have custom annotations in Solna)

**Review by northwestwitch — APPROVED** [review]

**Comment by northwestwitch** [comment]
Tested on this page: https://scout-stage.scilifelab.se/cust000/ACC8848A2-75M-FUSION/fusion/variants?variant_type=clinical

**Comment by northwestwitch** [comment]
Deployed on cg-prod-services:

image

**Comment by dnil** [comment]
Deployed:
Screenshot 2024-03-13 at 12 49 53

**Pull request merged**
