### PR TITLE
Simplistic CDN alternative - take three

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality.

A student had a need for a local scout for use inside a highly secure facility (no direct internet). This solves the issue. Just run it on a machine with web access. It will dl all css and js used in the code, and edit accordingly to make the pages use the local copy, like a very simplistic CDN service.

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
Now the command is working: 

image


Tested it by:
- Going offline
- Removing cached images and files

Start the demo server: 😨 

image

**Comment by dnil** [comment]
Ok, that should be it again. I didn't include the debug maps for css, so you will probably still see some issues with resource loading, but I think all styles and scripts should be covered. 😊

**Comment by northwestwitch** [comment]
Much better, but some libs are still missing, for instance font-awesome, that is used in many pages:

image


image

**Comment by dnil** [comment]
Ah, ok the fa one we have (now?) includes some stuff from paths relative to its server, like `format('embedded-opentype'),url('../fonts/fontawesome-webfont.woff?v=4.2.0')`. Ok, lets see..

**Comment by dnil** [comment]
Ok, I think this served its purpose. If needed later, I won't remove the branch, but for a complete version one would have to do a deeper pull, saving also the files that are fetched by the js that is explicitly imported.

**Pull request closed without merging**
