### PR TITLE
IGV.js 2.7.5 - fix #2170 fix #2323

### LINKED ISSUE #2170: Insertion positioning in IGV is one base off?
I'm looking at an insertion called on position chr5:1221430, but in IGV it looks like it would be on position chr5:1221429. 

Variant https://scout.scilifelab.se/cust003/20017/8b3e8fe403457286663a106909776556
It's the insertion of an A changing the sequence from GTAA to GTAAA:
image

However in IGV it looks like the A would be placed before the T, not after - changing the sequence to GATAA (and abolishing a splice site):
image

Now, this is probably just how things are displayed in IGV as I see the same discrepancy when looking at small insertions in other cases. But can you please (a) reassure me that it's IGV that places the insertion one base upstream and (b) tell me if it can be fixed?

### LINKED ISSUE #2323: IGV gene track
Hej, when looking at the GCH1 gene in IGV I'm now missing the gene (the blue exon/intron) in the IGV gene track. See attached file with screenshot before and after the update(?) - Update IGV.js to latest (v2.7.4). (It's the same result when my colleagues check the same region in IGV for other cases). 

[GCH1_IGV.pdf](https://github.com/Clinical-Genomics/scout/files/5894306/GCH1_IGV.pdf)

### PR DESCRIPTION
**Pull request by dnil**
This PR adds a functionality or fixes a bug.

New update from IGV fixing our issues! Neato!

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Review by northwestwitch — APPROVED** [review]
They've released it, nice! 👍

**Comment by northwestwitch** [comment]
I think this is fine to merge @dnil , but perhaps le't's test it on stage first?

**Comment by dnil** [comment]
Precisely! Testing right now, but still seeing the old issue. Will try with clean caches and whatnot.

**Comment by dnil** [comment]
Nope. Still there; see e.g. https://scout-stage.scilifelab.se/cust000/643594-300M/f1e8bf291eb22e2497243c4a8b22c25c and compare to the issue over at igv.js. This is probably still better than current, so I guess we keep it at 2.7.5 for now, but also keep the original issues open and reopen the one over at igv.js - will likely mean making a toy example to help demonstrate what we see.

**Comment by northwestwitch** [comment]
woa, let's not rush it!

image

**Comment by dnil** [comment]
Thats just on that case - the bw track issue; they work in regular IGV but.. We'll get to that one eventually (as Manuel would have it).

**Pull request merged**
