### PR TITLE
Minor release 4.81

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Tag for somatic SV IGH-DUX4 detection samtools script
### Changed
- [x] Upgraded Bootstrap version in reports from 4.3.1 to 5.1.3
### Fixed
- [x] Buttons layout in HPO genes panel on case page
- [x] Added back old variant rankscore index with different key order to help loading on demo instance _Tested by collaborator_
- [x] Cancer case_report panel-table no longer contains inheritance information
- [x] Case report pinned variants card now displays info text if all pinned variants are present in causatives
- [x] Darkmode setting now applies to the comment-box accordion
- [x] Typo in case report causing `cancer_rank_options is undefined` error

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**Review:**
- [x] code approved by DN
- [x] tests executed by DN, CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
Deployed on cg-vm1 now!

**Comment by dnil** [comment]
Right, that was the Pax.. 😸 We didn't have any new gnomAD annotations for the LRS in the end, so I did some release testing.

**Review by dnil — APPROVED** [review]
Looks good! 🥇

**Comment by northwestwitch** [comment]
Deployed on Hasta prod:

image

**Pull request merged**
