### PR TITLE
enable hpo filtering for SVs, fix #710

### LINKED ISSUE #710: Enable HPO list filter for SV list
I have not tested this explicitly yet. Anyone else?

### PR DESCRIPTION
**Pull request by northwestwitch**
This should fix the issue. The problem was that the HPO genes were not passed to the form by the view.

### CODE REVIEW

**Comment by northwestwitch** [comment]
If you refer to the whitespaces of the file that otherwise I left untouched, I have to be honest with you, I didn't realize I changed that file as well! :)

**Comment by moonso** [comment]
Good stuff @northwestwitch 👍

**Comment by dnil** [comment]
Hotfix on that one perhaps? Easy enough, and adds quite a bit of functionality back to the SV-view.

**Comment by moonso** [comment]
@dnil There is a problem with hot fixes at the moment. We need to make a big update of scout and then we will move over to github flow and make releases at least once per week.

**Pull request merged**
