### PR TITLE
Revert "Dashboard labels"

### PR DESCRIPTION
**Pull request by dnil**
Reverts Clinical-Genomics/scout#3670
Accidentally got the 4.61 version PR on there anyway.

### CODE REVIEW

**Review by northwestwitch — COMMENTED** [review]
Isn't it easier to just revert the header of the changelog to [unreleased] and the __version__.py to version = 4.60 ??

**Comment by dnil** [comment]
A lot, but that would mean accepting a git history error - and making a new PR. It would have been done already if it wasn't for the ubuntu / setuptools change.

**Comment by northwestwitch** [comment]
> A lot, but that would mean accepting a git history error - and making a new PR. It would have been done already if it wasn't for the ubuntu / setuptools change.

This one doesn't even pass the tests.. I can approve, it's fine, but I would go the easiest way

**Comment by northwestwitch** [comment]
> A lot, but that would mean accepting a git history error

It's always good to accepts from one's errors 😆

**Comment by dnil** [comment]
> It's always good to accept from one's errors 😆

Ah, yes, but we must not mix up our minds, hearts and souls with the git log.

**Review by northwestwitch — APPROVED** [review]
Looks OK! 👍🏻

**Comment by dnil** [comment]
> > It's always good to accept from one's errors 😆
> 
> Ah, yes, but we must not mix up our minds, hearts and souls with the git log.

Importantly it will now go down in the log as having been acknowledged, reverted and hopefully learned from.

**Comment by northwestwitch** [comment]
> Ah, yes, but we must not mix up our minds, hearts and souls with the git log.

Git log is a product of our minds and self indulgence is a mindful concept. So I see no problem in this :blossom:

**Pull request merged**
