### PR TITLE
Fix #955 - add gene name to dismissed variants.

### LINKED ISSUE #955: Report: Add gene name to dismissed variants
As a bare minimum, it will help convey at a glance what has been dismissed.

### PR DESCRIPTION
**Pull request by dnil**
Improves readability of a long dismissed list.

### CODE REVIEW

**Comment by dnil** [comment]
What do you think? The info is useful, but does it look ok?

**Comment by northwestwitch** [comment]
Hi, I'll look into it ASAP, on Thursday likely, sorry!

**Comment by moonso** [comment]
Hi, this works! I tried do dismiss a variant with multiple genes and it scales good enough:

skarmavbild 2018-09-20 kl 11 27 56

**Comment by moonso** [comment]
I'm merging this @northwestwitch , it's som small anyway

**Pull request merged**
