### PR TITLE
New minor version 4.76

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [x] Pydantic validation of image paths provided in case load config file
- [x] Info on the user which created a ClinVar submission, when available
- [x] Associate .d4 files to case individuals when loading a case via config file
### Changed
- [x] In diagnoses page the load of diseases are initiated by clicking a button
- [x] Revel score, Revel rank score and SpliceAI values are also displayed in Causatives and Validated variants tables
- [x] Remove unused functions and tests
- [x] Analysis type and direct link from cases list for OGM cases
- [x] Removed unused `case_obj` parameter from server/blueprints/variant/controllers/observations function
- [x] Possibility to reset ClinVar submission ID
- [x] Allow ClinVar submissions with custom API key for users registered as ClinVar submitters or when institute doesn't have a preset list of ClinVar submitters
- [x] Ordered event verbs alphabetically and created ClinVar-related user events
- [x] Removed the unused "no-variants" option from the load case command line
### Fixed
- [x] All disease_terms have gene HGNC ids as integers when added to the scout database
- [x] Disease_term identifiers are now prefixed with the name of the coding system
- [x] Command line crashing with error when updating a user that doesn't exist
- [x] Thaw coloredlogs - 15.0.1 restores errorhandler issue
- [x] Thaw crypography - current base image and library version allow Docker builds
- [x] Missing delete icons on phenomodels page
- [x] Missing cryptography lib error while running Scout container on an ARM processor
- [x] Round CADD values with many decimals on causatives and validated variants pages
- [x] Dark-mode visibility of some fields on causatives and validated variants pages
- [x] Clinvar submitters would be cleared when unprivileged users saved institute settings page
- [x] Added a default empty string in cases search form to avoid None default value
- [x] Page crashing when user tries to remove the same variant from a ClinVar submission in different browser tabs
- [x] Update more GnomAD links to GnomAD v4 (v38 SNVs, MT vars, STRs)
- [x] Empty cells for RNA fusion variants in Causatives and Verified variants page
- [x] Submenu icons missing from collapsible actionbar
- [x] The collapsible actionbar had some non-collapsing overly long entries
- [x] Cancer observations for SVs not appearing in the variant details view
- [x] Archived local observations not visible on cancer variantS page
- [x] Empty Population Frequency column in the Cancer SV Variants view
- [x] Capital letters in ClinVar events description shown on case page

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
It's a small thing but I've just realised that the ClinVar events descriptions have capital letters, while other event don't:

image

I'll fix it a small PR!

**Comment by northwestwitch** [comment]
Tested the cli commands on case helpedfilly

image

image

**Comment by northwestwitch** [comment]
## Download files
scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml download everything --api-key xxxxxxx

## Update HPO terms
scout  --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update hpo --hpoterms hpo.obo --hpo-to-genes phenotype_to_genes.txt

## Updating diseases
scout  --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update diseases -f .

## Updating genes
scout --config /scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update genes -f .

## Update the OMIM-AUTO panel
scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update omim --institute cust002 --genemap2 genemap2.txt --mim2genes mim2genes.txt

## Update the PanelApp green genes panel

scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update panelapp-green -i cust002 --force

**Review by dnil — APPROVED** [review]

**Comment by dnil** [comment]
Deployed to prod:
Screenshot 2024-01-25 at 11 01 43

**Comment by northwestwitch** [comment]
Deployed on Hasta prod now!

image

**Pull request merged**
