### PR TITLE
Prepare new minor release 4.26

### PR DESCRIPTION
**Pull request by northwestwitch**
**To be tested well on clinical-db first!**

### Added
- Extend the delete variants command to print analysis date, track, institute, status and research status
- Delete variants by type of analysis (wgs|wes|panel)
- Links to cBioPortal, MutanTP53, IARC TP53, OncoKB, MyCancerGenome, CIViC
### Fixed
- Deleted variants count
### Changed
- Print output of variants delete command as a tab separated table

**Review:**
- [ ] code approved by
- [ ] tests executed by

### CODE REVIEW

**Comment by northwestwitch** [comment]
I'm going to install the branch on clinical-db stage now!

**Review by dnil — APPROVED** [review]

**Comment by dnil** [comment]
> To be tested well on clinical-db first!

Yep! Long time since we skipped deploying so many releases! 😅

**Comment by northwestwitch** [comment]
Yes! It's on stage now. Stuff that should be checked because affect scout web:

- [ ] Links to cBioPortal, MutanTP53, IARC TP53, OncoKB, MyCancerGenome, CIViC
- [ ] Institute-level phenotype models with sub-panels containing HPO and OMIM terms
- [ ] ClinVar submissions crashing due to pinned variants that are not loaded
- [ ] Point ExAC pLI score to new gnomad server address
- [ ] Bug uploading cases missing phenotype terms in config file
- [ ] STRs loaded but not shown on browser page
- [ ] Export dynamic phenotypes with ordered gene lists as PDF

**Comment by dnil** [comment]
Possibly also check related to 
- [ ] Breakpoint two IGV button now shows correct chromosome when different from bp1
- [ ] Missing font lib in Docker image causing the PDF report download page to crash
- [ ] ClinVar submissions crashing due to pinned variants that are not loaded
- [x] Make matching causative and managed variants foldable on case page

**Comment by northwestwitch** [comment]
I'm going to remove variants from this one: https://scout-stage.scilifelab.se/cust000/WNB127AT/variants?variant_type=clinical so we test that the delete function works!

**Comment by northwestwitch** [comment]
Checked again the variants page of the case above: https://scout-stage.scilifelab.se/cust000/WNB127AT/variants?variant_type=clinical and now that the command to remove all variants has finished it works again. It wasn't a bug after all.

**Comment by northwestwitch** [comment]
All good, MERGING!!

**Pull request merged**
