### PR TITLE
Avoid coverage report opening an extra blank page 

### LINKED ISSUE #1477: Clicking on coverage report opens up 2 tabs
One correct and one empty

### PR DESCRIPTION
**Pull request by northwestwitch**
fix #1477

**How to test**:
1. Clicking on coverage report on the sidebar now opens an extra blank page
1. This change should avoid this
1. To be tested on stage where there are actual coverage reports to open for cases.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by dNil
- [x] tests executed by dNil

### CODE REVIEW

**Comment by northwestwitch** [comment]
Haven't tested this but it should work. Ready for review whenever Scout stage is available.

**Comment by dnil** [comment]
Yes, agreed. Lets test, but I need some 💤 before looking mending that install script / environment again. It does not seem to work out of the box right now. It would be so much simpler if we could just separate the different tools into different environments..

**Comment by dnil** [comment]
Ahem, no, the other way around. This now opens an extra tab and loads the coverage report in the original scout browser window. 😝

**Comment by northwestwitch** [comment]
> Ahem, no, the other way around. This now opens an extra tab and loads the coverage report in the original scout browser window. 😝

Thanks for the fix and the review! :)

**Pull request merged**
