### PR TITLE
Prepare minor software version 4.36

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- [ ] ~~Parse and save splice junction tracks from case config file~~
- [x] Tooltip in observations panel, explaining that case variants with no link might be old variants, not uploaded after a case rerun
### Fixed
- [ ] ~~Warning on overwriting variants with same position was no longer shown~~
- [x] Increase the height of the dropdowns to 425px
- [x] More indices for the case table as it grows, specifically for causatives queries
- [x] Splice junction tracks not centered over variant genes
- [x] Total number of research variants count
- [x] Update variants stats in case documents every time new variants are loaded
### Changed
- [x] Clearer warning messages for genes and gene/gene-panels searches in variants filters

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by DN
- [x] tests executed by DN, CR

### CODE REVIEW

**Comment by northwestwitch** [comment]
I'm going to install it on stage now

**Comment by northwestwitch** [comment]
Noooo 😆 

image

**Comment by northwestwitch** [comment]
A case with splice junction tracks on stage: https://scout-stage.scilifelab.se/cust003/14022/e4f6bda7d7150a2c455ee12e6a41e2c9

**Comment by northwestwitch** [comment]
Found a bug that needs fixing:

Triggered by using the HPO list for clinical filtering

image

**Review by dnil — APPROVED** [review]

**Pull request merged**
