### PR TITLE
update PyYaml requirement to use version 5.1

### PR DESCRIPTION
**Pull request by northwestwitch**
The following error was occurring when running scout cli commands from hasta:

```
2019-05-16 10:14:01 hasta.scilifelab.se scout.commands.base[149323] INFO Running scout version 4.4.1
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/S_main/bin/scout", line 11, in <module>
    sys.exit(cli())
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/scout/commands/base.py", line 69, in cli
    cli_config = yaml.load(in_handle, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'
```
This PR fixes there error by forcing the installation of a newer version of PyYaml

**How to test:**
install the branch on hasta cli stage as user hiseq.clinical:
``` 
bash update-scout-cli-stage.sh fix_PyYaml_requirement
```
start stage environment with 'us' command. And finally run any cli command, for instance:
``` 
scout view diseases
``` 

You shouldn't see any error.

- [x] code reviewed by @patrikgrenfeldt 
- [x] tested on hasta stage by @ingkebil 
- [x] merge approved by @dnil

### CODE REVIEW

**Comment by northwestwitch** [comment]
Did you fix this by updating the library? @patrikgrenfeldt @emiliaol

**Comment by patrikgrenfeldt** [comment]
- [x] code reviewed by PG

**Comment by patrikgrenfeldt** [comment]
@CR I have not done anything to solve this

**Comment by northwestwitch** [comment]
Hi @patrikgrenfeldt I don't have the permission to install or test anything on hasta, so someone from team teamname should do it. 
I wrote the instructions on the description comment of the PR!

If you ask me, it feels a bit ridiculous to have to follow this way of merging PRs because for something so small we've been blocked for almost a week.

**Comment by northwestwitch** [comment]
@adrosenbaum this one!

**Comment by adrosenbaum** [comment]
So is this ready to test? Will updating PyYAML cause any dependency problems for other tools? @patrikgrenfeldt @northwestwitch

**Comment by northwestwitch** [comment]
No, because we are already using PyYaml 5.1 on clinical-db prod. It's weird that hasta prod has an old version of the library installed.

**Comment by northwestwitch** [comment]
@ingkebil trying to test it on hasta with my user from home/proj/production/servers/resources/hasta.scilifelab.se

command:
```
bash update-scout-cli-stage.sh fix_PyYaml_requirement
```

I get:  uh-oh, not running script as hiseq.clinical, exiting

**Comment by ingkebil** [comment]
Fixing update script here: https://github.com/Clinical-Genomics/servers/pull/133

**Comment by ingkebil** [comment]
Have you considered that another tool might have locked PyYaml to a specific version and that is why it was never updated? :)

**Comment by ingkebil** [comment]
In any case, I have now checked all requirements.txt from all our tools and it looks like nothing is keeping this version to 3.13.

**Comment by ingkebil** [comment]
Before this PR:
```
[0|0|1161] [kenny.billiau@hasta:~/git/servers/resources/hasta.scilifelab.se] [S_main] fix-scout-cli-stage+* ± scout view diseases
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/S_main/bin/scout", line 11, in <module>
    sys.exit(cli())
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/flask/cli.py", line 411, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/flask/cli.py", line 367, in load_app
    app = call_factory(self, self.create_app)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/flask/cli.py", line 116, in call_factory
    return app_factory()
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/scout/commands/base.py", line 57, in get_app
    cli_config = yaml.load(in_handle, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

```
Confirmed that the provided command results in an error.

```
[0|0|1162] [kenny.billiau@hasta:~/git/servers/resources/hasta.scilifelab.se] [S_main] fix-scout-cli-stage+* 130 ± alias scout
alias scout='/home/proj/bin/conda/envs/S_main/bin/scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml'
[0|0|1162] [kenny.billiau@hasta:~/git/servers/resources/hasta.scilifelab.se] [S_main] fix-scout-cli-stage+* ± scout view diseases
2019-05-27 22:21:08 hasta.scilifelab.se scout.adapter.client[41345] INFO Try to connect to mongodb://stageuser:****@localhost:27030/scout-stage
2019-05-27 22:21:08 hasta.scilifelab.se scout.adapter.client[41345] INFO Connection established
2019-05-27 22:21:08 hasta.scilifelab.se scout.adapter.mongo.base[41345] INFO connecting to database: localhost:27030/scout-stage
2019-05-27 22:21:08 hasta.scilifelab.se scout.commands.base[41345] INFO Running scout version 4.5.0
2019-05-27 22:21:08 hasta.scilifelab.se scout.commands.base[41345] DEBUG Debug logging enabled.
2019-05-27 22:21:08 hasta.scilifelab.se scout.commands.view.diseases[41345] INFO Running scout view diseases
2019-05-27 22:21:08 hasta.scilifelab.se scout.adapter.mongo.hpo[41345] INFO Fetching all disease terms
Disease
2019-05-27 22:21:08 hasta.scilifelab.se scout.adapter.mongo.hpo[41345] INFO Fetching all disease terms
OMIM:612367
OMIM:606788
OMIM:605462
OMIM:155600
OMIM:115665
OMIM:607872
OMIM:608995
...
```

Seems to work!

**Comment by ingkebil** [comment]
As you're on a discrete release cycle and not pushing to production directly, the code owner needs to approve the merge. I presume the code owners would be: CR, DN, and MM? If so, feel free to approve your own merges.

If you want to push this directly to production, please create a release candidate and I'll sing off on the merge and deploy. (Please tell me you're singing merge and deploy to Metallica's Seek and Destroy :metal: )

**Comment by cr** [comment]
@patrikgrenfeldt: This is not the @cr your are looking for. ;)

**Comment by dnil** [comment]
I'm on AC/DC Back in Business, but suggest that we proceed as per tried and tested approach with release preparations with the addendum of notifying production, and deploy testing the release as it could be different than this branch?

**Comment by northwestwitch** [comment]
> @patrikgrenfeldt: This is not the @cr your are looking for. ;)

Nope! :)

**Comment by northwestwitch** [comment]
> Have you considered that another tool might have locked PyYaml to a specific version and that is why it was never updated? :)

Yes, and I dismissed the idea because the same updated version of PyYaml works on clinical-db prod and stage and interacts with the same tools that are also on hasta

**Comment by ingkebil** [comment]
That is incorrect. On clinical-db scout has it's own conda environment while on hasta it is installed together with cg, hk, tb, ... in the same one.

**Comment by northwestwitch** [comment]
> That is incorrect. On clinical-db scout has it's own conda environment while on hasta it is installed together with cg, hk, tb, ... in the same one.

Ah ok!

**Comment by northwestwitch** [comment]
@ingkebil can we deploy this one as well? It's still not in production

**Comment by ingkebil** [comment]
If you want to have this in production right away, please create release candidate that I can approve for merge and deploy.

**Comment by northwestwitch** [comment]
@ingkebil done!

**Comment by patrikgrenfeldt** [comment]
Sorry about that :)
/Patrik

Den mån 27 maj 2019 22:51Christiane Ruetten <notifications@github.com>
skrev:

**Pull request merged**
