### PR TITLE
Re-style case HPO terms to have one phenotype per line

### LINKED ISSUE #4765: Dont linebreak between phenotype checkbox and label. Add select all phenotypes button.
**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**

The label and checkbox need a good span or nbsp to keep them together intuitively. Also, when there are several phenotypes, a select all would be useful. One could consider using 0 filled as a shorthand for select all and skip the button, but there does seem to be some space for one.
bild (1)

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug.
- Fix #4765 

### Main branch:
image

### This branch:
image

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by DN
- [x] tests executed by CR

### CODE REVIEW

**Comment by dnil** [comment]
Did you want to add the "select all", e.g. via the view using all terms if none is selected?

**Comment by northwestwitch** [comment]
> Did you want to add the "select all", e.g. via the view using all terms if none is selected?

I didn't think about it, do you reckon it would be useful?

**Comment by northwestwitch** [comment]
> Did you want to add the "select all", e.g. via the view using all terms if none is selected?

I mean, in terms of creating the HPO panel it is already like this, no?

**Comment by dnil** [comment]
> > Did you want to add the "select all", e.g. via the view using all terms if none is selected?
> 
> I mean, in terms of creating the HPO panel it is already like this, no?

No? It used to be that we deleted any previously created panel on blank submission, but we dropped that when we added the "remove" function for genes / select all genes.

**Comment by northwestwitch** [comment]
> No? It used to be that we deleted any previously created panel on blank submission, but we dropped that when we added the "remove" function for genes / select all genes.

Ah Ok!

**Comment by northwestwitch** [comment]
Added the select:

image

**Comment by dnil** [comment]
> Added the select:

Nice! There is something that bothers me with the text alignment here, especially when there is a lot of empty space. Perhaps moving the toggle down, like just above, or even left of the buttons might work? Or just align the text starts for the toggle and the checkboxes instead?
Screenshot 2024-08-21 at 10 41 04

**Comment by dnil** [comment]
> Like this?

Well, I guess it's an improvement, but I was thinking about the start of the labels.

**Review by dnil — APPROVED** [review]
Good quick solution. It will add a bit of seldom used space in the middle of the page, but helps the interaction and readability quite a bit.

**Pull request merged**
