### PR TITLE
Bootstrap4 ready-sh

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR changes the layout of Scout and introduces nice graphs in the dashboard pages

**How to test**:
1. install the branch on clinical-db so that the changes will be in scout-stage:
```
bash update-scout-stage.sh bootstrap4_ready
 ```
1. Extensive tests should be performed by checking all web pages available.
1. Colors and objects are not fixed and can (and should) be changed. **I'm just suggesting a style** but we can discuss about it together to improve the portal.

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by dNil
- [x] tests executed by dNil, MMA, CR etc

### CODE REVIEW

**Comment by dnil** [comment]
🤸‍♂ 🎉 Wow! Really good and massive work there! Here are some things I noted while browsing:
- visited link color needs an update: purple on blue is hard to read
- really nice with the causatives page gene grouping! Neat!
- But, the causatives are duplicated - even if someone has clicked "causative" twice for them, they should only appear once.  Also, if someone has "reset causative" they should no longer be there. I e do check that the variant is still marked causative on the case, even if you used the event log to find them!
- case page/variant page: the red used for affected is too much. E g a lighter shade will go better with the entire page, and allow some contrast to the black text over it that is now hard to read.
- case page: pedigrees look a bit weirdly aligned?
- case page: nice sidebar, but genome build not visible until I hover over it?!
- case page, sidebar: folding/unfolding reruns/research caused the button to disappear?
- case page, sidebar: assignees should always be open.
- case page: status could be a little bit more colourful - doesn't have to be the whole page, but the change is dramatic now. At least the status:solved in green etc?
- case page, sidebar: why do genome build and rank model change appearance on hover, but not status?
- SV variant page: dissmiss options are all over the place in the dropdown!
- SV variant page: the caller badges look a bit odd down in the corner.
- SV variant page: verify button is not very visible; black on blue is not good- also looks strange when contrasted with the grey box buttons next to it.
- SV variants - and variants - page: most of the dropdowns are messy with unaligned options in other columns.
- Gene_variants: resulting table is rather bleak; add some bg color as with e.g. causatives.
- same with HPO_terms page!
- gene_panels: cell layout is messy for a longer history..
- dashboard: verification stats. Make the graph MUCH smaller, numbers and text large, aligned and clear. This is really only two informative numbers: the total number of verifications and the success (or fail) rate.
- dashboard case stats: cases with is very big compared to the tiny graph text! Alignment in the legend!
- dashboard general stats: lots of colour for few data points.. Oh well. Good tooltips on hover. Alignment: the actual numbers being compared in text should be on top of each other! One thing is missing: actual solve rate, eg solved / (solved + archived unsolved).
- Users: what is the deal with the multiple entries per user? I guess it was the same before. Something similar to the multiple variants above?
- cases page: why different alignment for the different statuses? Looks a bit unfinished, doesn't it?
- cases page: clinvar 1 variants with variants in the plural - I guess that was there before as well?

**Comment by northwestwitch** [comment]
@dnil I've converted your list of comments into a task list. I'll be working on it on these days!

**Comment by northwestwitch** [comment]
I'll copy and paste the task list here, since it's lost in the list of commits:

🤸‍♂ 🎉 Wow! Really good and massive work there! Here are some things I noted while browsing:
- [x] **visited link color needs an update: purple on blue is hard to read**
_I've left the links purple, but the text is white if in a blue badge or button (let me know if I missed any)_
- [x] really nice with the causatives page gene grouping! Neat!
- [x] **But, the causatives are duplicated - even if someone has clicked "causative" twice for them, they should only appear once.  Also, if someone has "reset causative" they should no longer be there. I e do check that the variant is still marked causative on the case, even if you used the event log to find them!**
_I must have introduced a double loop by mistake when I changed the page, nice that you spotted it! I've also adapted the rows of the causatives to their content: it looks nicer now_
- [x] **case page/variant page: the red used for affected is too much. E g a lighter shade will go better with the entire page, and allow some contrast to the black text over it that is now hard to read.**
_Nice suggestion. I made affected individuals line a big lighter, but I couldn't find similar lines in variants page.._
- [ ] **case page: pedigrees look a bit weirdly aligned?**
_Shouldn't pedigree be beside 'individuals' table? Could you find a case that looks weird?_
- [x] **case page: nice sidebar, but genome build not visible until I hover over it?!**
_Fixed_
- [x] **case page, sidebar: folding/unfolding reruns/research caused the button to disappear?**
_do you mean this mess?? Fixed!_
image
- [x] case page, sidebar: assignees should always be open.
_Done_
- [x] case page: status could be a little bit more colourful - doesn't have to be the whole page, but the change is dramatic now. At least the status:solved in green etc?
_I totally agree!_
What about this for solved cases:
image
And this for the archived ones:
image
- [x] **case page, sidebar: why do genome build and rank model change appearance on hover, but not status?**
_It's because they were treated as links. They behave the same way now_
- [x] **SV variant page: dissmiss options are all over the place in the dropdown!**
_I've fixed this in quite an ugly way. The problem is that bootstrap 4 is not compatible with the jquery plugin we used before to create that nice multiselect input field. After a lot of testing I've found another plugin that at least works, but I'm still not 100% satisfied with the result_
- [x] **SV variant page: the caller badges look a bit odd down in the corner.**
_More like inexistent! :) Fixed now_
- [x] SV variant page: verify button is not very visible; black on blue is not good- also looks strange when contrasted with the grey box buttons next to it.
- [x] **SV variants - and variants - page: most of the dropdowns are messy with unaligned options in other columns.**
_fixed it in the uglysh way I mentioned before_
- [x] **Gene_variants: resulting table is rather bleak; add some bg color as with e.g. causatives.**
- [x] **same with HPO_terms page!**
- [ ] **gene_panels: cell layout is messy for a longer history..**
_Which part is messy specifically?_
- [x] **dashboard: verification stats. Make the graph MUCH smaller, numbers and text large, aligned and clear. This is really only two informative numbers: the total number of verifications and the success (or fail) rate.**
_Fixed it like this:_
image
- [x] dashboard case stats: cases with is very big compared to the tiny graph text! Alignment in the legend!
_Fixed it like this:_
image
- [ ] dashboard general stats: lots of colour for few data points.. Oh well. Good tooltips on hover. Alignment: the actual numbers being compared in text should be on top of each other! One thing is missing: actual solve rate, eg solved / (solved + archived unsolved).
- [ ] **Users: what is the deal with the multiple entries per user? I guess it was the same before. Something similar to the multiple variants above?**
_I haven't modified the code of this page, just the layout. 'admin' label was not visible, fixed it now. I'm not sure I understand. What do you mean for multiple entries and multiple variants above?_
- [x] **cases page: why different alignment for the different statuses? Looks a bit unfinished, doesn't it?**
_I hadn't noticed.bootstrap4 doesn't have col-xs class style so it wasn't recognized. Fixed it now_
- [x] **cases page: clinvar 1 variants with variants in the plural - I guess that was there before as well?**
_Yes, it was like this from before, but I've fixed it now_
- [x] verify variant modal displays items in an ugly way.
- [x] fix layout of filters in gene_variants page because new input fields were recently added
- [x] create a nicer confirm window when archiving variants
- [ ] igv and pileup buttons are white on white
- [ ] cgh buttom is invisible

**Comment by northwestwitch** [comment]
@dnil and @moonso I'm done with this PR I think. I've fixed all points from the checklist above and noticed that the coverage dropped by 2% :( 
So I wrote tests and now it's increased by 0.7%.  This branch is on stage now. Take a look when you have time!

**Comment by dnil** [comment]
🤩 Fantastic! Eh, by the way, weren’t you supposed to be on vacation?

**Comment by northwestwitch** [comment]
I am now :)

**Comment by moonso** [comment]
Great Chiara 👩‍🚀 !! Looks fantastic. Have a nice vacation 🏄‍♀

**Comment by moonso** [comment]
Could we edit this comment with stuff that needs to be modified?

## List of remarks

- [ ] **Variant page**. Name of gene panels are "under" header

**Comment by moonso** [comment]
Beautiful work on the dashboard!!

**Comment by northwestwitch** [comment]
> Can you update stage when ready?

I will. I'm working on all the items from the list today

**Comment by northwestwitch** [comment]
I'm checking the checkboxes to remember what I've done in the list. We can uncheck them all when I'm finished and check them all again on stage

**Comment by dnil** [comment]
The Home, User guide and Issues menu options were dropped. I like the click logo for Home, and Institutes is better than the login page, in everything than showing Scout version. Not that I use them much, but perhaps we should have the version accessible as well as a collection of links to external user resources, like, documentation for Scout, MIP, Balsamic, as well as Reporting Issues for these?

**Comment by northwestwitch** [comment]
> * he Home, User guide and Issues menu options were dropped. I like the click logo for Home, and Institutes is better than the login page, in everything than showing Scout version. Not that I use them much, but perhaps we should have the version accessible as well as a collection of links to external user resources, like, documentation for Scout, MIP, Balsamic, as well as Reporting Issues for these?

Good idea, and it's not complicated!

**Comment by northwestwitch** [comment]
Hi @dnil and @moonso. I fixed according to comments (checkboxes) and some more stuff I've seen. If you don't see anything else that requires urgent fixing I suggest we merge for 2 main reasons:

- We have just released version 4.7.1 and we are not releasing for some time, so we'll have time to fix layout stuff while we work on other PRs.
- All new PRs should be created based on this layout, because otherwise they will require fixing after merging.

What do you say?

**Comment by moonso** [comment]
We recruited 3 beta testers yesterday(Nicole, Sophie and Kicki), so we can let them test for a short period before merging

**Comment by northwestwitch** [comment]
> We recruited 3 beta testers yesterday(Nicole, Sophie and Kicki), so we can let them test for a short period before merging

Cool, I'll update stage with the latest code then!

**Comment by northwestwitch** [comment]
MatchMaker page is still using the old layout. Fix it!

**Comment by dnil** [comment]
I might as well add a task then:

- [ ] Colors in the STR view are off; in particular the pre-mut got the same color as undetermined.

Compare
Screenshot 2019-10-04 at 10 07 53
to
Screenshot 2019-10-04 at 10 09 51

**Comment by northwestwitch** [comment]
Fixes all the stuff we mentioned so far. Putting the latest on stage

**Comment by northwestwitch** [comment]
I am soooo done with this PR. If you don't see anything terribly wrong with the new layout, could we (pretty) please merge? Latest code on stage

**Comment by henrikstranneheim** [comment]
Great work Chiara!

**Comment by moonso** [comment]
Looks like you're done here @northwestwitch , amazing work!!

**Comment by northwestwitch** [comment]
> Looks like you're done here @northwestwitch , amazing work!!

Let's try to merge today.

**Comment by northwestwitch** [comment]
> > Looks like you're done here @northwestwitch , amazing work!!
> 
> Let's try to merge today.

You know what, I'll just merge!

**Comment by dnil** [comment]
🥁 :drum:

**Comment by northwestwitch** [comment]
..

**Comment by northwestwitch** [comment]
It's DONE! (Finally, I still can't believe it!) :)

**Pull request merged**
