### PR TITLE
Fix gene variants

### PR DESCRIPTION
**Pull request by dnil**
Fixes two known aestethic issues with the gene_variants view.

### CODE REVIEW

**Comment by northwestwitch** [comment]
Nice! If you are done with this we can test it on stage

**Comment by dnil** [comment]
Feel free to make it more elegant: one could either geralise the owner query to take an array for $in, or actually solve the None to "None" conversion issue. But this addresses the issue.

**Comment by dnil** [comment]
And the last one is to fix #1170 (super groovy admin access to dash) ofcourse.. 🤷‍♂️

**Comment by northwestwitch** [comment]
I'm thinking, with the latest commit to this PR, users which are not admins will not be able to see general stats for all institutes. Maybe this is not what we want. We still want to be able to see all general stats whenever there is not a specific query above which could be revealing sensitive stuff.

For instance testing with test user Stella Gibson I see this:
image

But what if I want to see general stats without querying for specific genes in all cases (also not in Stella's institutes?) I'll work on this!

**Comment by northwestwitch** [comment]
I've added a simple javascript function to make sure that it is not possible to have a slice query on all institutes from the web form

**Comment by northwestwitch** [comment]
I've also updated scout stage with this last commit. Didn't test it yet

**Comment by dnil** [comment]
Dashboard looks solid now. Whats wrong with the ”users” page though? Something strange with the stage: looks fine on a demo install.

**Comment by northwestwitch** [comment]
The error is the following:
File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/login/controllers.py", line 25, in users
user_obj['institutes'] = [store.institute(inst_id) for inst_id in user_obj['institutes']]
KeyError: 'institutes'

I'll fix it and test it on stage again

**Comment by northwestwitch** [comment]
I'm going to merge this. Stop me now or never!

**Pull request merged**
