### PR TITLE
Bump version to 4.61 again

### PR DESCRIPTION
**Pull request by dnil**
This PR marks a new Scout release. We apply semantic versioning. This is a minor release.

### Added
- [x] Filter case list by cases with variants in ClinVar submission
- [x] Filter case list by cases containing RNA-seq data - gene_fusion_reports and sample-level tracks (splice junctions and RNA coverage)
- [x] Additional case category `Ignored`, to be used for cases that don't fall in the existing 'inactive', 'archived', 'solved', 'prioritized' categories
- [x] Display number of cases shown / total number of cases available for each category on Cases page
- [x] Moved buttons to modify case status from sidebar to main case page
- [x] Link to Mutalyzer Normalizer tool on variant's transcripts overview to retrieve official HVGS descriptions
- [x] Option to manually load RNA MULTIQC report using the command `scout load report -t multiqc_rna`
- [x] Load RNA MULTIQC automatically for a case if config file contains the `multiqc_rna` key/value
- [x] Instructions in admin-guide on how to load case reports via the command line
- [x] Possibility to filter RD variants by a specific genotype call
- [x] Distinct colors for different inheritance models on RD Variant page
- [x] Gene panels PDF export with case variants hits by variant type
### Changed
- [x] Instructions on how to call dibs on scout-stage server in pull request template
- [x] Deprecated CLI commands `scout load <delivery_report, gene_fusion_report, coverage_qc_report, cnv_report>` to replace them with command `scout load report -t <report type>`
- [x] Refactored code to display and download custom case reports
- [x] Do not export `Assertion method` and `Assertion method citation` to ClinVar submission files according to changes to ClinVar's submission spreadsheet templates.
- [x] Safe variants matching badge more visible on case page
### Fixed
- [x] Non-admin users saving institute settings would clear loqusdb instance selection
- [x] Layout of variant position, cytoband and type in SV variant summary
- [x] Broken `Build Status - GitHub badge` on GitHub README page
- [x] Visibility of text on grey badges in gene panels PDF exports
- [x] Labels for dashboard search controls
- [x] Dark mode visibility for ClinVar submission
- [x] Whitespaces on outdated panel in extent report

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by CR
- [x] tests executed by DN, CR

### CODE REVIEW

**Review by northwestwitch — APPROVED** [review]
Looks good! 👍🏻

**Comment by northwestwitch** [comment]
But wait, don't merge before we test all those items!

**Comment by dnil** [comment]
I am well aware.. 😊

**Comment by northwestwitch** [comment]
I was about to test the changes in the cli on hasta stage, but the bash [command to deploy this branch on Hasta stage](https://atlas.scilifelab.se/infrastructure/scout/scout_deployment/#hasta_stage) is gone?


image

**Comment by henrikstranneheim** [comment]
Use: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b main`

**Comment by dnil** [comment]
Sorry, it was the same last I did it. I'll add that to the PR template test section! 😊

**Comment by henrikstranneheim** [comment]
@dnil Great Thx. I should have made a PR when I did the change....

**Comment by dnil** [comment]
> @dnil Great Thx. I should have made a PR when I did the change....

We only had a wsgi side test section, so no obvious place to notice it needed changing really.

**Comment by northwestwitch** [comment]
> @dnil Great Thx. I should have made a PR when I did the change....

No worries, we can update the Atlas docs now!

**Comment by dnil** [comment]
☑️ And the loqusdb settings clear is also still fixed.

Changing without admin privileges:
Screenshot 2022-11-24 at 10 44 23
Checking with 
Screenshot 2022-11-24 at 10 45 05

**Comment by northwestwitch** [comment]
Loading a case from a yaml file that contains a multiqc_rna key/value:

image

Yep, worked. Same case as above:

image

**Comment by northwestwitch** [comment]
Deployed on cg-prod-services:

image

**Comment by northwestwitch** [comment]
Deployed also on hasta prod:

image

**Pull request merged**
