### PR TITLE
SPIDEX filter. Fix #693

### LINKED ISSUE #693: Filter on SPIDEX prediction

### PR DESCRIPTION
**Pull request by dnil**
I ended up commiting the human readable version of SPIDEX to the mongodb on load. Not the most elegant or backwards compatible solution. Other suggestions? 

My issue was figuring out how to conduct queries on abs(SPIDEX) - or for that matter queries on the spidex_human transform of that used in display?

### CODE REVIEW

**Comment by moonso** [comment]
I think it would be a bettet solution to display the human readable version in the filter and then convert that to float. The filter can use(pseudo code)  `{'spidex': {'gt': x, '$lt': y}}`

**Comment by dnil** [comment]
Hm, that was my first thought too, but as abs() didn't seem to work in the queries, the get.. well.. complex. But, perhaps that's a small price for not having to update the db. I'll give you an edited PR so you can appreciate what the queries look like - perhaps on the trainride home... :)

**Comment by moonso** [comment]
say that the rules are
```
medium =  0.2 < abs(spidex) < 0.6
high = abs(spidex) > 0.6
```
The filer would then look like

```python
if spidex == 'medium':
    spidex_filter = {'spidex': {'gt': 0.2, '$lt': -0.2}}
elif spidex == 'high':
    spidex_filter = {'spidex': {'gt': 0.6, '$lt': -0.6}}
```
or am I missing something?

**Comment by dnil** [comment]
Yep, in principle, but it grows a little more complicated when you wish to consider missing values, multiple choice and three categories. Not impossible, just a bit messy. Also in general a little dubious to have the values hard coded like that in several places.

Anyway, I have an almost complete version of that stashed; will get back with it when I can!

**Comment by moonso** [comment]
Ok I get it, but still better right. We could solve the problem with hardcoded values on different place by adding some kind of data structure in `scout/constants/__init__.py`

Great!

**Comment by dnil** [comment]
Ok, so I got that other version out and made a makeshift constant data type instead of changing the db schema. See #770 instead. Closing this PR.

**Pull request closed without merging**
