### PR TITLE
Update README.md with Coveralls badge

### PR DESCRIPTION
**Pull request by dnil**

### CODE REVIEW

**Comment by dnil** [comment]
Fix #1145

**Comment by dnil** [comment]
Just a moment; adding scripts as well..

**Comment by northwestwitch** [comment]
57%! Not bad, I would have guessed 30-40% max!

**Comment by dnil** [comment]
Doesn't necessarily say that the right conditions are tested, but it's a good starting point at least! I notice one might add ignores on specific files, file-types etc, but I guess we can play with that on a rainy day.

**Comment by dnil** [comment]
So, I guess that's it for now? The badge should populate once on master.

**Comment by northwestwitch** [comment]
If the coverage is available on coveralls.io, I guess

**Comment by dnil** [comment]
Thanks! Will merge now so I can enjoy writing tests for the slice_dash branch.. ;-)

**Comment by northwestwitch** [comment]
It says coverage unknown. I'll look into it while you write those nice tests :)

**Comment by dnil** [comment]
It just needs a build on the master branch up on coveralls.io: it works nicely showin 57% if you point it to the PR-branch..

**Comment by northwestwitch** [comment]
I just triggered a master build!

**Comment by dnil** [comment]
Works now!

**Pull request merged**
