### PR TITLE
REVEL score deep parsing

### LINKED ISSUE #4693: REVEL score not reported if not present in the first CSQ-field transcript
**Describe the bug**

We have found that some variants do not display their REVEL_score in Scout, despite it being present for CSQ-field transcripts.

We retrieve these values using VEP and the `dbNSFP` plugin, using the `transcript_match=1` setting. This sometimes gives different REVEL_scores for different transcript, but can also lead to no REVEL_score being assigned for certain transcripts.

Here is one example, with subsets of one CSQ entry shown per row. Here the REVEL_score is present, but not for the first transcript. No score is thus shown in Scout.

```
Chrom  Pos       Allele  Feature          MANE_SELECT  REVEL_rankscore  REVEL_score
1      21890003  G/T     ENST00000374673               0.56024
1      21890003  G/T     ENST00000374695  NM_005529.7  0.56024          0.251
1      21890003  G/T     NM_001291860.2                0.56024
1      21890003  G/T     NM_005529.7                   0.56024
1      21890003  G/T     XM_011541318.2                0.56024
1      21890003  G/T     XM_017001120.1                0.56024
1      21890003  G/T     XM_017001121.1                0.56024
1      21890003  G/T     XM_017001122.1                0.56024
```

Digging around in the Scout source code, I found that it indeed seems to be selecting `REVEL_score` from the first transcript:

https://github.com/Clinical-Genomics/scout/blob/2373185c2c9d71cd1bbdaaba9add232d316612d1/scout/parse/variant/variant.py#L230-L233

What do you think. Do you have the same issue? Would it make sense to take the highest score, or the score on the MANE_SELECT instead? Or does Scout expect all transcripts to have the same REVEL_score, i.e. this should be fixed upstream.

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR adds a functionality or fixes a bug:

REVEL score is collected as the maximum REVEL score from all of the variant's transcripts (closes #4693 )

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. Load a case and make sure REVEL score and REVEL rank score are loaded

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by Jakob37
- [x] tests executed by GitHub actions

### CODE REVIEW

**Comment by Jakob37** [comment]
I'll take a look during the day!

**Comment by northwestwitch** [comment]
> I'll take a look during the day!

Great, thanks and no rush!

**Comment by Jakob37** [comment]
Or, aha, now I inspected an already loaded case. I'll see what happens when loading a new case with this pattern.

**Comment by Jakob37** [comment]
OK, when loading with the correct version it looks good.

scout_revel_success

This will be appreciated by our geneticists! They have poked me several times over this, so very nice to have it solved.

A sidenote is that I encountered a stream of warnings that I haven't seen before, and I received "0" as rank score in the end. This might be unrelated to this PR. I can investigate and open a separate issue if indeed it seems to be an issue.

```
5 9a62864ff4ed scout.parse.variant.transcript[176] ERROR Encountered error when parsing variant frequencies for transcript XM_017022510.1: Failed to parse GNOMADG_POPMAX (could not convert string to float: 'amr')
2024-07-22 12:52:35 9a62864ff4ed scout.parse.variant.transcript[176] WARNING Only decomposed/split and normalised VEP v90+ frequencies are supported
```

**Review by Jakob37 — APPROVED** [review]

**Comment by northwestwitch** [comment]
> A sidenote is that I encountered a stream of warnings that I haven't seen before, and I received "0" as rank score in the end. This might be unrelated to this PR. I can investigate and open a separate issue if indeed it seems to be an issue.
> 
> ```
> 5 9a62864ff4ed scout.parse.variant.transcript[176] ERROR Encountered error when parsing variant frequencies for transcript XM_017022510.1: Failed to parse GNOMADG_POPMAX (could not convert string to float: 'amr')
> 2024-07-22 12:52:35 9a62864ff4ed scout.parse.variant.transcript[176] WARNING Only decomposed/split and normalised VEP v90+ frequencies are supported
> ```

Come [from here](https://github.com/Clinical-Genomics/scout/blob/07d0676ce724bc98e46b80e5f92ccdc2994c2112/scout/parse/variant/transcript.py#L346) I think. It's trying to collect a float from a string? If you try to load the demo case locally with `scout setup demo` you get a similar error. Not sure it's a bug tho.

**Comment by northwestwitch** [comment]
Thanks for testing! 🚀 
Merging now, let's check that warning.

**Pull request merged**
