### PR TITLE
Add a simple Docker demo containing database, cli and web app

### LINKED ISSUE #2172: Create a Docker image for Scout
And add instructions on how to use it

### PR DESCRIPTION
**Pull request by northwestwitch**
This PR creates a Dockerfile (Docker image can be pulled from clinicalgenomics Docker Hub) and a runnable demo (based on it) consisting of 3 containers:
- a lightweight mongodb image
- scout-cli --> connected to mongodb, populates the demo database with demo data
- scout-web --> serves the app on localhost, port 5000

Fix #2172

My idea is to add the demo with simple instructions on how to run it in this PR, and then **create another PR to write some documentation on how to use this Docker image in production**.

**How to test**:
- [x]  Stop any running mongodb instance on your computer (you could even remove any scout-demo database, to be sure new data is created by this process)
- [x] Checkout to this branch
- [x] from the the root folder of the app, run the following command:
`docker-compose run -d`

**Expected outcome**:
- [x] The 3 containers should be created
- [x] Connect to the database and make sure that new collections containing demo data are created
- [x] Open the web browser and go to `http://localhost:5000/`. Scout web app should look exactly as the one launched by pip installing the whole thing.
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by MM
- [x] tests executed by CR

### CODE REVIEW

**Comment by moonso** [comment]
For future PRs it could be interesting to think about integration of chanjo and loqusdb as well. Should not be to difficult now that you have the docker compose file in place

**Comment by northwestwitch** [comment]
> For future PRs it could be interesting to think about integration of chanjo and loqusdb as well. Should not be to difficult now that you have the docker compose file in place

Yes! :) would you like to review this one?

**Review by moonso — APPROVED** [review]
Looks great!

**Comment by northwestwitch** [comment]
> Looks great!

Thanks for the review! Merging as soon as it passes the tests. I'll start working on how to use the image in production (both server and CLI) with all the connected servers/databases

**Comment by northwestwitch** [comment]
Running the images: 🆗 

image

Checking that web app works and contains data: 🆗 

image

**Pull request merged**
